Repository GoogleContainerTools/config-sync, pull requests merged in 2022-08, with the labels that each got.

#14 add OWNERS file
  OWNERS
Labels: lgtm, size/S

#16 added mikebz as an owner
  OWNERS
Labels: size/XS, lgtm, approved

#8 rename kubevirt operator files in examples
  e2e/testcases/apply_scoped_resource_test.go
  examples/kubevirt-compiled/clusterrole_kubevirt.io-operator.yaml
  examples/kubevirt/cluster/kubevirt.io-operator-clusterrole.yaml
Labels: size/XS, lgtm, approved

#11 upsert privateCertSecret from RepoSync
  e2e/nomostest/ssh.go
  e2e/testcases/private_cert_secret_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/secret_test.go
Labels: size/L, lgtm, approved

#15 add more owners
  OWNERS
Labels: size/XS, lgtm, approved

#25 Use kstatus for reconciler deployment status
  pkg/reconcilermanager/controllers/deployment_conditions.go
  pkg/reconcilermanager/controllers/deployment_conditions_test.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/secret_test.go
  pkg/util/env.go
  pkg/util/log/error.go
Labels: size/L, lgtm, approved

#24 added a design doc template
  docs/contributing.md
  docs/design-docs/00-template.md
Labels: documentation, size/L, lgtm, approved

#7 add kcc_test to e2e testcases
  e2e/testcases/kcc_test.go
Labels: size/L, lgtm, approved

#26 Updating ACM hierarchial repo documentation landing page
  cmd/nomos/initialize/template_files.go
Labels: size/XS, ok-to-test, lgtm, approved

#12 add watch for privateCertSecret
  e2e/nomostest/predicates.go
  e2e/testcases/private_cert_secret_test.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/secret.go
Labels: size/L, lgtm, approved

#27 skip creating of namespace cert secret on nonlocal
  e2e/nomostest/ssh.go
Labels: size/XS, lgtm, approved

#29 fix caCertPath for shared test envs
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ssh.go
Labels: lgtm, size/S, approved

#19 improve logging when git-server fails to start
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved

#31 pass caCertPath to shared test envs
  e2e/nomostest/new.go
Labels: size/XS, lgtm, approved

#32 Fix printing not ready pod logs
  e2e/nomostest/nt.go
Labels: size/XS, lgtm, approved

#22 Support authenticate to private helm artifact registry with GCPServic…
  cmd/helm-sync/main.go
  e2e/nomostest/sync.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/helmconfig.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/helm/helm.go
  pkg/parse/root.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/util.go
Labels: size/L, lgtm, approved

#33 add wait for ready to kind cluster creation
  e2e/nomostest/ntopts/kind.go
Labels: size/XS, lgtm, approved

#28 Return blocking discover error to prevent resource pruning
  e2e/testcases/apiservice_test.go
  e2e/testdata/apiservice/namespace-custom-metrics.yaml
  e2e/testdata/apiservice/namespace.yaml
  e2e/testdata/apiservice/rbac.yaml
  pkg/util/discovery/server_resourcer.go
Labels: size/L, lgtm, approved

#30 Cleanup logs & errors in reconciler-manager
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/secret_test.go
  pkg/reconcilermanager/controllers/validate_secret.go
Labels: lgtm, approved, size/XL

#37 fix lint-license-headers make target
  Makefile
  e2e/testcases/helm_sync_test.go
  scripts/lint-license-headers.sh
Labels: size/M, lgtm, approved

#36 rename privateCertSecret to caCertSecretRef
  e2e/nomostest/ssh.go
  e2e/testcases/private_cert_secret_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/gitconfig.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/gitconfig.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/parse/root_test.go
  pkg/reconcilermanager/controllers/gitsync_env.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/volumes.go
Labels: size/L, lgtm, approved

#38 fix v1beta1 CACertSecretRef description
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1beta1/gitconfig.go
Labels: size/XS, lgtm, approved

#34 Support authenticate to private helm repo with token
  e2e/testcases/helm_sync_test.go
  pkg/helm/helm.go
Labels: size/M, lgtm, approved

#40 Clean up the share test env after TestHelmARTokenAuth finish.
  e2e/testcases/helm_sync_test.go
Labels: size/XS, lgtm, approved

#42 add make targets for building release candidates
  Makefile.release
  scripts/tag-release-candidate.sh
Labels: size/M, lgtm, approved

#45 enable gh access tokens for tag-release-candidate
  scripts/tag-release-candidate.sh
Labels: size/XS, lgtm, approved

#41 go mod tidy
  go.sum
Labels: size/M, lgtm, approved

#47 add OSS manifest staging dir to make target
  Makefile
  Makefile.build
Labels: lgtm, size/S, approved

#48 reconciler-manager cleanup
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/secret_test.go
Labels: size/L, lgtm, approved

#44 add dockerfile for docker-buildenv image
  Makefile.build
  build/docker-buildenv/Dockerfile
Labels: size/M, lgtm, approved

#51 Update nomos status to report Helm info and status
  cmd/nomos/status/cluster_state.go
  cmd/nomos/status/cluster_state_test.go
Labels: size/L, lgtm, approved

#50 Validate the Helm spec when sourceType is helm
  e2e/testcases/oci_sync_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/validate/raw/validate/repo_sync_validator.go
  pkg/validate/raw/validate/root_sync_validator.go
  pkg/validate/raw/validate/source_spec_validator.go
  pkg/validate/raw/validate/source_spec_validator_test.go
Labels: size/L, lgtm, approved

#43 add targets for promoting RC artifacts
  Makefile
  Makefile.build
  Makefile.release
  scripts/tag-promotion.sh
Labels: size/L, lgtm, approved

#55 Add nan-yu to the owner and approver list
  OWNERS
Labels: size/XS, lgtm, approved

#35 fix: Handle empty initContainers in pod resources
  pkg/core/structured.go
  pkg/core/structured_test.go
  pkg/validate/raw/hydrate/declared_field_hydrator.go
  pkg/validate/raw/hydrate/declared_field_hydrator_raw_test.go
Labels: size/L, lgtm, approved

#53 Remove spec.helm.valuesFiles field and update spec.helm.period field
  cmd/helm-sync/main.go
  e2e/testcases/csr_auth_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/helmconfig.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/helm/helm.go
  pkg/reconcilermanager/controllers/util.go
Labels: size/M, lgtm, approved

#52 update base images to address vulnerabilities
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#59 remove exclusion of acm-psp from oss manifest
  Makefile.build
Labels: size/XS, lgtm, approved

#56 Change helm.values field type from unstructured to JSON
  e2e/testcases/csr_auth_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/helmconfig.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/reconcilermanager/controllers/util.go
Labels: lgtm, size/S, approved

#57 rc tag creation separate from rc build
  Makefile.release
  scripts/tag-release-candidate.sh
Labels: lgtm, size/S, approved

#58 Add haiyanmeng into OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#60 ensure branch is correct and up to date for RC tag
  scripts/tag-release-candidate.sh
Labels: lgtm, size/S, approved

#62 bump git-sync to address vulnerabilities
  manifests/templates/git-importer.yaml
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#65 Increase the test resource-group-controller memory request to 200Mi
  e2e/nomostest/config-sync.go
  e2e/nomostest/git-server.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/webhook.go
  manifests/test-resources/resourcegroup-manifest.yaml
  pkg/api/configmanagement/register.go
  pkg/bugreport/bugreport.go
  pkg/bugreport/constants.go
  pkg/reconcilermanager/controllers/deployment_conditions.go
  pkg/reconcilermanager/controllers/deployment_conditions_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
Labels: size/L, lgtm, approved

#66 Update the IsGKEAutopilotCluster to understand the new autopilot webhook
  pkg/kinds/kinds.go
  pkg/testing/fake/objects.go
  pkg/util/autopilot.go
  pkg/util/autopilot_test.go
Labels: size/L, lgtm, approved

#68 bump resource-group manifest
  manifests/test-resources/resourcegroup-manifest.yaml
Labels: lgtm, size/S, approved

#20 Load allow vertical scale flag in reconciler manager
  cmd/reconciler-manager/main.go
  e2e/testcases/reconciler_manager_test.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, ok-to-test, lgtm, approved

#67 fix: Fix index out of bounds error in nomos status command
  cmd/nomos/status/client.go
Labels: size/M, lgtm, approved

#70 Change VPA e2e test to use dynamic generation validation
  e2e/testcases/reconciler_manager_test.go
Labels: size/XS, lgtm, approved

#69 Remove spec.helm.namespace field from RepoSync API
  cmd/nomos/status/cluster_state.go
  cmd/nomos/status/cluster_state_test.go
  manifests/reposync-crd.yaml
  pkg/api/configsync/v1alpha1/helmconfig.go
  pkg/api/configsync/v1alpha1/reposync_types.go
  pkg/api/configsync/v1alpha1/rootsync_types.go
  pkg/api/configsync/v1alpha1/sync_types.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/api/configsync/v1beta1/reposync_types.go
  pkg/api/configsync/v1beta1/rootsync_types.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret_test.go
  pkg/reconcilermanager/controllers/util.go
  pkg/reposync/constants.go
  pkg/rootsync/constants.go
  pkg/validate/raw/validate/repo_sync_validator.go
  pkg/validate/raw/validate/root_sync_validator.go
  pkg/validate/raw/validate/source_spec_validator.go
  pkg/validate/raw/validate/source_spec_validator_test.go
Labels: size/L, lgtm, approved

#71 Use the mutating webhook to determine if the cluster is an autopilot cluster
  pkg/kinds/kinds.go
  pkg/testing/fake/objects.go
  pkg/util/autopilot.go
  pkg/util/autopilot_test.go
Labels: size/L, lgtm, approved

#64 Allow other declared resources in the config-management-system namespace
  cmd/nomoserrors/examples/examples.go
  e2e/testcases/acme_test.go
  e2e/testdata/object-in-cms-namespace/cmsconfigmap.yaml
  e2e/testdata/object-in-cms-namespace/cmsrole.yaml
  pkg/importer/analyzer/validation/nonhierarchical/illegal_namespace_validator.go
  pkg/validate/raw/validate/namespace_validator.go
  pkg/validate/raw/validate/namespace_validator_test.go
Labels: size/L, lgtm, approved

#49 Fix apiservice bats test
  build/e2e-tests/Dockerfile
  e2e/nomostest/nt.go
  e2e/testcases/apiservice.bats
  e2e/testcases/apiservice_test.go
  pkg/importer/filesystem/reconcile.go
  pkg/util/discovery/server_resourcer.go
Labels: size/L, lgtm, approved

#10 Create a playbook for tuning custom monitoring
  docs/custom-metric-filter.md
Labels: size/L, ok-to-test, lgtm, approved

#73 Use kubectl to deploy necessary RBAC in mono repo apiservice_test
  e2e/testcases/apiservice_test.go
Labels: lgtm, size/S, approved
