Repository GoogleContainerTools/config-sync, pull requests merged in 2022-12, with the labels that each got.

#318 Remove extra space at the end of lines
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: lgtm, size/S, approved

#321 docs: expand OSS usage documentation
  README.md
  docs/installation.md
  docs/usage.md
Labels: size/M, lgtm, approved

#319 Fix over-agressive role binding subject deletion
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/permissions.go
  pkg/reconcilermanager/controllers/permissions_test.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: lgtm, approved, size/XL

#322 Switch to docker buildx for faster builds
  Makefile.build
  Makefile.e2e.ci
  Makefile.oss.prow
  scripts/e2e-kind.sh
Labels: lgtm, size/S, approved

#323 Improve largeResourceGroupError error message
  pkg/applier/applier_err.go
Labels: size/XS, lgtm, approved

#320 fix the override reconcile timeout test
  e2e/nomostest/client.go
  e2e/nomostest/predicates.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testdata/low-priority-pause-deployment.yaml
  go.mod
  go.sum
  pkg/kinds/kinds.go
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/kpt.dev/resourcegroup/LICENSE
  vendor/kpt.dev/resourcegroup/apis/kpt.dev/v1alpha1/groupversion_info.go
  vendor/kpt.dev/resourcegroup/apis/kpt.dev/v1alpha1/resourcegroup_types.go
  vendor/kpt.dev/resourcegroup/apis/kpt.dev/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#327 Update go-junt-report version and config
  build/test-e2e-go/e2e.sh
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
Labels: size/XS, lgtm, approved

#326 Export SLI-related metrics to Google Cloud Monitoring
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: size/XS, lgtm, approved

#328 Refactor the Applier to make it easier to test
  pkg/applier/applier.go
  pkg/applier/applier_test.go
  pkg/applier/client.go
  pkg/applier/clientset.go
  pkg/parse/namespace.go
  pkg/parse/root.go
  pkg/parse/updater.go
  pkg/reconciler/reconciler.go
Labels: size/L, lgtm, approved

#330 Fix the flaky test TestCACertSecretWatch
  e2e/testcases/private_cert_secret_test.go
Labels: lgtm, size/S, approved

#329 Postprocess the junit report by appending a testcases.Failure
  Makefile.build
  build/test-e2e-go/e2e.sh
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  cmd/junit-report/main.go
  cmd/junit-report/resetfailure/reset_failure.go
  cmd/junit-report/resetfailure/reset_failure_test.go
  e2e/testdata/junit-report-updated.xml
  e2e/testdata/junit-report.xml
  go.mod
  go.sum
  scripts/build-junitreport-cli.sh
  scripts/lint-license-headers.sh
  vendor/github.com/jstemmer/go-junit-report/v2/LICENSE
  vendor/github.com/jstemmer/go-junit-report/v2/gtr/gtr.go
  vendor/github.com/jstemmer/go-junit-report/v2/junit/junit.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#305 chore: bump default k8s version for kind
  e2e/flags.go
Labels: size/XS, lgtm, approved

#332 Add dependencies to e2e CentralizedControl setup
  e2e/nomostest/config_sync.go
  pkg/applier/applier.go
  pkg/applier/utils.go
  pkg/applier/utils_test.go
Labels: size/M, lgtm, approved

#331 Fake client fixes
  pkg/reconcilermanager/controllers/otel_controller_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret_test.go
  pkg/reconcilermanager/controllers/validate_secret_test.go
  pkg/remediator/reconcile/reconciler_test.go
  pkg/remediator/reconcile/worker_test.go
  pkg/syncer/syncertest/fake/client.go
  pkg/syncer/syncertest/fake/dynamic_client.go
Labels: lgtm, approved, size/XL

#333 Modify the Delete method in fake client
  pkg/syncer/syncertest/fake/client.go
Labels: size/XS, lgtm, approved
