Repository GoogleContainerTools/config-sync, pull requests merged in 2022-11, with the labels that each got.

#257 Fix vulnerability found in the git-sync image
  manifests/templates/git-importer.yaml
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#246 override pointer instead of a struct instance.
  e2e/nomostest/config_sync.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_resource_limits_test.go
  pkg/api/configsync/v1alpha1/getters.go
  pkg/api/configsync/v1alpha1/gitconfig.go
  pkg/api/configsync/v1alpha1/reposync_types.go
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1alpha1/rootsync_types.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/getters.go
  pkg/api/configsync/v1beta1/reposync_types.go
  pkg/api/configsync/v1beta1/resource_override.go
  pkg/api/configsync/v1beta1/rootsync_types.go
  pkg/api/configsync/v1beta1/sync_types.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/parse/root_test.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved, tide/merge-method-squash

#253 Only update condition timestamps on change
  pkg/reposync/conditions.go
  pkg/reposync/conditions_test.go
  pkg/rootsync/conditions.go
  pkg/rootsync/conditions_test.go
Labels: size/XXL, lgtm, approved

#250 fix: Avoid copying mutex/lock for Parser
  pkg/declared/value.go
Labels: size/XS, lgtm, approved

#261 fix: copy acm-psp from correct directory
  Makefile.build
Labels: size/XS, lgtm, approved

#262 set fake shared env as failed when a test fails
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved

#264 remove monorepo e2e test targets
  Makefile.e2e
  Makefile.e2e.ci
Labels: size/M, lgtm, approved

#265 remove targets related to e2e-tests image
  Makefile.e2e
  Makefile.oss.prow
  build/README.md
  build/e2e-tests/Dockerfile
  build/e2e-tests/build.sh
  build/prow/kubekins-kind/Dockerfile
Labels: size/L, lgtm, approved

#267 remove monorepo e2e testcases
  e2e/flags.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/testcases/basic_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/repoless_test.go
  e2e/testcases/resource_conditions_test.go
  e2e/testcases/switch_mode_test.go
Labels: lgtm, approved, size/XL

#270 remove bats scaffolding for git-server
  Makefile.build
  scripts/init-git-server.sh
  test/manifests/templates/git-server.yaml
Labels: size/L, lgtm, approved

#271 Fix broken link to the development guide
  README.md
Labels: size/XS, lgtm, approved

#274 Fix flakey TestInvalidR*SyncBranchStatus
  e2e/nomostest/metrics/validate.go
Labels: size/M, lgtm, approved

#266 Add last sync timestamp into `nomos status`
  cmd/nomos/status/cluster_state.go
  cmd/nomos/status/cluster_state_test.go
Labels: size/L, lgtm, approved

#275 Disable Syncing condition validation on error
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/sync_ordering_test.go
Labels: size/L, lgtm, approved

#254 add details for test/make params in dev doc
  docs/development.md
Labels: size/M, lgtm, approved

#276 Wait for non-commit changes to sync
  e2e/nomostest/wait.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/helm_sync_test.go
Labels: size/L, lgtm, approved

#273 Cleanup time duration options
  cmd/hydration-controller/main.go
  cmd/reconciler-manager/main.go
  cmd/reconciler/main.go
  pkg/api/configsync/register.go
  pkg/api/configsync/v1alpha1/getters.go
  pkg/api/configsync/v1beta1/getters.go
  pkg/hydrate/controller.go
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/run.go
  pkg/reconciler/reconciler.go
Labels: size/L, lgtm, approved

#278 remove prober-cred scaffolding
  Makefile.e2e.ci
  build/test-e2e-go/e2e.sh
  scripts/oss-prow/README.md
  scripts/oss-prow/prober-runner-sa-key-rotate.sh
  scripts/set-up-workload-identity-configs.sh
Labels: size/L, lgtm, approved

#277 use NS reconciler cluster role in e2e tests
  e2e/nomostest/config_sync.go
  e2e/testcases/composition_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/oci_sync_test.go
Labels: size/M, lgtm, approved

#279 Move periodic status updates into the parser
  cmd/reconciler/main.go
  pkg/api/configsync/register.go
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/run.go
  pkg/reconciler/reconciler.go
Labels: size/L, lgtm, approved

#272 use build-manifests for e2e testing
  .dockerignore
  Makefile.build
  Makefile.e2e
  Makefile.e2e.ci
  docs/development.md
  e2e/flags.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/docker.go
  e2e/nomostest/docker/docker.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/kind.go
  e2e/nomostest/webhook.go
  e2e/testcases/reconciler_manager_test.go
  scripts/e2e-go.sh
Labels: size/L, lgtm, approved

#282 remove legacy manifest scaffolding
  Makefile.build
  scripts/append_manifests/append_manifests.go
Labels: size/L, lgtm, approved

#256 rename test-resources manifest directory
  manifests/cs-namespaces.yaml
  manifests/oss/kustomization.yaml
  manifests/third_party/resourcegroup-manifest.yaml
  scripts/debug-reconciler.sh
Labels: size/XS, lgtm, approved

#283 make prober creds optional in go-gke-ci target (#157)
  Makefile.e2e.ci
  build/test-e2e-go/e2e.sh
Labels: lgtm, size/S, approved

#280 Fix Otel Collector resource mapping
  manifests/templates/otel-collector.yaml
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: size/M, lgtm, approved

#288 Add WatchForObject to e2e test framework
  e2e/nomostest/clean.go
  e2e/nomostest/client.go
  e2e/nomostest/nt.go
  e2e/nomostest/predicates.go
  e2e/nomostest/wait.go
  e2e/nomostest/wait_for_sync.go
  e2e/nomostest/watch.go
  e2e/testcases/cluster_selectors_test.go
Labels: size/L, lgtm, approved

#287 Remove five metrics for tracking feature adoption
  e2e/nomostest/metrics.go
  e2e/nomostest/metrics/validate.go
  e2e/testcases/no_ssl_verify_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_resource_limits_test.go
  pkg/metrics/metrics.go
  pkg/metrics/record.go
  pkg/metrics/register.go
  pkg/metrics/views.go
  pkg/parse/namespace.go
  pkg/parse/root.go
  pkg/reconcilermanager/controllers/gitsync_env.go
  pkg/reconcilermanager/controllers/reconciler_base.go
Labels: size/L, lgtm, approved

#289 Add e2e and unit test coverage to make sure a root|ns-reconciler Deployment is not updated unnecessarily
  e2e/nomostest/predicates.go
  e2e/testcases/override_resource_limits_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#285 test: fine grained permissions for ns reconciler
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/nomostest/policy/reposync.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/composition_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/oci_sync_test.go
Labels: size/L, lgtm, approved

#292 Enhance the `parser_duration_seconds` and `apply_duration_seconds` metrics
  pkg/metrics/views.go
Labels: size/XS, lgtm, approved

#294 Enhance the `apply_operations` metric
  pkg/applier/clientset.go
  pkg/applier/kpt_applier.go
  pkg/metrics/record.go
  pkg/metrics/tagkeys.go
  pkg/metrics/views.go
  pkg/remediator/reconcile/reconciler.go
  pkg/syncer/reconcile/apply.go
  pkg/syncer/syncertest/fake/applier.go
Labels: size/M, lgtm, approved

#293 Enhance the `last_sync_timestamp` metric
  pkg/metrics/record.go
  pkg/parse/namespace.go
  pkg/parse/root.go
Labels: lgtm, approved

#296 Revert "Add e2e and unit test coverage to make sure a root|ns-reconciler Deployment is not updated unnecessarily"
  e2e/nomostest/predicates.go
  e2e/testcases/override_resource_limits_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#298 Removing PodSecurityPolicy validation
  e2e/testcases/acme_test.go
  examples/acme/cluster/podsecuritypolicy.yaml
Labels: size/M, lgtm, approved

#281 Simplify status reporting of sync errors
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespaces_test.go
  pkg/applier/kpt_applier.go
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/run.go
  pkg/parse/updater.go
  pkg/remediator/remediator.go
Labels: size/L, lgtm, approved

#300 Align local-config annotation behavior with kpt
  e2e/testcases/local_config_test.go
  pkg/importer/reader/parse_file.go
  pkg/importer/reader/parse_file_test.go
  pkg/metadata/annotations.go
Labels: size/M, lgtm, approved

#297 Update the kubevirt version from v0.46.1 to v0.58.0
  e2e/testcases/apply_scoped_resource_test.go
  e2e/testcases/cli_test.go
  examples/kubevirt-compiled/clusterrole_kubevirt-operator.yaml
  examples/kubevirt-compiled/clusterrole_kubevirt.io-operator.yaml
  examples/kubevirt-compiled/clusterrole_kubevirt.io:operator.yaml
  examples/kubevirt-compiled/customresourcedefinition_kubevirts.kubevirt.io.yaml
  examples/kubevirt-compiled/kubevirt/deployment_virt-operator.yaml
  examples/kubevirt-compiled/kubevirt/role_kubevirt-operator.yaml
  examples/kubevirt-compiled/namespace_kubevirt.yaml
  examples/kubevirt/README.md
  examples/kubevirt/cluster/kubevirt-cluster-critical.yaml
  examples/kubevirt/cluster/kubevirt-operator-cluster-role.yaml
  examples/kubevirt/cluster/kubevirt.io-operator-clusterrole.yaml
  examples/kubevirt/kubevirt-cr.yaml
  examples/kubevirt/kubevirt-operator.yaml
  examples/kubevirt/namespaces/kubevirt/kubevirt-operator.yaml
  examples/kubevirt/namespaces/kubevirt/ns.yaml
  examples/kubevirt/ns-bookstore1.yaml
  examples/kubevirt/system/README.md
  examples/kubevirt/vm.yaml
Labels: size/XXL, lgtm, approved

#299 Add e2e and unit test coverage to make sure a root|ns-reconciler Deployment is not updated unnecessarily
  e2e/nomostest/predicates.go
  e2e/testcases/override_resource_limits_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#303 Clean up REST client construction
  cmd/nomos/parse/parse.go
  e2e/nomostest/client.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/gke.go
  e2e/nomostest/ntopts/kind.go
  e2e/nomostest/ntopts/new.go
  e2e/nomostest/watch.go
  pkg/client/restconfig/config.go
  pkg/client/restconfig/restconfig.go
Labels: size/L, lgtm, approved

#306 fix: pass WatchConfig to shared test env
  e2e/nomostest/new.go
Labels: size/XS, lgtm, approved

#301 Improve thread-safety of sync status updates
  pkg/applier/kpt_applier.go
  pkg/applier/kpt_applier_test.go
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/run.go
  pkg/parse/state.go
  pkg/parse/updater.go
Labels: size/L, lgtm, approved

#307 ci: consolidate gke cluster args
  build/test-e2e-go/e2e.sh
  docs/development.md
  e2e/flags.go
  e2e/nomostest/client.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/gke.go
  e2e/nomostest/ntopts/kind.go
  e2e/nomostest/ntopts/new.go
Labels: size/L, lgtm, approved

#269 Resolve the fight between reconciler manager and Autopilot
  cmd/reconciler-manager/main.go
  e2e/testcases/reconciler_manager_test.go
  go.mod
  manifests/templates/reconciler-manager-configmap.yaml
  pkg/kinds/resources.go
  pkg/reconcilermanager/controllers/jsonpath.go
  pkg/reconcilermanager/controllers/jsonpath_test.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/syncer/syncertest/fake/dynamic_client.go
Labels: size/XXL, lgtm, approved

#304 ci: remove mono repo clusters
  e2e/testinfra/terraform/prow/prow_clusters.tf
Labels: size/M, lgtm, approved

#308 remove nomos image references
  Makefile
  Makefile.build
Labels: size/XS, lgtm, approved

#311 Make sure users can reset the resources.limits override
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
Labels: size/L, lgtm, approved

#314 Add retries to reduce flakiness
  e2e/testcases/multi_sync_test.go
Labels: lgtm, size/S, approved

#313 Update reconciler manager deployment status compute related logic to …
  e2e/nomostest/git-server.go
  pkg/reconcilermanager/controllers/deployment_conditions.go
  pkg/reconcilermanager/controllers/deployment_conditions_test.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/XXL, lgtm, approved
