Repository GoogleContainerTools/config-sync, pull requests merged in 2022-10, with the labels that each got.

#156 Filter some metrics by pod name for testing
  e2e/nomostest/metrics/validate.go
  e2e/nomostest/nt.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/root_sync_test.go
  pkg/metrics/record.go
  pkg/metrics/tagkeys.go
  pkg/parse/namespace.go
  pkg/parse/root.go
Labels: size/L, lgtm, approved

#170 Increase the wait timeout and add retries to a mono-repo test
  e2e/testcases/resource_conditions_test.go
Labels: size/M, lgtm, approved

#169 Force to enable client-side throttling for mono-repo mode
  cmd/monitor/main.go
  cmd/nomos/parse/parse.go
  e2e/nomostest/new.go
  pkg/client/restconfig/restconfig.go
  pkg/configsync/git-importer.go
Labels: size/M, lgtm, approved

#171 Force to enable client-side throttling for mono-repo mode (#169)
  cmd/monitor/main.go
  cmd/nomos/parse/parse.go
  e2e/nomostest/new.go
  pkg/client/restconfig/restconfig.go
  pkg/configsync/git-importer.go
Labels: size/M, lgtm, approved

#172 Increase the wait timeout and add retries to a mono-repo test (#170)
  e2e/testcases/resource_conditions_test.go
Labels: size/M, lgtm, approved

#173 only create e2e psp resources on psp clusters
  e2e/nomostest/config-sync.go
  e2e/nomostest/git-server.go
  e2e/nomostest/nt.go
Labels: size/M, lgtm, approved

#175 Delete the membership after unregistration failure
  e2e/testcases/csr_auth_test.go
Labels: lgtm, size/S, approved

#176 Retry the validation for the large CRD test
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/multi_sync_test.go
Labels: size/XS, lgtm, approved

#149 run tidy as part of presubmit check
  Makefile
  go.sum
  scripts/prepare-licenses.sh
Labels: size/M, lgtm, approved

#177 pass ARTIFACTS env var into kind container
  scripts/e2e-kind.sh
Labels: size/XS, lgtm, approved

#180 Always enable client-side throttling with QPS 20 for mono-repo mode
  cmd/monitor/main.go
  cmd/nomos/parse/parse.go
  e2e/nomostest/new.go
  pkg/client/restconfig/restconfig.go
  pkg/configsync/git-importer.go
Labels: size/M, lgtm, approved

#181 Always enable client-side throttling with QPS 20 for mono-repo mode (#180)
  cmd/monitor/main.go
  cmd/nomos/parse/parse.go
  e2e/nomostest/new.go
  pkg/client/restconfig/restconfig.go
  pkg/configsync/git-importer.go
Labels: size/M, lgtm, approved

#183 Change test expectation to match behavior
  e2e/testcases/gatekeeper_test.go
Labels: size/XS, lgtm, approved

#182 separate acm-psp manifest from OSS config-sync-manifest
  Makefile.build
  docs/installation.md
Labels: lgtm, size/S, approved, tide/merge-method-rebase

#184 separate acm-psp manifest from OSS config-sync-manifest
  Makefile.build
  docs/installation.md
Labels: lgtm, size/S, approved, tide/merge-method-rebase

#185 Print Repo/RepoSync/RootSync json on e2e error
  e2e/nomostest/sync.go
  pkg/util/log/stringer.go
Labels: size/L, lgtm, approved

#157 make prober creds optional in go-gke-ci target
  Makefile.e2e.ci
  build/test-e2e-go/e2e.sh
Labels: lgtm, size/S, approved

#178 Support passing different types of values directly through helm.values
  cmd/helm-sync/main.go
  e2e/nomostest/predicates.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testdata/root-sync-helm-chart-cr.yaml
  pkg/helm/helm.go
Labels: size/L, lgtm, approved

#186 Skip monorepo NamespaceConfig updates if unchanged
  pkg/importer/differ/differ.go
Labels: lgtm, size/S, approved

#188 Support passing different types of values directly through helm.value…
  cmd/helm-sync/main.go
  e2e/nomostest/predicates.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testdata/root-sync-helm-chart-cr.yaml
  pkg/helm/helm.go
Labels: size/L, lgtm, approved

#193 Delete the membership after unregistration failure (#175)
  e2e/testcases/csr_auth_test.go
Labels: lgtm, size/S, approved

#187 Fix e2e test cleanup to reset git branch
  e2e/nomostest/config-sync.go
  e2e/nomostest/nt.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/root_sync_test.go
Labels: size/L, lgtm, approved

#195 Fix a test failure on autopilot cluster
  e2e/testcases/reconciler_manager_test.go
Labels: lgtm, size/S, approved

#196 Fix bug in RootSync ClusterRoleBinding cleanup
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: lgtm, size/S, approved

#179 Wrap multiple retry blocks in the same one
  e2e/testcases/resource_conditions_test.go
Labels: size/L, lgtm, approved

#199 Revert "Fix e2e test cleanup to reset git branch (#187)"
  e2e/nomostest/config-sync.go
  e2e/nomostest/nt.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/root_sync_test.go
Labels: size/L, lgtm, approved

#200 Clean up the membership for cross-project as well
  e2e/testcases/csr_auth_test.go
Labels: size/XS, lgtm, approved

#202 Fix the test failure on the autopilot cluster
  e2e/testcases/helm_sync_test.go
Labels: lgtm, size/S, approved

#201 Fix mono-repo e2e test cleanup to reset the branch
  e2e/nomostest/config-sync.go
  e2e/nomostest/new.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/root_sync_test.go
Labels: size/L, lgtm, approved

#204 Update the git-sync image tag to fix the vulnerabilities
  manifests/templates/git-importer.yaml
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#192 make openapi test file not depend on dir structure
  pkg/declared/value.go
  pkg/parse/root_test.go
  pkg/testing/openapitest/doc.go
  pkg/validate/raw/hydrate/declared_field_hydrator_raw_test.go
  pkg/validate/raw/hydrate/declared_field_hydrator_test.go
  pkg/validate/validate_test.go
  pkg/webhook/fields_test.go
  pkg/webhook/validate_test.go
Labels: size/L, lgtm, approved

#206 Update the git-sync image tag to fix the vulnerabilities (#204)
  manifests/templates/git-importer.yaml
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#203 fetch all branches in release tagging script
  scripts/tag-promotion.sh
  scripts/tag-release-candidate.sh
Labels: lgtm, size/S, approved

#208 Revert "Fix repoless.bats test cleanup"
  e2e/testcases/repoless.bats
Labels: size/XS, lgtm, approved

#166 Port bats test to Golang
  e2e/nomostest/predicates.go
  e2e/testcases/basic.bats
  e2e/testcases/basic_test.go
  e2e/testcases/legacy_test.go
  scripts/lint-bash.sh
Labels: lgtm, approved, size/XL

#209 fix terraform config for fresh projects
  e2e/testinfra/terraform/README.md
  e2e/testinfra/terraform/common/service_accounts.tf
  e2e/testinfra/terraform/common/services.tf
Labels: lgtm, size/S, approved

#211 Fixed test data for TestNamespaceKubePublicCanBeManaged
  e2e/testcases/basic_test.go
Labels: size/XS, lgtm, approved

#150 Harmonize CLI args
  cmd/monitor/main.go
  cmd/nomos/flags/flags.go
  cmd/nomos/hydrate/hydrate.go
  cmd/nomos/parse/parse.go
  cmd/nomos/vet/vet.go
  cmd/nomos/vet/vet_impl.go
  e2e/nomostest/client.go
  e2e/nomostest/ntopts/gke.go
  pkg/hydrate/tool_util.go
Labels: size/M, ok-to-test, lgtm, approved

#148 redesign build related make targets
  Makefile
  Makefile.build
  Makefile.e2e
  Makefile.e2e.ci
  Makefile.oss
  docs/development.md
  scripts/build-oss.sh
  scripts/get-docker-tag.sh
Labels: size/L, lgtm, approved

#210 test: Fix cleanup for TestSyncFailureAfterSuccessfulSyncs
  e2e/testcases/invalid_git_branch_test.go
Labels: size/XS, lgtm, approved

#125 Added additional annotation validation to TestPreventDeletionRole
  e2e/testcases/lifecycle_directives_test.go
Labels: size/XS, lgtm, approved

#213 Use the public AR/GCR image in the stolos-dev project for testing
  e2e/testcases/oci_sync_test.go
Labels: lgtm, size/S, approved

#214 Remove the k8sallowedrepos.constraints.gatekeeper.sh CRD if needed
  e2e/testcases/gatekeeper_test.go
Labels: size/XS, lgtm, approved

#215 Enable TestConstraintTemplateAndConstraintInSameCommit on Autopilot clusters
  e2e/testcases/gatekeeper_test.go
Labels: size/XS, lgtm, approved

#216 Revert VPA flag and e2e test
  cmd/reconciler-manager/main.go
  e2e/testcases/reconciler_manager_test.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#217 Add retries to mitigate the flakiness
  e2e/testcases/custom_resource_definitions_test.go
Labels: size/XS, lgtm, approved

#218 Update a test git repository
  e2e/testcases/proxy_test.go
  e2e/testdata/proxy/proxy-enabled.yaml
  e2e/testdata/reconciler-manager/rootsync-sample.yaml
Labels: lgtm, size/S, approved

#219 Indentation fix
  docs/custom-metric-filter.md
Labels: size/M, lgtm, approved

#221 add new operator/oss build manifest targets
  Makefile
  Makefile.build
  e2e/nomostest/config-sync.go
  manifests/base/kustomization.yaml
  manifests/operator/kustomization.yaml
  manifests/oss/kustomization.yaml
  manifests/templates/admission-webhook.yaml
  manifests/templates/reconciler-manager.yaml
Labels: size/L, lgtm, approved

#223 expand development docs for running e2e tests
  docs/development.md
Labels: size/M, lgtm, approved

#134 Port bats test to go test
  e2e/nomostest/nt.go
  e2e/testcases/cli.bats
  e2e/testcases/cli_test.go
  e2e/testcases/foo_corp.bats
  e2e/testcases/legacy_test.go
  e2e/testcases/multiversion.bats
  e2e/testcases/operator-no-policy-dir.bats
  e2e/testcases/repoless.bats
  e2e/testcases/repoless_test.go
  examples/repoless-no-ns/default-role.yaml
  examples/repoless/backend-default-ns.yaml
  examples/repoless/backend-default-role.yaml
Labels: lgtm, approved, size/XL

#225 exclude monitor and git-importer from oss manifest
  Makefile.build
Labels: size/XS, lgtm, approved

#228 Increase the metrics wait timeout for Autopilot cluster
  e2e/nomostest/new.go
Labels: size/XS, lgtm, approved

#227 Log more details for command execution failures
  e2e/nomostest/ntopts/gke.go
Labels: lgtm, size/S, approved

#230 GOPATH explicit setting
  scripts/build.sh
  scripts/generate-clientset.sh
Labels: size/XS, lgtm, approved

#233 add policy-controller-psp to operator multirepo manifest
  manifests/operator/kustomization.yaml
Labels: size/XS, lgtm, approved

#235 add hierarchyconfig-crd to multirepo manifest
  manifests/operator/kustomization.yaml
Labels: size/XS, lgtm, approved

#234 Fix reconciler controllers to exit cleanly
  pkg/reconciler/reconciler.go
  pkg/remediator/queue/queue.go
  pkg/remediator/reconcile/worker.go
  pkg/remediator/reconcile/worker_test.go
  pkg/remediator/remediator.go
  pkg/syncer/syncertest/fake/applier.go
  pkg/syncer/syncertest/fake/client.go
Labels: size/L, lgtm, approved

#240 Remove unused UpstreamRepoURL from e2e tests
  e2e/nomostest/config-sync.go
  e2e/nomostest/git.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/nomostest/ntopts/nomos.go
  e2e/testcases/multi_sync_test.go
Labels: size/M, lgtm, approved

#238 make test KUBECONFIG thread safe
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/gke.go
  e2e/nomostest/ntopts/kind.go
  e2e/nomostest/ntopts/new.go
  e2e/testcases/cli_test.go
Labels: size/L, lgtm, approved

#229 Skip validating non-central root reconciler Pods in validateMultiRepoPods
  e2e/nomostest/config-sync.go
  e2e/nomostest/git-server.go
Labels: lgtm, size/S, approved

#241 Increase the retry timeout and aggregate the validation errors in a multierr
  e2e/testcases/root_sync_test.go
Labels: size/M, lgtm, approved

#231 using pointers for optional structs
  cmd/nomos/migrate/migrate.go
  e2e/nomostest/config-sync.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/private_cert_secret_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/gitconfig.go
  pkg/api/configsync/v1alpha1/helmconfig.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/gitconfig.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/api/configsync/v1beta1/sync_types.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/parse/root_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/secret_test.go
  pkg/validate/raw/validate/source_spec_validator.go
  pkg/validate/raw/validate/source_spec_validator_test.go
Labels: size/L, lgtm, approved, tide/merge-method-squash

#243 run configsync-crds as part of presubmit
  Makefile
  Makefile.build
  Makefile.reconcilermanager
Labels: size/M, lgtm, approved

#244 remove public grant to public ar registry
  e2e/testinfra/terraform/prow/registries.tf
Labels: lgtm, size/S, approved

#247 update installation docs to install from url
  docs/installation.md
Labels: lgtm, size/S, approved

#236 add support for shared kind clusters
  e2e/flags.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/kind.go
  e2e/nomostest/ntopts/new.go
  e2e/nomostest/testing/ntb.go
  e2e/testcases/main_test.go
  e2e/testcases/reconciler_manager_test.go
Labels: size/L, lgtm, approved

#248 add link to development.md from top level readme
  README.md
Labels: size/XS, lgtm, approved

#251 Add test validation for annotation/label removal
  e2e/nomostest/predicates.go
  e2e/testcases/lifecycle_directives_test.go
Labels: size/M, lgtm, approved

#252 Split nt.go into multiple files
  e2e/nomostest/clean.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/metrics.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/validate.go
  e2e/nomostest/wait.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/managed_resources_test.go
Labels: size/XXL, lgtm, approved
