Repository GoogleContainerTools/config-sync, pull requests merged in 2022-09, with the labels that each got.

#75 Update TestHelmNamespaceRepo to make it works in shared test environment
  e2e/testcases/helm_sync_test.go
Labels: size/XS, lgtm, approved

#76 Fix InvalidSourceType error message
  pkg/validate/raw/validate/source_spec_validator.go
Labels: size/XS, lgtm, approved

#79 Only remove manually applied resource in mono repo go test
  e2e/testcases/apiservice_test.go
Labels: size/XS, lgtm, approved

#78 Avoid object updates if semantically equal
  pkg/importer/differ/differ.go
  pkg/parse/namespace.go
  pkg/parse/root.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/syncer/crd/reconcile.go
  pkg/syncer/reconcile/apply.go
  pkg/syncer/reconcile/repostatus.go
  pkg/syncer/reconcile/util.go
  pkg/syncer/sync/reconciler.go
  pkg/util/compare/compare.go
  pkg/util/compare/comparer.go
  pkg/util/compare/comparer_test.go
  pkg/util/repo/client.go
  pkg/util/watch/manager.go
Labels: size/M, lgtm, approved

#82 Create the testing git projects to a specific gitlab group
  e2e/nomostest/gitproviders/gitlab.go
Labels: lgtm, size/S, approved

#83 Update the installation guide for the ImagePullBackoff error
  docs/installation.md
Labels: lgtm, size/S, approved

#84 Fix cleanup for Gatekeeper tests
  e2e/nomostest/nt.go
  e2e/testcases/gatekeeper_test.go
  e2e/testcases/resource_conditions_test.go
Labels: size/L, lgtm, approved

#86 Print container logs when repo setup fails
  e2e/nomostest/new.go
Labels: lgtm, size/S, approved

#88 Fix the test failure for TestResourceConditionAnnotations
  e2e/nomostest/nt.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/multiversion_test.go
  e2e/testcases/resource_conditions_test.go
Labels: size/M, lgtm, approved

#85 Update contributor guide
  README.md
  docs/contributing.md
Labels: size/M, lgtm, approved

#87 update make targets to support generic registry
  Makefile
  Makefile.build
  Makefile.e2e
  Makefile.e2e.ci
  Makefile.release
Labels: size/M, lgtm, approved

#91 Fix TestResourceConditionAnnotations
  e2e/testcases/resource_conditions_test.go
Labels: size/XS, lgtm, approved

#92 Fix mono-repo "failed to create object" error
  pkg/importer/differ/differ.go
  pkg/syncer/client/client.go
  pkg/syncer/client/client_test.go
  pkg/syncer/reconcile/apply.go
  pkg/syncer/reconcile/namespaceconfig.go
  pkg/syncer/reconcile/util.go
  pkg/syncer/sync/reconciler.go
  pkg/util/repo/client.go
Labels: size/L, lgtm, approved

#93 Add e2e tests for Helm support
  e2e/testcases/helm_sync_test.go
Labels: size/L, lgtm, approved

#94 Fix broken links in documentation
  README.md
  docs/contributing.md
Labels: lgtm, size/S, approved

#98 Fail test during reset if sync still in-progress
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/sync.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/resource_conditions_test.go
  pkg/testing/fake/repo.go
  pkg/util/repo/default.go
Labels: size/L, lgtm, approved

#101 Split the sync ordering e2e test into several shorter ones
  e2e/testcases/sync_ordering_test.go
Labels: lgtm, size/S, approved

#97 remove docker-buildenv Dockerfile/target
  Makefile.build
  build/docker-buildenv/Dockerfile
Labels: size/M, lgtm, approved

#99 make retagging functionality generic
  Makefile
  Makefile.build
  Makefile.e2e
Labels: size/M, lgtm, approved

#102 Remove the ResourceGroup option that is not used
  e2e/nomostest/ntopts/multi_repo.go
  e2e/testcases/resource_group_controller_test.go
Labels: lgtm, size/S, approved

#105 Use opencensus based exporter for monitoring
  e2e/testdata/reconciler-manager-configmap-updated.yaml
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
Labels: lgtm, size/S, approved

#89 Add unit test for parseAndUpdate
  pkg/parse/root_test.go
  pkg/syncer/syncertest/fake/discovery_client.go
Labels: size/L, lgtm, approved

#103 remove GH_TOKEN functionality from tagging scripts
  scripts/tag-promotion.sh
  scripts/tag-release-candidate.sh
Labels: size/XS, lgtm, approved

#109 Fix helm.values field to support mutiple values
  e2e/testcases/helm_sync_test.go
  pkg/helm/helm.go
  pkg/reconcilermanager/controllers/util.go
Labels: size/M, lgtm, approved

#113 Fix helm.values field to support mutiple values (#109)
  e2e/testcases/helm_sync_test.go
  pkg/helm/helm.go
  pkg/reconcilermanager/controllers/util.go
Labels: size/M, lgtm, approved

#108 Split e2e tests into multiple test groups by features
  Makefile.e2e.ci
  e2e/flags.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/new.go
  e2e/nomostest/testing/feature.go
  e2e/nomostest/testing/wrapper.go
  e2e/testcases/acme_test.go
  e2e/testcases/admission_test.go
  e2e/testcases/adopt_client_side_applied_test.go
  e2e/testcases/apiservice_test.go
  e2e/testcases/apply_scoped_resource_test.go
  e2e/testcases/cli_test.go
  e2e/testcases/cluster_resources_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/composition_test.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/custom_resource_definitions_schema_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/declared_fields_test.go
  e2e/testcases/gatekeeper_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/kptfile_test.go
  e2e/testcases/legacy_test.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/local_config_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/multiversion_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/no_ssl_verify_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/policy_dir_test.go
  e2e/testcases/preserve_fields_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/proxy_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/resource_conditions_test.go
  e2e/testcases/resource_group_controller_test.go
  e2e/testcases/root_sync_test.go
  e2e/testcases/status_enablement_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/switch_mode_test.go
  e2e/testcases/sync_ordering_test.go
Labels: lgtm, approved, size/XL

#115 Don't send sync metrics unless status has changed
  pkg/parse/namespace.go
  pkg/parse/root.go
Labels: lgtm, size/S, approved

#116 Add make rules for running a subset of e2e tests in a presbumit nomo/multi job
  Makefile.e2e
  Makefile.e2e.ci
  scripts/e2e-kind.sh
Labels: size/M, lgtm, approved

#117 Log metrics recorded and received for debugging
  e2e/nomostest/metrics/parse.go
  e2e/nomostest/metrics/validate.go
  e2e/nomostest/nt.go
  e2e/testcases/override_resource_limits_test.go
  pkg/kmetrics/record.go
  pkg/metrics/record.go
Labels: size/L, lgtm, approved

#114 Add GCP+GKE metric attributes
  docs/metric-resource-attributes.md
  manifests/otel-agent-cm.yaml
  manifests/test-resources/resourcegroup-manifest.yaml
Labels: size/M, lgtm, approved

#118 Send correct number of declared_resources
  pkg/declared/resources.go
  pkg/parse/updater.go
Labels: lgtm, size/S, approved

#119 Validate metrics after Sync, not just Apply
  e2e/nomostest/metrics/validate.go
  e2e/nomostest/nt.go
  pkg/importer/filesystem/reconcile.go
  pkg/metrics/record.go
  pkg/metrics/tagkeys.go
  pkg/metrics/views.go
  pkg/parse/namespace.go
  pkg/parse/root.go
  pkg/syncer/metrics/metrics.go
Labels: size/M, lgtm, approved

#122 Reduce the parallel setting of presubmit mono/multi jobs to 15
  Makefile.e2e
Labels: size/XS, lgtm, approved

#120 Add k8s resource attributes to metrics
  cmd/nomos/migrate/migrate.go
  cmd/reconciler-manager/main.go
  e2e/nomostest/config-sync.go
  e2e/testcases/namespace_repo_test.go
  e2e/testdata/reconciler-manager-configmap-updated.yaml
  manifests/otel-agent-cm.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  pkg/api/configsync/register.go
  pkg/applier/kpt_applier.go
  pkg/applier/utils_test.go
  pkg/diff/precedence_test.go
  pkg/kinds/kinds.go
  pkg/kmetrics/register.go
  pkg/metadata/labels.go
  pkg/metrics/register.go
  pkg/metrics/tagkeys.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#126 Add victorpras (victortjhia) to owners
  OWNERS
Labels: size/XS, lgtm, approved

#100 Fix metrics validation
  e2e/nomostest/config-sync.go
  e2e/nomostest/git.go
  e2e/nomostest/metrics/validate.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/testcases/acme_test.go
  e2e/testcases/cluster_resources_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/gatekeeper_test.go
  e2e/testcases/kptfile_test.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/multiversion_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/preserve_fields_test.go
  e2e/testcases/root_sync_test.go
  manifests/templates/otel-collector.yaml
  pkg/metrics/otel.go
  pkg/metrics/tagkeys.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: lgtm, approved, size/XL

#128 add test-resources to OSS manifest
  Makefile.build
Labels: size/XS, lgtm, approved

#129 Re-enable a disabled metrics validation test
  e2e/testcases/custom_resource_definitions_test.go
Labels: lgtm, size/S, approved

#130 Add missing test groups for the multi-repo mode
  Makefile.e2e
Labels: size/XS, lgtm, approved

#131 Use timers instead of tickers
  pkg/configsync/git-importer.go
  pkg/hydrate/controller.go
  pkg/importer/filesystem/controller.go
  pkg/parse/run.go
  pkg/policycontroller/reconciler.go
  pkg/reconciler/reconciler.go
Labels: size/L, lgtm, approved

#133 Avoid unnecessary status updates
  pkg/parse/namespace.go
  pkg/parse/root.go
Labels: size/L, lgtm, approved

#124 add terraform config for dev/ci clusters
  e2e/testinfra/terraform/Makefile
  e2e/testinfra/terraform/README.md
  e2e/testinfra/terraform/common/service_accounts.tf
  e2e/testinfra/terraform/common/source_repositories.tf
  e2e/testinfra/terraform/dev/clusters.tf
  e2e/testinfra/terraform/dev/variables.tf
  e2e/testinfra/terraform/environments.tf
  e2e/testinfra/terraform/main.tf
  e2e/testinfra/terraform/modules/e2ecluster/e2ecluster.tf
  e2e/testinfra/terraform/modules/e2ecluster/variables.tf
  e2e/testinfra/terraform/modules/e2ecluster_autopilot/e2ecluster.tf
  e2e/testinfra/terraform/modules/e2ecluster_autopilot/variables.tf
  e2e/testinfra/terraform/modules/service_account/service_account.tf
  e2e/testinfra/terraform/modules/service_account/variables.tf
  e2e/testinfra/terraform/modules/testgroup/networks.tf
  e2e/testinfra/terraform/modules/testgroup/testgroup.tf
  e2e/testinfra/terraform/modules/testgroup/variables.tf
  e2e/testinfra/terraform/modules/testgroup_autopilot/networks.tf
  e2e/testinfra/terraform/modules/testgroup_autopilot/testgroup.tf
  e2e/testinfra/terraform/modules/testgroup_autopilot/variables.tf
  e2e/testinfra/terraform/prow/networks.tf
  e2e/testinfra/terraform/prow/prow_clusters.tf
  e2e/testinfra/terraform/variables.tf
Labels: size/XXL, lgtm, approved

#136 add registries and enable APIs in terraform
  e2e/testinfra/terraform/common/registries.tf
  e2e/testinfra/terraform/common/services.tf
  e2e/testinfra/terraform/prow/registries.tf
  e2e/testinfra/terraform/prow/services.tf
Labels: size/L, lgtm, approved

#104 Re-enable the resource condition tests for mono-repo mode
  e2e/testcases/resource_conditions_test.go
Labels: lgtm, size/S, approved

#138 add test-resources to OSS manifest (#128)
  Makefile.build
Labels: size/XS, lgtm, approved

#140 Add rquitales to OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#137 Change the RootSync helm.namespace field default value
  e2e/testcases/helm_sync_test.go
  manifests/rootsync-crd.yaml
  pkg/api/configsync/register.go
  pkg/api/configsync/v1alpha1/helmconfig.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/helm/helm.go
Labels: size/M, lgtm, approved

#142 Use kubectl to deploy necessary RBAC in mono repo apiservice_test (#73)
  e2e/testcases/apiservice_test.go
Labels: lgtm, size/S, approved

#146 Update cert-controller from v0.2.0 to v0.5.0
  go.mod
  go.sum
  vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#145 Change the RootSync helm.namespace field default value
  e2e/testcases/helm_sync_test.go
  manifests/rootsync-crd.yaml
  pkg/api/configsync/register.go
  pkg/api/configsync/v1alpha1/helmconfig.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/helm/helm.go
Labels: size/M, lgtm, approved

#143 Update TestHelmNamespaceRepo to make it works in shared test environment (#75)
  e2e/testcases/helm_sync_test.go
Labels: size/XS, lgtm, approved

#147 use BUILD_ID as unique identifier for prow jobs
  Makefile
Labels: size/XS, lgtm, approved

#144 Add e2e tests for Helm support (#93)
  e2e/testcases/helm_sync_test.go
Labels: size/M, lgtm, approved

#141 Make client-side timeout when talking to API Server configurable
  cmd/reconciler/main.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/resource_override.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/configsync/git-importer.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/util.go
Labels: ok-to-test, lgtm, approved, size/XL

#139 Fix pipeline_error_observed description to match
  pkg/metrics/metrics.go
  pkg/metrics/views.go
Labels: lgtm, size/S, approved

#153 Support passing number only values as string directly through helm.va…
  e2e/testcases/helm_sync_test.go
  pkg/helm/helm.go
Labels: lgtm, size/S, approved

#154 Fix InvalidSourceType error message (#76)
  pkg/validate/raw/validate/source_spec_validator.go
Labels: size/XS, lgtm, approved

#151 Only remove manually applied resource in mono repo go test (#79)
  e2e/testcases/apiservice_test.go
Labels: size/XS, lgtm, approved

#152 Fix cherrypick discrepancy in #93 and #144
  e2e/testcases/helm_sync_test.go
Labels: size/XS, lgtm, approved

#158 Revert "Support passing number only values as string directly through helm.va…"
  e2e/testcases/helm_sync_test.go
  pkg/helm/helm.go
Labels: lgtm, size/S, approved

#159 Revert "Support passing number only values as string directly through helm.va…"
  e2e/testcases/helm_sync_test.go
  pkg/helm/helm.go
Labels: lgtm, size/S, approved

#161 Fix cleanup for Gatekeeper tests (#84)
  e2e/nomostest/nt.go
  e2e/testcases/gatekeeper_test.go
  e2e/testcases/resource_conditions_test.go
Labels: size/L, lgtm, approved

#160 Fix the test failure for TestResourceConditionAnnotations (#88)
  e2e/nomostest/nt.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/multiversion_test.go
  e2e/testcases/resource_conditions_test.go
Labels: size/M, lgtm, approved

#162 Fix pipeline_error_observed description to match the description in the resource-group controller. (#139)
  pkg/metrics/metrics.go
  pkg/metrics/views.go
Labels: lgtm, size/S, approved

#165 Make the test infra setup script robust
  Makefile.build
  scripts/set-up-kcc-configs.sh
  scripts/set-up-workload-identity-configs.sh
Labels: size/XS, lgtm, approved

#163 update make targets to support generic registry (#87)
  Makefile
  Makefile.build
  Makefile.e2e
  Makefile.e2e.ci
  Makefile.release
Labels: size/M, lgtm, approved

#164 make retagging functionality generic #99
  Makefile
  Makefile.build
  Makefile.e2e
Labels: size/M, lgtm, approved
