Repository GoogleContainerTools/config-sync, pull requests merged in 2023-07, with the labels that each got.

#718 test: enhancements to reconciler finalizer tests
  e2e/nomostest/reset.go
  e2e/testcases/reconciler_finalizer_test.go
Labels: size/L, lgtm, approved

#719 test: add e2e options for disk size/type
  e2e/flags.go
  e2e/nomostest/clusters/gke.go
Labels: lgtm, size/S, approved

#480 Modify the metrics for CS smokedetector setup
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: lgtm, size/S, approved

#722 test: add namespace yaml to reset error logging
  e2e/nomostest/reset.go
Labels: size/XS, lgtm, approved

#723 chore: bump k8s patch version
  go.mod
  go.sum
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#725 test: fixes for TestManagingReconciler
  e2e/testcases/reconciler_manager_test.go
Labels: size/M, lgtm, approved

#728 Remove unneeded TestHydrateHelmComponents
  e2e/testcases/hydration_test.go
Labels: size/XS, lgtm, approved

#721 chore: bump resource-group/otel-collector
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/third_party/resourcegroup-manifest.yaml
Labels: lgtm, size/S, approved

#730 test: add support for creating kcc clusters
  e2e/flags.go
  e2e/nomostest/clusters/gke.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/test_type.go
  e2e/testcases/kcc_test.go
  scripts/set-up-kcc-configs.sh
Labels: size/M, lgtm, approved

#732 Remove deleteKubevirt
  e2e/nomostest/clean.go
  e2e/nomostest/kubevirt/v1/kubevirt.go
Labels: size/L, lgtm, approved

#731 test: set GKE cidr range when creating clusters
  e2e/nomostest/clusters/gke.go
Labels: size/XS, lgtm, approved

#733 docs: add dev docs for e2e cluster creation/deletion
  docs/development.md
Labels: lgtm, size/S, approved

#717 helm fix: volume names will use the valuesFileRef index rather than ConfigMap name
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
Labels: lgtm, size/S, approved

#727 rename helm.spec.valuesFileSources to spec.helm.valuesFileRefs
  cmd/helm-sync/main.go
  e2e/testcases/helm_sync_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/helm/helm.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/util.go
  pkg/reconcilermanager/controllers/util_test.go
  pkg/validate/raw/validate/source_spec_validator.go
Labels: size/L, lgtm, approved

#656 Remove the kubevirt e2e test (#643)
  e2e/nomostest/clean.go
  e2e/testcases/apply_scoped_resource_test.go
Labels: size/L, lgtm, approved

#734 test: set oauth scopes for gcenode e2e clusters
  e2e/nomostest/clusters/gke.go
Labels: lgtm, size/S, approved

#736 chore: bump helm version to v3.12.2
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#737 [cherry-pick] chore: bump helm version to v3.12.2 (#736)
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#739 Patch the OS-level packages and remove unneeded dependencies
  test/docker/http-git-server/Dockerfile
Labels: size/XS, lgtm, approved

#743 revert package upgrade and bump base image of http-git-server
  test/docker/http-git-server/Dockerfile
Labels: size/XS, lgtm, approved, tide/merge-method-rebase

#744 chore: bump http-git-server image used by tests
  e2e/nomostest/git-server.go
Labels: size/XS, lgtm, approved

#747 Avoid creating LoadBalancer in wordpress Helm chart
  e2e/testcases/helm_sync_test.go
Labels: size/XS, lgtm, approved

#745 ci: skip cleanup of ConfigConnector resource
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved

#735 helm: configmaps should be immutable
  e2e/testcases/helm_sync_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/validate/raw/validate/source_spec_validator.go
Labels: lgtm, approved, size/XL

#750 test: update default GKE shape
  e2e/flags.go
Labels: lgtm, size/S, approved

#751 ci: remove unused make targets
  Makefile.e2e
  Makefile.e2e.ci
  Makefile.oss.prow
  scripts/set-up-kcc-configs.sh
Labels: size/L, lgtm, approved

#753 Use a patch go version
  build/all/Dockerfile
  build/prow/vulnerability-scanner/Dockerfile
Labels: size/XS, lgtm, approved

#755 Bump askpass image
  pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
Labels: size/XS, lgtm, approved

#757 Update resource group manifest
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#758 Update resource group manifest (#757)
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#760 ci: remove unused Dockerfile
  build/test-e2e-go/gke/Dockerfile
Labels: size/M, lgtm, approved

#756 Bump askpass image (#755)
  pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
Labels: size/XS, lgtm, approved

#754 Update git-sync to address one vulnerability
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#761 Update git-sync to address one vulnerability (#754)
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#752 helm api: better handling of copying referenced configmaps to c-m-s (and other cleanup)
  e2e/testcases/helm_sync_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/validate/raw/validate/source_spec_validator.go
Labels: size/L, lgtm, approved, tide/merge-method-squash

#764 Update the vulnerabitility scan script to check all fixable CVEs
  scripts/vulnerabilities.sh
Labels: size/XS, lgtm, approved

#765 chore: regenerate conversion code
  Makefile.gen
  pkg/api/configsync/v1alpha1/conversion.go
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
Labels: size/M, lgtm, approved

#767 Remove legacy reconciler template test artifact
  e2e/nomostest/config_sync.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testdata/reconciler-manager-configmap-updated.yaml
  pkg/reconcilermanager/controllers/parse.go
Labels: lgtm, approved, size/XL

#770 Update k8s to v1.26.7 & docker to v23.0.6
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1alpha1/generated.proto
  vendor/k8s.io/api/resource/v1alpha1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/openapi/client.go
  vendor/k8s.io/client-go/openapi/groupversion.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/rest/with_retry.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/k8s.io/component-base/metrics/legacyregistry/registry.go
  vendor/k8s.io/component-base/metrics/metric.go
  vendor/k8s.io/component-base/metrics/registry.go
  vendor/k8s.io/kubectl/pkg/cmd/delete/delete.go
  vendor/k8s.io/kubectl/pkg/cmd/testing/fake.go
  vendor/k8s.io/kubectl/pkg/describe/describe.go
  vendor/k8s.io/kubectl/pkg/scheme/install.go
  vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#763 Add configsync_sync_generation metric resource tag
  e2e/nomostest/prometheus_metrics.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/remediator_test.go
  e2e/testcases/root_sync_test.go
  manifests/otel-agent-cm.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  pkg/metadata/labels.go
  pkg/metrics/otel.go
  pkg/metrics/tagkeys.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/util.go
Labels: lgtm, approved, size/XL

#771 Remove IAMServiceAccountKey from KCC source repo
  e2e/testdata/configsync-kcc/kcc/pubsub-key.yaml
Labels: lgtm, size/S, approved

#677 Make log level configurable in r*sync API
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  pkg/api/configsync/v1alpha1/conversion.go
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
  pkg/api/configsync/v1beta1/resource_override.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#769 fix: reconciler fail/timeout as error for destroy
  e2e/nomostest/new.go
  pkg/applier/applier.go
  pkg/applier/applier_err.go
  pkg/applier/applier_test.go
Labels: size/L, lgtm, approved

#772 test: increase timeout for stress tests
  e2e/nomostest/new.go
  e2e/testcases/stress_test.go
Labels: size/XS, lgtm, approved

#774 test: add finalizer reconcile timeout e2e test
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/testutils/validate.go
  e2e/testcases/reconciler_finalizer_test.go
Labels: size/L, lgtm, approved

#776 test: wait for observedGeneration = generation
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/wait_for_sync.go
Labels: size/M, lgtm, approved

#773 [Terraform] Add e2e-metric-writer-sa to test infra
  e2e/testinfra/terraform/common/service_accounts.tf
  e2e/testinfra/terraform/common/services.tf
Labels: lgtm, size/S, approved

#778 Fix deletion of resources with deleted CRDs
  pkg/reconcilermanager/controllers/errors.go
  pkg/util/watch/delete.go
  pkg/util/watch/until.go
Labels: lgtm, size/S, approved

#779 Update git-sync to v3.6.9
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#777 test: Clean up ReconcileTimeout config
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/multi_repo.go
Labels: size/L, lgtm, approved

#775 test: use HasGenerationAtLeast for autopilot
  e2e/testcases/reconciler_manager_test.go
Labels: size/L, lgtm, approved

#780 Fix reconciler-manager cmd to accept log flags
  cmd/reconciler-manager/main.go
  manifests/templates/reconciler-manager.yaml
Labels: lgtm, size/S, approved

#782 test: fix memory request predicate
  e2e/testcases/reconciler_manager_test.go
Labels: size/XS, lgtm, approved

#781 test: install kind at runtime
  Makefile
  Makefile.build
  Makefile.e2e
  build/prow/kubekins-e2e/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  docs/development.md
  scripts/docker-registry.sh
  scripts/e2e-kind.sh
Labels: size/M, lgtm, approved

#749 ci: update terraform for test-provisioned clusters
  e2e/testinfra/terraform/README.md
  e2e/testinfra/terraform/dev/clusters.tf
  e2e/testinfra/terraform/dev/variables.tf
  e2e/testinfra/terraform/environments.tf
  e2e/testinfra/terraform/modules/e2ecluster/e2ecluster.tf
  e2e/testinfra/terraform/modules/e2ecluster/variables.tf
  e2e/testinfra/terraform/modules/e2ecluster_autopilot/e2ecluster.tf
  e2e/testinfra/terraform/modules/e2ecluster_autopilot/variables.tf
  e2e/testinfra/terraform/modules/testgroup/networks.tf
  e2e/testinfra/terraform/modules/testgroup/testgroup.tf
  e2e/testinfra/terraform/modules/testgroup/variables.tf
  e2e/testinfra/terraform/modules/testgroup_autopilot/networks.tf
  e2e/testinfra/terraform/modules/testgroup_autopilot/testgroup.tf
  e2e/testinfra/terraform/modules/testgroup_autopilot/variables.tf
  e2e/testinfra/terraform/prow/networks.tf
  e2e/testinfra/terraform/prow/prow_clusters.tf
  e2e/testinfra/terraform/variables.tf
Labels: lgtm, approved, size/XL

#785 test: remove test finalizer in cleanup
  e2e/nomostest/clean.go
  e2e/nomostest/testutils/validate.go
  e2e/testcases/reconciler_finalizer_test.go
Labels: size/M, lgtm, approved
