Repository GoogleContainerTools/config-sync, pull requests merged in 2023-04, with the labels that each got.

#509 Update kustomize to v5.0.1 for hydration
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#510 Update helm & kustomize (cont.)
  Makefile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  manifests/patch/kustomization.yaml
  pkg/hydrate/tool_util.go
  pkg/kmetrics/exec_test.go
Labels: size/M, lgtm, approved

#513 Fix vulnerabilities.sh when zero vulns
  scripts/vulnerabilities.sh
Labels: size/XS, lgtm, approved

#514 ci: install gke-auth-plugin in e2e image
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
Labels: size/XS, lgtm, approved

#516 Fix debian container nonroot user
  build/all/Dockerfile
  e2e/nomostest/testshell/shell.go
  e2e/testcases/cli_test.go
Labels: size/M, lgtm, approved

#478 test: keep port forwards open when pod changes
  e2e/nomostest/git.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/portforwarder/port_forwarder.go
  e2e/nomostest/prometheus.go
  e2e/nomostest/prometheus_metrics.go
  e2e/nomostest/testkubeclient/client.go
  e2e/nomostest/testwatcher/watch.go
  e2e/testcases/root_sync_test.go
Labels: lgtm, approved, size/XL

#511 Bitbucket e2e test create repository fix
  e2e/nomostest/gitproviders/bitbucket.go
Labels: lgtm, size/S, approved

#515 Add helm & kustomize licenses into images
  Makefile
  Makefile.build
  build/all/Dockerfile
Labels: size/M, lgtm, approved

#517 Validate helm & kustomize checksums
  build/all/Dockerfile
Labels: lgtm, size/S, approved

#519 Update render-helm-chart function to v0.3.0
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
Labels: lgtm, size/S, approved

#518 test: fix git portforward to support non-local provider
  e2e/nomostest/git.go
Labels: lgtm, size/S, approved

#520 Fix vulnerabilities.sh uniqueness filter
  scripts/vulnerabilities.sh
Labels: size/XS, lgtm, approved

#522 Update docker to v23.0.3
  go.mod
  go.sum
  vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go
  vendor/github.com/docker/docker-credential-helpers/credentials/version.go
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/pkg/homedir/homedir_linux.go
  vendor/github.com/docker/docker/pkg/homedir/homedir_others.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#521 test: refactor git portforwarder under gitprovider
  e2e/nomostest/git.go
  e2e/nomostest/gitproviders/bitbucket.go
  e2e/nomostest/gitproviders/git-provider.go
  e2e/nomostest/gitproviders/gitlab.go
  e2e/nomostest/gitproviders/local.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/portforwarder/port_forwarder.go
Labels: size/L, lgtm, approved

#512 add Notification status CRD and controller logic
  Makefile.reconcilermanager
  cmd/notification/main.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/notification_test.go
  go.mod
  go.sum
  manifests/base/kustomization.yaml
  manifests/notification-crd.yaml
  manifests/ns-reconciler-cluster-role.yaml
  manifests/patch/kustomization.yaml
  pkg/api/configsync/register.go
  pkg/api/configsync/v1alpha1/notification_types.go
  pkg/api/configsync/v1alpha1/register.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/notification_types.go
  pkg/api/configsync/v1beta1/register.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/kinds/kinds.go
  pkg/notifications/notifications.go
  pkg/notifications/notifications_test.go
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/util/notification.go
  vendor/github.com/argoproj/notifications-engine/pkg/controller/controller.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#523 test: init GitProvider before setupTestCase
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved

#525 test: set GitProvider in ReInit
  e2e/nomostest/git.go
Labels: size/XS, lgtm, approved

#526 test: use RemoteRepositories for setPortCallback
  e2e/nomostest/git.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved

#529 Update PortForwarder to watch with no timeout
  e2e/nomostest/portforwarder/port_forwarder.go
  e2e/nomostest/testwatcher/watch.go
Labels: size/M, lgtm, approved

#533 test: fix boolean check for process kill
  e2e/nomostest/portforwarder/port_forwarder.go
Labels: size/XS, lgtm, approved

#531 Fix e2e Watch to distinguish cancel vs timeout
  e2e/nomostest/testwatcher/watch.go
  e2e/testcases/composition_test.go
Labels: size/M, lgtm, approved

#534 Update vulnerabilities script
  scripts/vulnerabilities.sh
Labels: size/M, lgtm, approved

#536 Make `nomos migrate` output message clear when errors occur
  cmd/nomos/migrate/migrate.go
Labels: lgtm, size/S, approved

#540 Update helm to v3.11.3
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
  pkg/hydrate/tool_util_test.go
Labels: lgtm, size/S, approved

#537 Improved caCert validation
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/validate_secret.go
Labels: size/L, lgtm, approved

#543 feat: filter Args from error json in RSync status
  pkg/hydrate/controller.go
  pkg/hydrate/controller_test.go
  pkg/util/log/logging.go
Labels: size/M, lgtm, approved

#530 test: restart PortForwarder if process is killed
  e2e/nomostest/gitproviders/git-provider.go
  e2e/nomostest/gitproviders/local.go
  e2e/nomostest/gitproviders/repository.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/portforwarder/port_forwarder.go
  e2e/nomostest/reset.go
Labels: lgtm, approved, size/XL

#544 test: use RootRepos/NonRootRepos in init
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved

#542 Notification helper functions
  Makefile.e2e
  Makefile.e2e.ci
  cmd/notification/main.go
  e2e/nomostest/notification_config.go
  e2e/nomostest/testing/feature.go
  e2e/testcases/notification_test.go
  pkg/notifications/expressions/strings/strings.go
  pkg/notifications/expressions/strings/strings_test.go
  pkg/notifications/expressions/utils/utils.go
  pkg/notifications/expressions/utils/utils_test.go
Labels: lgtm, approved, size/XL

#547 test: improve logging of gitlab/bitbucket cleanup
  e2e/nomostest/gitproviders/bitbucket.go
  e2e/nomostest/gitproviders/git-provider.go
  e2e/nomostest/gitproviders/gitlab.go
  e2e/nomostest/new.go
Labels: size/M, lgtm, approved

#548 remove notification debug log
  pkg/notifications/expressions/strings/strings.go
Labels: size/XS, lgtm, approved

#554 chore: fix kubevirt file naming
  e2e/testcases/apply_scoped_resource_test.go
  examples/kubevirt-compiled/bookstore1/virtualmachine_testvm.yaml
  examples/kubevirt-compiled/clusterrole_kubevirt-operator.yaml
  examples/kubevirt-compiled/clusterrole_kubevirt.io-operator.yaml
  examples/kubevirt-compiled/clusterrolebinding_kubevirt-operator.yaml
  examples/kubevirt-compiled/customresourcedefinition_kubevirts.kubevirt.io.yaml
  examples/kubevirt-compiled/kubevirt/deployment_virt-operator.yaml
  examples/kubevirt-compiled/kubevirt/kubevirt_kubevirt.yaml
  examples/kubevirt-compiled/kubevirt/role_kubevirt-operator.yaml
  examples/kubevirt-compiled/kubevirt/rolebinding_kubevirt-operator-rolebinding.yaml
  examples/kubevirt-compiled/kubevirt/serviceaccount_kubevirt-operator.yaml
  examples/kubevirt-compiled/namespace_bookstore1.yaml
  examples/kubevirt-compiled/namespace_kubevirt.yaml
  examples/kubevirt-compiled/priorityclass_kubevirt-cluster-critical.yaml
  examples/kubevirt/README.md
  examples/kubevirt/kubevirt-operator.yaml
Labels: size/M, lgtm, approved

#555 fix typo in helm chart version
  e2e/testcases/helm_sync_test.go
Labels: size/XS, lgtm, approved

#539 Add a new reconciler into reconciler-manager
  cmd/reconciler-manager/main.go
  pkg/reconcilermanager/controllers/constants.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
  pkg/reconcilermanager/controllers/otel_sa_controller.go
Labels: size/L, lgtm, approved

#556 Add a new reconciler into reconciler-manager (#539)
  cmd/reconciler-manager/main.go
  pkg/reconcilermanager/controllers/constants.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
  pkg/reconcilermanager/controllers/otel_sa_controller.go
Labels: size/L, lgtm, approved

#557 Increase the timeout to address the flakiness
  e2e/testcases/status_enablement_test.go
Labels: size/XS, lgtm, approved
