Repository GoogleContainerTools/config-sync, pull requests merged in 2023-02, with the labels that each got.

#380 Support overriding the helm-sync container's resource requirements
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/resource_override.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#381 Support overriding the helm-sync container's resource requirements (#380)
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/resource_override.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#384 Add more e2e test logs to help debug setup/cleanup
  e2e/nomostest/clean.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/git.go
  e2e/nomostest/metrics.go
  e2e/nomostest/new.go
  e2e/nomostest/watch.go
Labels: size/M, lgtm, approved

#382 Fix OCI e2e tests to run locally
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  e2e/testcases/oci_sync_test.go
Labels: size/L, lgtm, approved

#383 Add a nomostest field-manager
  e2e/nomostest/config_sync.go
  e2e/nomostest/nt.go
  e2e/nomostest/webhook.go
Labels: size/M, lgtm, approved

#373 Use deletion propagation for e2e test cleanup
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/reset.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/root_sync_test.go
Labels: size/XXL, lgtm, approved

#385 Change the wordpress service type to avoid leaking GCP resources
  e2e/testdata/hydration/compiled-json/helm-components/wordpress/service_my-wordpress.json
  e2e/testdata/hydration/compiled/helm-components/wordpress/service_my-wordpress.yaml
  e2e/testdata/hydration/helm-components-remote-values-kustomization.yaml
  e2e/testdata/hydration/helm-components/kustomization.yaml
  e2e/testdata/hydration/krm-function-helm-components-kustomization.yaml
  e2e/testdata/hydration/krm-function-helm-components-remote-values-kustomization.yaml
  e2e/testdata/root-sync-helm-chart-cr.yaml
Labels: lgtm, size/S, approved

#386 Fix WatchObject to test predicates on initial GET
  e2e/nomostest/watch.go
Labels: size/M, lgtm, approved

#388 Bullseye image update for vulnerability fix
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#389 increase timeout for not found after deletion
  e2e/testcases/namespace_repo_test.go
Labels: size/XS, lgtm, approved

#392 Bullseye image update for vulnerability fix (#388)
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#390 Update git-sync version to fix vulnerabilities
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#393 Update git-sync version to fix vulnerabilities (#390)
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#391 Rewrite WatchObject to use client-go
  e2e/nomostest/client.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/new.go
  e2e/nomostest/watch.go
Labels: size/L, lgtm, approved

#394 Modify Predicates to recieve nil for NotFound
  e2e/nomostest/predicates.go
  e2e/nomostest/watch.go
  e2e/testcases/cluster_selectors_test.go
Labels: size/L, lgtm, approved

#395 Use WatchObject instead of Retry+Validate
  e2e/nomostest/clean.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/crds.go
  e2e/nomostest/git-server.go
  e2e/nomostest/predicates.go
  e2e/nomostest/sync.go
  e2e/nomostest/watch.go
  e2e/nomostest/webhook.go
  e2e/testcases/apiservice_test.go
  e2e/testcases/apply_scoped_resource_test.go
  e2e/testcases/cluster_resources_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/declared_fields_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/multiversion_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/no_ssl_verify_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/preserve_fields_test.go
  e2e/testcases/proxy_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/root_sync_test.go
  e2e/testcases/status_enablement_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/sync_ordering_test.go
  pkg/kinds/kinds.go
Labels: size/XXL, lgtm, approved

#397 Use temporary base image to address vulnerability
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#398 Use temporary base image to address vulnerability (#397)
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#400 Don't allow namespace for cluster-scope watch
  e2e/nomostest/watch.go
  e2e/testcases/apiservice_test.go
Labels: size/XS, lgtm, approved

#402 Add liveness & readiness probes to e2e git-server
  e2e/nomostest/git-server.go
Labels: lgtm, size/S, approved

#399 Add a doc for deletion propagation
  docs/deletion-propagation.md
Labels: size/L, lgtm, approved

#403 use WatchForCurrentStatus for composition_test
  e2e/testcases/composition_test.go
Labels: lgtm, size/S, approved

#404 Fix TestDependencyWithReconciliation
  e2e/nomostest/predicates.go
  e2e/testcases/sync_ordering_test.go
Labels: size/L, lgtm, approved

#405 Fix usages of TaskGroup in a for loop
  e2e/nomostest/crds.go
  e2e/nomostest/reset.go
  e2e/testcases/composition_test.go
  e2e/testcases/namespace_repo_test.go
Labels: size/M, lgtm, approved

#407 Error if port-forward exits prematurely
  e2e/nomostest/nt.go
Labels: size/M, lgtm, approved

#406 Improve clean/reset of namespaces
  e2e/nomostest/clean.go
  e2e/nomostest/reset.go
Labels: size/L, lgtm, approved

#410 Increase wait timeout for reconciler
  e2e/nomostest/config_sync.go
Labels: size/XS, lgtm, approved

#409 E2E Clean enhancements
  e2e/nomostest/clean.go
  e2e/nomostest/client.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/crds.go
  e2e/nomostest/kubevirt/v1/kubevirt.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/testcases/apply_scoped_resource_test.go
  go.mod
  go.sum
  vendor/k8s.io/kube-aggregator/LICENSE
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/helpers.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/doc.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.pb.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/register.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.conversion.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.deepcopy.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/zz_generated.defaults.go
  vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#411 Include command output when metrics curl errors
  e2e/nomostest/metrics/parse.go
Labels: lgtm, size/S, approved

#413 Skip .spec.ports check for ExternalName Service
  pkg/validate/raw/hydrate/declared_field_hydrator.go
  pkg/validate/raw/hydrate/declared_field_hydrator_raw_test.go
Labels: size/M, lgtm, approved

#414 Enable nomos status command in OSS
  cmd/nomos/status/client.go
  e2e/testcases/cli_test.go
Labels: size/M, lgtm, approved

#419 Enable nomos status command in OSS (#414)
  cmd/nomos/status/client.go
  e2e/testcases/cli_test.go
Labels: size/M, lgtm, approved

#422 Skip .spec.ports check for ExternalName Service
  pkg/validate/raw/hydrate/declared_field_hydrator.go
  pkg/validate/raw/hydrate/declared_field_hydrator_raw_test.go
Labels: size/M, lgtm, approved
