Repository GoogleContainerTools/config-sync, pull requests merged in 2023-08, with the labels that each got.

#787 docs: fix typo
  docs/deletion-propagation.md
Labels: size/XS, lgtm, approved

#786 Upgrade kustomize CLI to 5.1.1 for CVE fixes
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#788 fix: Remove otel agent & collector liveness probe
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/third_party/resourcegroup-manifest.yaml
Labels: lgtm, size/S, approved

#791 test: reduce flakiness of reconcile timeout e2e
  e2e/testcases/override_reconcile_timeout_test.go
Labels: size/XS, lgtm, approved

#792 fix: Handle watcher context cancel
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/filteredwatcher_test.go
  pkg/remediator/watch/manager.go
  pkg/status/internal_error.go
Labels: size/L, lgtm, approved

#748 Fix otel-collector logging repeat error
  e2e/testcases/otel_collector_test.go
  e2e/testdata/otel-collector/otel-cm-duplicate-timeseries.yaml
  go.mod
  go.sum
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
  vendor/cloud.google.com/go/monitoring/LICENSE
  vendor/cloud.google.com/go/monitoring/apiv3/v2/alert_policy_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/doc.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/gapic_metadata.json
  vendor/cloud.google.com/go/monitoring/apiv3/v2/group_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/metric_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/alert.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/alert_service.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/common.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/dropped_labels.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/group.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/group_service.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/metric.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/metric_service.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/mutation_record.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/notification.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/notification_service.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/query_service.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/service.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/service_service.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/span_context.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/uptime.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/monitoringpb/uptime_service.pb.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/notification_channel_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/query_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/service_monitoring_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/uptime_check_client.go
  vendor/cloud.google.com/go/monitoring/apiv3/v2/version.go
  vendor/cloud.google.com/go/monitoring/internal/version.go
  vendor/google.golang.org/api/iterator/iterator.go
  vendor/google.golang.org/genproto/googleapis/api/distribution/distribution.pb.go
  vendor/google.golang.org/genproto/googleapis/api/label/label.pb.go
  vendor/google.golang.org/genproto/googleapis/api/metric/metric.pb.go
  vendor/google.golang.org/genproto/googleapis/api/monitoredres/monitored_resource.pb.go
  vendor/google.golang.org/genproto/googleapis/type/calendarperiod/calendar_period.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#795 test: log objects in validateReconcilerResource
  e2e/testcases/multi_sync_test.go
Labels: size/XS, lgtm, approved

#799 test: fix cleanup ordering of kcc resources
  e2e/testdata/configsync-kcc/kcc/policy-member.yaml
Labels: size/XS, lgtm, approved

#790 refactor: move the askpass declaration to manifest
  e2e/testcases/reconciler_manager_test.go
  manifests/templates/reconciler-manager-configmap.yaml
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  scripts/lib/manifests.sh
Labels: size/L, lgtm, approved

#798 chore: bump golang version
  build/all/Dockerfile
  build/prow/vulnerability-scanner/Dockerfile
Labels: size/XS, lgtm, approved

#797 chore: bump git-sync
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#800 chore: bump gcenode-askpass-sidecar
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#801 chore: bump resource-group-controller
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#804 Add a stress test with 100 CRDs
  e2e/testcases/stress_test.go
Labels: size/M, lgtm, approved

#806 fetch helm from patched GKE version
  Makefile
  Makefile.build
  Makefile.oss.prow
  build/all/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: size/M, lgtm, approved

#810 chore: bump debian base image
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#809 fetch kustomize from patched GKE version
  Makefile
  Makefile.build
  Makefile.oss.prow
  Makefile.reconcilermanager
  build/all/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: size/M, lgtm, approved

#813 fix: nil pointer in upsertHelmConfigMap
  e2e/testcases/helm_sync_test.go
  pkg/core/decorate.go
  pkg/reconcilermanager/controllers/helm_value_files.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/secret.go
Labels: size/L, lgtm, approved

#805 helm: use spec.helm.period to configure repulling charts
  cmd/helm-sync/main.go
  cmd/reconciler-manager/main.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/testcases/helm_sync_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1beta1/getters.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/helm/helm.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/util.go
  pkg/reconcilermanager/controllers/util_test.go
Labels: size/L, lgtm, approved

#815 test: Log object YAML on validate failure
  e2e/nomostest/testwatcher/watch.go
  e2e/nomostest/validate.go
Labels: size/M, lgtm, approved

#802 Skip validating R*Sync if it has a deletion timestamp
  e2e/testcases/reconciler_manager_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
Labels: lgtm, approved, size/XL

#817 fix: Remove 'type' label from all metrics
  e2e/nomostest/metrics/expectations.go
  e2e/nomostest/metrics/validate.go
  e2e/nomostest/prometheus_metrics.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/namespaces_test.go
  pkg/applier/applier.go
  pkg/metrics/record.go
  pkg/metrics/tagkeys.go
  pkg/metrics/views.go
  pkg/remediator/reconcile/reconciler.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/syncer/client/client.go
  pkg/syncer/metrics/metrics.go
  pkg/syncer/reconcile/apply.go
Labels: size/L, lgtm, approved

#818 helm: add new fields to v1alpha1
  clientgen/apis/clientset.go
  clientgen/apis/fake/clientset_generated.go
  clientgen/apis/fake/register.go
  clientgen/apis/scheme/register.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/helmconfig.go
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
Labels: size/L, lgtm, approved

#811 Add log level override API to v1alpha1
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/conversion.go
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
Labels: size/L, lgtm, approved

#819 Modify the otel_collector_test error condition
  e2e/testcases/otel_collector_test.go
  e2e/testdata/otel-collector/otel-cm-monarch-rejected-labels.yaml
Labels: lgtm, size/S, approved

#823 cherry-pick: use spec.helm.period to configure repulling charts
  cmd/helm-sync/main.go
  cmd/reconciler-manager/main.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/testcases/helm_sync_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1beta1/getters.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/helm/helm.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/util.go
  pkg/reconcilermanager/controllers/util_test.go
Labels: size/L, lgtm, approved

#816 outputting a proper extension for bugreport files
  build/test-e2e-go/kind/Dockerfile
  e2e/testcases/cli_test.go
  pkg/bugreport/bugreport.go
  pkg/bugreport/logsources.go
  pkg/bugreport/logsources_test.go
Labels: size/M, lgtm, approved, tide/merge-method-squash

#814 Set default resource requests for askpass container
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#824 cherry-pick: Add new helm fields to v1alpha1
  clientgen/apis/clientset.go
  clientgen/apis/fake/clientset_generated.go
  clientgen/apis/fake/register.go
  clientgen/apis/scheme/register.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/helmconfig.go
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
Labels: size/L, lgtm, approved

#828 Cherry-pick: fix: Remove 'type' label from all metrics (#817)
  e2e/nomostest/metrics/expectations.go
  e2e/nomostest/metrics/validate.go
  e2e/nomostest/prometheus_metrics.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/namespaces_test.go
  pkg/applier/applier.go
  pkg/metrics/record.go
  pkg/metrics/tagkeys.go
  pkg/metrics/views.go
  pkg/remediator/reconcile/reconciler.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/syncer/client/client.go
  pkg/syncer/metrics/metrics.go
  pkg/syncer/reconcile/apply.go
Labels: size/L, lgtm, approved

#830 test: reduce flakiness of reconcile timeout e2e (#791)
  e2e/testcases/override_reconcile_timeout_test.go
Labels: size/XS, lgtm, approved

#832 test: fix cleanup ordering of kcc resources (#799)
  e2e/testdata/configsync-kcc/kcc/policy-member.yaml
Labels: size/XS, lgtm, approved

#834 chore: bump git-sync (#797)
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#833 chore: bump golang version (#798)
  build/all/Dockerfile
  build/prow/vulnerability-scanner/Dockerfile
Labels: size/XS, lgtm, approved

#827 test: Wait for Current + Synced
  e2e/nomostest/wait_for_sync.go
Labels: size/XS, lgtm, approved

#837 refactor: move the askpass declaration to manifest (#790)
  e2e/testcases/reconciler_manager_test.go
  manifests/templates/reconciler-manager-configmap.yaml
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  scripts/lib/manifests.sh
Labels: size/L, lgtm, approved

#831 test: log objects in validateReconcilerResource (#795)
  e2e/testcases/multi_sync_test.go
Labels: size/XS, lgtm, approved

#838 chore: bump resource-group-controller (#801)
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#835 Reduce askpass container default memory
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#836 Improve the retry behavior (#812)
  pkg/parse/cache.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/state.go
Labels: size/L, lgtm, approved

#840 chore: bump debian base image (#810)
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#839 fetch helm from patched GKE version (#806)
  Makefile
  Makefile.build
  Makefile.oss.prow
  build/all/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: size/M, lgtm, approved

#842 Set default resource requests for askpass container
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved, tide/merge-method-rebase

#825 Aggregate commit label for GCM metrics
  e2e/testcases/otel_collector_test.go
  go.mod
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: size/L, lgtm, approved

#844 Revert "Set default resource requests for askpass container"
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#847 Cherrypick: fix: Handle watcher context cancel (#792)
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/filteredwatcher_test.go
  pkg/remediator/watch/manager.go
  pkg/status/internal_error.go
Labels: size/L, lgtm, approved, tide/merge-method-rebase

#849 [vulnerability] Bump resource group controller to v1.0.16
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#850 [vulnerability] Bump resource group controller to v1.0.16 (#849)
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved, tide/merge-method-rebase

#848 fix: race condition in scheme
  pkg/syncer/decode/decode.go
  pkg/syncer/scheme/main_test.go
  pkg/syncer/scheme/scheme.go
  pkg/syncer/scheme/scheme_test.go
  pkg/webhook/configuration/update.go
Labels: size/L, lgtm, approved

#845 Change label aggregation in Moanrch to MAX
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: size/M, lgtm, approved

#851 Change label aggregation in Moanrch to MAX (#845)
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: size/M, lgtm, approved
