Repository GoogleContainerTools/config-sync, pull requests merged in 2023-11, with the labels that each got.

#986 fix: nomos bugreport to prefer the kubectl config
  cmd/nomos/bugreport/bugreport.go
  cmd/nomos/parse/parse.go
  cmd/nomos/status/client.go
  e2e/testcases/cli_test.go
  pkg/bugreport/bugreport.go
  pkg/client/restconfig/restconfig.go
  pkg/hydrate/tool_util.go
Labels: size/L, lgtm, approved

#987 Set default log level value and configure at runtime
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_container_log_level.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#990 docs: add design doc for RSync roleRefs
  docs/design-docs/02-custom-root-reconciler-clusterrole.md
Labels: size/L, lgtm, approved

#989 fix: map RepoSync RoleBinding to RepoSync namespace
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
Labels: size/M, lgtm, approved

#988 fix: use GroupName for RootSyncPermissionPrefix
  pkg/core/names.go
Labels: size/XS, lgtm, approved

#993 Fixes the bitbucket API failures
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/XS, lgtm, approved

#994 Skip helm/kustomize install when version matches
  Makefile
  Makefile.build
  Makefile.e2e
  Makefile.oss.prow
  Makefile.reconcilermanager
  scripts/install-helm.sh
  scripts/install-kustomize.sh
Labels: size/L, lgtm, approved

#978 Add container args validation and e2e test for log verbosity override
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/override_log_level_test.go
Labels: size/L, lgtm, approved

#992 consolidate apt-get calls to a single layer
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#995 copy only needed files to docker context
  .dockerignore
  build/prow/e2e/Dockerfile.dockerignore
Labels: lgtm, size/S, approved

#1000 docs: update RSync RBAC design doc for RootSync
  docs/design-docs/02-custom-root-reconciler-clusterrole.md
Labels: size/L, lgtm, approved

#999 docs: move testing to its own doc page
  docs/development.md
  docs/installation.md
  docs/testing.md
Labels: size/L, lgtm, approved

#1004 chore: update resource group controller manifest
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1005 Update the generated deepcopy code for ClusterRoleOverride
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
Labels: lgtm, size/S, approved

#998 test: migrate ResourceGroup e2e tests to this repo
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/testresourcegroup/resourcegroup.go
  e2e/testcases/kcc_test.go
  e2e/testcases/resource_group_controller_test.go
  e2e/testcases/stress_test.go
Labels: lgtm, approved, size/XL

#1006 test: use a new bitbucket workspace for CI test
  e2e/nomostest/gitproviders/bitbucket.go
Labels: lgtm, size/S, approved

#1009 test: fix name pattern of kcc and stress test
  e2e/testcases/kcc_test.go
  e2e/testcases/stress_test.go
Labels: size/XS, lgtm, approved

#1011 use go install for golangci-lint
  scripts/lint-go.sh
Labels: size/XS, lgtm, approved

#1008 bump resourcegroup to latest main
  e2e/nomostest/testresourcegroup/resourcegroup.go
  go.mod
  go.sum
  vendor/kpt.dev/resourcegroup/controllers/handler/event_handler.go
  vendor/kpt.dev/resourcegroup/controllers/metrics/record.go
  vendor/kpt.dev/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
  vendor/kpt.dev/resourcegroup/controllers/root/root_controller.go
  vendor/kpt.dev/resourcegroup/controllers/status/status.go
  vendor/kpt.dev/resourcegroup/controllers/typeresolver/fakeresolver.go
  vendor/kpt.dev/resourcegroup/controllers/typeresolver/typeresolver.go
  vendor/kpt.dev/resourcegroup/controllers/watch/manager.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#1007 Sync from the branch if git.rev is empty or HEAD
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/gitconfig.go
  pkg/api/configsync/v1beta1/gitconfig.go
  pkg/reconcilermanager/controllers/gitsync_env.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/M, lgtm, approved

#1016 Remove unused function and associated unit test
  pkg/hydrate/flatten.go
  pkg/hydrate/flatten_test.go
Labels: size/L, lgtm, approved

#1017 Remove a redefined constant
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/no_ssl_verify_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/root_sync_test.go
  pkg/api/configmanagement/v1/constants.go
  pkg/parse/source.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret_test.go
Labels: size/L, lgtm, approved

#1018 test: wait for test dependencies asyncronously
  e2e/nomostest/config-connector.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: size/L, lgtm, approved

#997 ci: remove in-repo artifacts from gke-e2e image
  Makefile.build
  Makefile.e2e
  build/prow/e2e/Dockerfile
  scripts/build-junitreport-cli.sh
  scripts/e2e.sh
Labels: size/M, lgtm, approved

#1020 test: Deploy git-server async in e2e test setup
  e2e/nomostest/config_sync.go
  e2e/nomostest/git-server.go
  e2e/nomostest/new.go
  e2e/nomostest/ssh.go
  e2e/testcases/composition_test.go
Labels: size/L, lgtm, approved

#1012 Optimize git/oci/helm container resources
  pkg/reconcilermanager/controllers/reconciler_container_resources.go
Labels: lgtm, size/S, approved

#1013 Add the scope marker to ConfigManagement CRDs
  pkg/api/configmanagement/v1/types.go
Labels: size/XS, lgtm, approved

#1021 fix: add ClusterRoleOverrideSpec to v1alpha
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
Labels: size/M, lgtm, approved

#1025 Add e2e tests for NamespaceSelector
  Makefile.e2e
  e2e/nomostest/testing/feature.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/namespace_selectors_test.go
Labels: size/L, lgtm, approved

#1014 Update the configmanagement v1 CRDs to match the generated manifests
  manifests/cluster-selector-crd.yaml
  manifests/hierarchyconfig-crd.yaml
  manifests/namespace-config-crd.yaml
  manifests/namespace-selector-crd.yaml
Labels: size/L, lgtm, approved

#1026 feat: Add klog flags to nomos cli
  cmd/nomos/bugreport/bugreport.go
  cmd/nomos/nomos.go
Labels: lgtm, size/S, approved

#1028 fix: nomos default kubeconfig path
  cmd/nomos/nomos.go
  pkg/client/restconfig/config.go
  pkg/client/restconfig/restconfig.go
Labels: size/M, lgtm, approved

#1027 Auto-generate manifests for ConfigManagement CRDs
  Makefile.reconcilermanager
  manifests/cluster-selector-crd.yaml
  manifests/hierarchyconfig-crd.yaml
  manifests/namespace-selector-crd.yaml
  manifests/patch/kustomization.yaml
  pkg/api/configmanagement/v1/types.go
  pkg/status/error.go
Labels: size/M, lgtm, approved

#1029 API: add a new field to the NamespaceSelector API
  manifests/namespace-selector-crd.yaml
  pkg/api/configmanagement/v1/types.go
  pkg/api/configmanagement/v1/zz_generated.deepcopy.go
Labels: size/M, lgtm, approved

#991 feat: implement roleRefs API for RootSyncs
  e2e/nomostest/nt.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/override_role_refs_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/root_sync_test.go
  manifests/base/kustomization.yaml
  manifests/ns-reconciler-base-cluster-role.yaml
  manifests/root-reconciler-base-cluster-role.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/resource_override.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/core/meta.go
  pkg/core/names.go
  pkg/reconcilermanager/controllers/build_names.go
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/syncer/syncertest/fake/storage.go
Labels: size/XXL, lgtm, approved

#1032 test: fix go linter install
  Makefile
  scripts/lint-go.sh
Labels: size/M, lgtm, approved

#1022 ci: enable spellchecking linter
  .golangci.yaml
  e2e/nomostest/taskgroup/taskgroup.go
  e2e/nomostest/testwatcher/watch.go
  e2e/testcases/admission_test.go
  e2e/testcases/main_test.go
  e2e/testcases/managed_resources_test.go
  pkg/api/configmanagement/v1/types.go
  pkg/applier/applier.go
  pkg/applier/utils.go
  pkg/diff/diff.go
  pkg/helm/helm.go
  pkg/importer/filesystem/filesystemtest/test_dir.go
  pkg/parse/cache.go
  pkg/reconciler/finalizer/controller.go
  pkg/reconciler/finalizer/reposync_finalizer.go
  pkg/reconciler/finalizer/rootsync_finalizer.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
  pkg/syncer/syncertest/fake/common.go
  pkg/syncer/syncertest/fake/fields.go
  pkg/validate/raw/hydrate/declared_field_hydrator.go
  pkg/validate/raw/validate/illegal_kind_validator.go
  pkg/webhook/auth.go
Labels: size/M, lgtm, approved

#1034 test: fix ConfigConnector watch
  e2e/nomostest/config-connector.go
Labels: size/XS, lgtm, approved

#1024 Add a new Namespace Controller
  cmd/reconciler/main.go
  pkg/parse/run.go
  pkg/reconciler/namespacecontroller/namespace_controller.go
  pkg/reconciler/namespacecontroller/namespace_predicate.go
  pkg/reconciler/namespacecontroller/state.go
  pkg/reconciler/namespacecontroller/state_test.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/constants.go
Labels: size/L, lgtm, approved

#1001 Implement known_host ssh support
  e2e/nomostest/ssh.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/ssh_known_hosts_test.go
  pkg/reconcilermanager/controllers/gitsync_env.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#1039 refactor: update ForEachCluster to avoid using long list of parameters
  cmd/nomos/hydrate/hydrate.go
  cmd/nomos/vet/vet_impl.go
  pkg/hydrate/for_each_cluster.go
Labels: size/M, lgtm, approved

#1038 test: fix test flake for role ref on autopilot
  e2e/testcases/override_role_refs_test.go
Labels: size/XS, lgtm, approved

#1037 refactor: use option structs to replace the long list of function parameters
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/util.go
  pkg/reconcilermanager/controllers/util_test.go
Labels: size/L, lgtm, approved

#1033 test: fix addlicense & controller-gen install
  Makefile
  Makefile.build
  Makefile.reconcilermanager
  manifests/cluster-selector-crd.yaml
  manifests/hierarchyconfig-crd.yaml
  manifests/namespace-selector-crd.yaml
  manifests/reposync-crd.yaml
  manifests/resourcegroup-crd.yaml
  manifests/rootsync-crd.yaml
  scripts/generate-test-loggers.sh
  scripts/license-headers.sh
Labels: size/M, lgtm, approved

#1042 refactor: replace the long list of parameters with options struct
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/source.go
  pkg/parse/source_test.go
  pkg/parse/updater.go
  pkg/reconciler/reconciler.go
Labels: lgtm, approved, size/XL

#1030 Update the reconciler-manager to set the ns-controller-requires flag
  cmd/reconciler/main.go
  pkg/metadata/annotations.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/util.go
Labels: size/L, lgtm, approved

#1044 chore: remove scope from the namespace struct
  pkg/parse/namespace.go
  pkg/reconciler/reconciler.go
Labels: lgtm, size/S, approved

#1045 test: add timing measurements for each e2e feature
  e2e/nomostest/new.go
  e2e/testcases/main_test.go
Labels: size/M, lgtm, approved

#1046 chore: bump otelcontribcol to v0.89.0-gke.1
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1041 fix: clientgen tools install to local output dir
  Makefile.gen
  scripts/generate-clientset.sh
Labels: size/M, lgtm, approved

#1047 ci: rebalance e2e presubmit tests
  Makefile.e2e
Labels: size/XS, lgtm, approved

#1043 fix: get clientgen version from go.mod file
  Makefile.gen
  clientgen/apis/clientset.go
  clientgen/apis/typed/configmanagement/v1/configmanagement_client.go
  clientgen/apis/typed/configmanagement/v1/fake/fake_clusterconfig.go
  clientgen/apis/typed/configmanagement/v1/fake/fake_clusterselector.go
  clientgen/apis/typed/configmanagement/v1/fake/fake_hierarchyconfig.go
  clientgen/apis/typed/configmanagement/v1/fake/fake_namespaceconfig.go
  clientgen/apis/typed/configmanagement/v1/fake/fake_namespaceselector.go
  clientgen/apis/typed/configmanagement/v1/fake/fake_repo.go
  clientgen/apis/typed/configmanagement/v1/fake/fake_sync.go
  clientgen/apis/typed/configsync/v1alpha1/configsync_client.go
  clientgen/apis/typed/configsync/v1beta1/configsync_client.go
  clientgen/apis/typed/hub/v1/hub_client.go
  clientgen/apis/typed/kpt.dev/v1alpha1/kpt.dev_client.go
  clientgen/informer/factory.go
Labels: size/L, lgtm, approved

#1050 chore: Update k8s to 1.26.11
  go.mod
  go.sum
  vendor/golang.org/x/mod/semver/semver.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/google.golang.org/genproto/googleapis/api/LICENSE
  vendor/google.golang.org/genproto/googleapis/api/annotations/client.pb.go
  vendor/google.golang.org/genproto/googleapis/rpc/LICENSE
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/prototext/encode.go
  vendor/google.golang.org/protobuf/internal/encoding/json/encode.go
  vendor/google.golang.org/protobuf/internal/encoding/text/encode.go
  vendor/google.golang.org/protobuf/internal/genid/descriptor_gen.go
  vendor/google.golang.org/protobuf/internal/genid/type_gen.go
  vendor/google.golang.org/protobuf/internal/order/order.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/size.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/source_gen.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#1051 Clarify the revision's default value in the API
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/gitconfig.go
  pkg/api/configsync/v1beta1/gitconfig.go
Labels: size/M, lgtm, approved

#1031 Implement the select mode in the NamespaceSelector API
  cmd/nomos/hydrate/hydrate.go
  cmd/nomos/vet/vet_impl.go
  cmd/nomoserrors/examples/examples.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/webhook.go
  e2e/testcases/namespace_selectors_test.go
  pkg/api/configmanagement/v1/constants.go
  pkg/hydrate/for_each_cluster.go
  pkg/importer/analyzer/transform/selectors/namespace_selectors.go
  pkg/parse/namespace.go
  pkg/parse/repository_scope.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run_test.go
  pkg/parse/source_test.go
  pkg/reconciler/reconciler.go
  pkg/validate/objects/raw.go
  pkg/validate/objects/scoped.go
  pkg/validate/raw/raw.go
  pkg/validate/scoped/hydrate/namespace_hydrator.go
  pkg/validate/scoped/hydrate/namespace_hydrator_test.go
  pkg/validate/scoped/scoped.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: size/XXL, lgtm, approved

#1052 fix: apply managed resource labels consistently
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/secret_test.go
Labels: size/M, lgtm, approved

#1049 fix: setup/teardown keep finalizer on reconcile err
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/reconciler_manager_test.go
  pkg/reconcilermanager/controllers/errors.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
Labels: size/L, lgtm, approved

#1053 Add RepoSync e2e test for log level override
  e2e/testcases/override_log_level_test.go
Labels: size/L, lgtm, approved

#1059 fix: remove a false condition that sets the dynamic mode
  e2e/testcases/namespace_selectors_test.go
  pkg/validate/scoped/hydrate/namespace_hydrator.go
  pkg/validate/scoped/hydrate/namespace_hydrator_test.go
Labels: size/M, lgtm, approved
