Repository GoogleContainerTools/config-sync, pull requests merged in 2023-03, with the labels that each got.

#418 Avoid exposing transient errors to the R*Sync API
  cmd/nomoserrors/examples/examples.go
  pkg/hydrate/controller.go
  pkg/hydrate/error.go
  pkg/importer/git/git.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/source.go
  pkg/parse/state.go
  pkg/status/hydration.go
  pkg/status/multierror.go
  pkg/status/transient_error.go
Labels: size/L, lgtm, approved

#424 Update the debina-base image to fix CVE-2023-0361
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#426 Update the debina-base image to fix CVE-2023-0361 (#424)
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#423 Change e2e test validation to use sync status output
  e2e/testcases/cli_test.go
Labels: size/XS, lgtm, approved

#427 Avoid exposing transient errors to the R*Sync API (#418)
  cmd/nomoserrors/examples/examples.go
  pkg/hydrate/controller.go
  pkg/hydrate/error.go
  pkg/importer/git/git.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/source.go
  pkg/parse/state.go
  pkg/status/hydration.go
  pkg/status/multierror.go
  pkg/status/transient_error.go
Labels: size/L, lgtm, approved

#429 Update the git-sync image to fix 8 vulnerabilities
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#430 Update the git-sync image to fix 8 vulnerabilities (#429)
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#431 Avoid unnecessary source status update
  pkg/parse/state.go
Labels: size/M, lgtm, approved

#433 Increase e2e polling periods
  e2e/nomostest/new.go
Labels: size/XS, lgtm, approved

#434 Print YAML instead of JSON on e2e validation error
  e2e/nomostest/sync.go
Labels: size/M, lgtm, approved

#432 Make TestComposition exit early on failure
  e2e/nomostest/watch.go
  e2e/testcases/composition_test.go
Labels: size/M, lgtm, approved

#435 Add more logs for debugging
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/parse/run.go
  pkg/remediator/reconcile/reconciler.go
Labels: size/M, lgtm, approved

#437 Fix remediator missing events
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/filteredwatcher_test.go
  pkg/remediator/watch/listwatch.go
  pkg/remediator/watch/manager.go
  pkg/remediator/watch/manager_test.go
  pkg/remediator/watch/watcher.go
Labels: size/L, lgtm, approved

#438 Prevent declaring the reconciler's own RSync object in its repo (#367)
  cmd/nomoserrors/examples/examples.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/root_sync_test.go
  pkg/parse/namespace.go
  pkg/parse/root.go
  pkg/validate/objects/raw.go
  pkg/validate/raw/raw.go
  pkg/validate/raw/validate/self_reconcile_validator.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: size/L, lgtm, approved

#440 Fix a misuse of error builder (#439)
  pkg/hydrate/controller.go
Labels: size/XS, lgtm, approved

#442 Minor cleanup of managed resource e2e tests
  e2e/testcases/managed_resources_test.go
Labels: size/M, lgtm, approved

#436 Change nomos version output in standalone OSS to match image version
  cmd/nomos/util/configmanagement.go
  cmd/nomos/version/version.go
  e2e/testcases/cli_test.go
Labels: size/M, lgtm, approved

#444 Change nomos version output in standalone OSS to match image version …
  cmd/nomos/util/configmanagement.go
  cmd/nomos/version/version.go
  e2e/testcases/cli_test.go
Labels: size/M, lgtm, approved

#445 Increase the reconcileTimeout on the Autopilot cluster
  e2e/testcases/apiservice_test.go
Labels: lgtm, size/S, approved

#450 Remove GKE requirement in API service test
  e2e/testcases/apiservice_test.go
Labels: size/XS, lgtm, approved

#448 Increase the reconcileTimeout for the apiservice test (#445)
  e2e/testcases/apiservice_test.go
Labels: lgtm, size/S, approved

#451 Fix race condition (#415)
  pkg/hydrate/controller.go
  pkg/hydrate/controller_test.go
  pkg/parse/run.go
  pkg/parse/source.go
  pkg/parse/source_test.go
Labels: size/L, lgtm, approved

#449 Improve fake.DynamicClient
  pkg/syncer/syncertest/fake/dynamic_client.go
Labels: size/L, lgtm, approved

#447 Fix abandonment
  e2e/nomostest/wait_for_sync.go
  pkg/applier/applier.go
  pkg/applier/applier_test.go
  pkg/applier/clientset.go
  pkg/syncer/syncertest/fake/client.go
Labels: size/L, lgtm, approved

#443 Update OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: size/M, lgtm, approved

#417 Pause the remediator while the Applier is running
  e2e/nomostest/metrics/validate.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/multi_sync_test.go
  pkg/declared/resources.go
  pkg/declared/resources_test.go
  pkg/parse/cache.go
  pkg/parse/root_test.go
  pkg/parse/run.go
  pkg/parse/updater.go
  pkg/remediator/queue/queue.go
  pkg/remediator/queue/queue_test.go
  pkg/remediator/reconcile/worker.go
  pkg/remediator/reconcile/worker_test.go
  pkg/remediator/remediator.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/filteredwatcher_test.go
  pkg/remediator/watch/manager.go
Labels: lgtm, approved, size/XL

#452 Fix e2e status checks
  e2e/nomostest/sync.go
Labels: size/L, lgtm, approved

#453 Fix OCI tests to read latest commit from git
  e2e/nomostest/nt.go
Labels: size/M, lgtm, approved

#420 Watch for sync in e2e tests, instead of polling
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/acme_test.go
  e2e/testcases/admission_test.go
  e2e/testcases/adopt_client_side_applied_test.go
  e2e/testcases/apiservice_test.go
  e2e/testcases/apply_scoped_resource_test.go
  e2e/testcases/basic_test.go
  e2e/testcases/cli_test.go
  e2e/testcases/cluster_resources_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/composition_test.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/custom_resource_definitions_schema_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/declared_fields_test.go
  e2e/testcases/gatekeeper_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/kptfile_test.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/local_config_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/multiversion_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/no_ssl_verify_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/policy_dir_test.go
  e2e/testcases/preserve_fields_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/proxy_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/resource_group_controller_test.go
  e2e/testcases/root_sync_test.go
  e2e/testcases/status_enablement_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/sync_ordering_test.go
Labels: size/XXL, lgtm, approved

#454 Make GetDeploymentPod return an error
  e2e/nomostest/git-server.go
  e2e/nomostest/metrics.go
  e2e/nomostest/nt.go
Labels: size/L, lgtm, approved

#455 Fix e2e Clean to handle async deletions
  e2e/nomostest/clean.go
Labels: size/XS, lgtm, approved

#457 Fix e2e to avoid double setup
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: size/M, lgtm, approved

#458 Revert "Fix e2e to avoid double setup (#457)"
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: size/M, lgtm, approved

#441 test: add notification server test component
  Makefile.build
  e2e/nomostest/new.go
  e2e/nomostest/notification_server.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/new.go
  test/docker/http-notification-webhook/Dockerfile
  test/docker/http-notification-webhook/main.go
Labels: size/L, lgtm, approved

#462 test: fix ls-remote for CSR repos
  e2e/nomostest/nt.go
Labels: size/M, lgtm, approved

#464 fix: flag make targets as phony
  Makefile
Labels: lgtm, size/S, approved

#466 ci: bump kubekins-e2e base image
  Makefile.oss.prow
Labels: size/XS, lgtm, approved

#465 bump Go version to 1.19
  Makefile
  build/all/Dockerfile
  build/buildenv/Dockerfile
  cmd/nomos/initialize/init.go
  cmd/nomos/vet/vet_impl.go
  e2e/doc.go
  e2e/testcases/hydration_test.go
  e2e/testcases/multi_sync_test.go
  go.mod
  pkg/api/configmanagement/v1/doc.go
  pkg/api/configsync/v1alpha1/doc.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/doc.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/api/hub/v1/doc.go
  pkg/hydrate/for_each_cluster.go
  pkg/hydrate/tool_util.go
  pkg/hydrate/tool_util_test.go
  pkg/importer/filesystem/parser.go
  pkg/metrics/record.go
  pkg/parse/cache.go
  pkg/parse/repository_scope.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/syncer/reconcile/fight_detector.go
  pkg/testing/fake/namespace.go
  pkg/util/large_request.go
  pkg/validate/raw/validate/illegal_kind_validator.go
  pkg/vet/api_resources.go
  pkg/webhook/configuration/merge.go
  scripts/lint-go.sh
Labels: size/L, lgtm, approved

#463 feat: add notification configuration API
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/notification_config.go
  pkg/api/configsync/v1alpha1/reposync_types.go
  pkg/api/configsync/v1alpha1/rootsync_types.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/notification_config.go
  pkg/api/configsync/v1beta1/reposync_types.go
  pkg/api/configsync/v1beta1/rootsync_types.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
Labels: size/L, lgtm, approved

#467 use same ignore list for add/lint license headers
  Makefile
  scripts/license-headers.sh
Labels: lgtm, size/S, approved

#460 Log YAML when object expected to be not found
  e2e/nomostest/predicates.go
  e2e/nomostest/watch.go
  e2e/testcases/sync_ordering_test.go
Labels: lgtm, size/S, approved

#459 Don't log kubectl output when cancelled
  e2e/nomostest/nt.go
Labels: size/M, lgtm, approved

#461 De-dupe test setup on shared environments
  e2e/nomostest/config_sync.go
  e2e/nomostest/git-server.go
  e2e/nomostest/git.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: size/L, lgtm, approved

#456 Fix test setup metric validation
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/reset.go
  e2e/testcases/cluster_resources_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/kptfile_test.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/multiversion_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/preserve_fields_test.go
  e2e/testcases/root_sync_test.go
Labels: lgtm, approved, size/XL

#472 test: only update ns if it was changed
  e2e/nomostest/clean.go
Labels: size/XS, lgtm, approved

#473 improve logging of port forward cleanup
  e2e/nomostest/nt.go
Labels: size/XS, lgtm, approved

#474 do not error test if port forward finished
  e2e/nomostest/nt.go
Labels: size/XS, lgtm, approved

#476 Handle the empty value of the Autopilot annotation
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
  pkg/util/autopilot.go
Labels: size/M, lgtm, approved

#477 fix port forward log for format string
  e2e/nomostest/nt.go
Labels: size/XS, lgtm, approved

#481 Update golangci-lint to v1.52.0
  .golangci.yaml
  cmd/nomos/initialize/init.go
  cmd/nomos/status/cluster_state_test.go
  cmd/nomos/vet/vet_impl.go
  e2e/doc.go
  e2e/nomostest/client.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/gitproviders/gitlab.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/gke.go
  e2e/nomostest/predicates.go
  e2e/nomostest/wait.go
  e2e/testcases/main_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespaces_test.go
  pkg/api/configmanagement/v1/doc.go
  pkg/api/configsync/v1alpha1/doc.go
  pkg/api/configsync/v1beta1/doc.go
  pkg/api/hub/v1/doc.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/hydrate/for_each_cluster.go
  pkg/importer/filesystem/parser.go
  pkg/metrics/record.go
  pkg/parse/namespace.go
  pkg/parse/repository_scope.go
  pkg/parse/root.go
  pkg/reconcilermanager/controllers/gitsync_env.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/remediator/reconcile/reconciler.go
  pkg/syncer/reconcile/fight_detector.go
  pkg/syncer/syncertest/fake/applier.go
  pkg/syncer/syncertest/fake/client.go
  pkg/testing/fake/namespace.go
  pkg/util/large_request.go
  pkg/util/log/stringer.go
  pkg/validate/raw/validate/illegal_kind_validator.go
  pkg/vet/api_resources.go
  pkg/webhook/configuration/merge.go
  scripts/lint-go.sh
Labels: size/L, lgtm, approved

#483 Add type & commit metric tags
  pkg/declared/resources.go
  pkg/declared/resources_test.go
  pkg/metrics/otel.go
  pkg/metrics/record.go
  pkg/metrics/views.go
  pkg/parse/updater.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
  pkg/remediator/reconcile/reconciler.go
  pkg/remediator/reconcile/reconciler_test.go
  pkg/remediator/reconcile/worker.go
  pkg/remediator/reconcile/worker_test.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/filteredwatcher_test.go
  pkg/syncer/syncertest/fake/applier.go
Labels: size/L, lgtm, approved

#484 Fix the cleanup for fleet memberships
  e2e/testcases/csr_auth_test.go
Labels: size/M, lgtm, approved

#486 Fix the check for the membership existence message
  e2e/testcases/csr_auth_test.go
Labels: size/XS, lgtm, approved

#487 Fix the cleanup for fleet memberships (#484)
  e2e/testcases/csr_auth_test.go
Labels: size/M, lgtm, approved

#488 Fix the check for the membership existence message (#486)
  e2e/testcases/csr_auth_test.go
Labels: size/XS, lgtm, approved

#489 Remove the unused boolean from the remediator's applier methods
  pkg/remediator/reconcile/reconciler.go
  pkg/syncer/reconcile/apply.go
  pkg/syncer/syncertest/fake/applier.go
Labels: size/M, lgtm, approved

#491 Moves the fight error to the status package
  cmd/nomoserrors/examples/examples.go
  pkg/status/fight_error.go
  pkg/syncer/reconcile/fight_detector.go
Labels: size/M, lgtm, approved

#490 Add a mutex to make the fight detector threadsafe
  pkg/reconciler/reconciler.go
  pkg/syncer/reconcile/apply.go
  pkg/syncer/reconcile/fight/detector.go
  pkg/syncer/reconcile/fight/detector_test.go
  pkg/syncer/reconcile/fight/logger.go
Labels: size/M, lgtm, approved

#492 Replace gknn with core.ID
  pkg/syncer/reconcile/fight/detector.go
  pkg/syncer/reconcile/fight/detector_test.go
  pkg/syncer/reconcile/fight/logger.go
Labels: size/M, lgtm, approved

#494 Move nomostest.Retry to retry package
  e2e/nomostest/docker.go
  e2e/nomostest/nt.go
  e2e/nomostest/predicates.go
  e2e/nomostest/prometheus.go
  e2e/nomostest/prometheus_metrics.go
  e2e/nomostest/retry/retry.go
  e2e/nomostest/validate.go
  e2e/nomostest/wait.go
  e2e/testcases/apply_scoped_resource_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/preserve_fields_test.go
  e2e/testcases/resource_group_controller_test.go
  e2e/testcases/root_sync_test.go
Labels: size/M, lgtm, approved

#495 Extract testlogger, testshell, and testkubeclient
  e2e/nomostest/clean.go
  e2e/nomostest/client.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/docker.go
  e2e/nomostest/git-server.go
  e2e/nomostest/git.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/predicates.go
  e2e/nomostest/prometheus.go
  e2e/nomostest/prometheus_metrics.go
  e2e/nomostest/reset.go
  e2e/nomostest/ssh.go
  e2e/nomostest/testkubeclient/client.go
  e2e/nomostest/testkubeclient/labels.go
  e2e/nomostest/testlogger/testlogger.go
  e2e/nomostest/testshell/shell.go
  e2e/nomostest/validate.go
  e2e/nomostest/wait.go
  e2e/nomostest/wait_for_sync.go
  e2e/nomostest/watch.go
  e2e/nomostest/webhook.go
  e2e/testcases/acme_test.go
  e2e/testcases/admission_test.go
  e2e/testcases/apply_scoped_resource_test.go
  e2e/testcases/basic_test.go
  e2e/testcases/cli_test.go
  e2e/testcases/cluster_resources_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/composition_test.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testcases/preserve_fields_test.go
  e2e/testcases/proxy_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/root_sync_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/sync_ordering_test.go
Labels: size/XXL, lgtm, approved

#493 Surface the fight errors in the R*Sync status field
  e2e/testcases/remediator_test.go
  pkg/parse/root_test.go
  pkg/parse/updater.go
  pkg/remediator/reconcile/reconciler.go
  pkg/remediator/reconcile/reconciler_test.go
  pkg/remediator/reconcile/worker.go
  pkg/remediator/reconcile/worker_test.go
  pkg/remediator/remediator.go
  pkg/syncer/reconcile/apply.go
  pkg/syncer/reconcile/fight/detector.go
  pkg/syncer/reconcile/fight/detector_test.go
  pkg/syncer/reconcile/fight/handler.go
  pkg/syncer/reconcile/fight/logger.go
  pkg/syncer/syncertest/fake/fight_handler.go
Labels: size/L, lgtm, approved

#496 test: refactor watch/predicates into subpackages
  e2e/nomostest/clean.go
  e2e/nomostest/client.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/crds.go
  e2e/nomostest/git-server.go
  e2e/nomostest/git.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/prometheus.go
  e2e/nomostest/reset.go
  e2e/nomostest/sync.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/testutils/validate.go
  e2e/nomostest/testwatcher/watch.go
  e2e/nomostest/validate.go
  e2e/nomostest/wait_for_sync.go
  e2e/nomostest/webhook.go
  e2e/testcases/apiservice_test.go
  e2e/testcases/basic_test.go
  e2e/testcases/cluster_resources_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/composition_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/declared_fields_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/multiversion_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/no_ssl_verify_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/preserve_fields_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/proxy_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/resource_group_controller_test.go
  e2e/testcases/root_sync_test.go
  e2e/testcases/status_enablement_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/sync_ordering_test.go
Labels: size/XXL, lgtm, approved

#499 Refactor the conflict error functions to ConflictHandler
  go.mod
  go.sum
  pkg/parse/root_test.go
  pkg/remediator/conflict/handler.go
  pkg/remediator/remediator.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/filteredwatcher_test.go
  pkg/remediator/watch/manager.go
  pkg/remediator/watch/manager_test.go
  pkg/remediator/watch/watcher.go
  pkg/syncer/reconcile/fight/handler.go
  pkg/syncer/syncertest/fake/conflict_handler.go
  pkg/syncer/syncertest/fake/fight_handler.go
  vendor/github.com/wk8/go-ordered-map/.gitignore
  vendor/github.com/wk8/go-ordered-map/.golangci.yml
  vendor/github.com/wk8/go-ordered-map/LICENSE
  vendor/github.com/wk8/go-ordered-map/Makefile
  vendor/github.com/wk8/go-ordered-map/README.md
  vendor/github.com/wk8/go-ordered-map/orderedmap.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#502 Detect the new autopilot webhook used on GKE 1.26+ (#501)
  pkg/util/autopilot.go
Labels: lgtm, size/S, approved

#500 Pass Kind instead of GVK to the record metrics functions
  pkg/applier/applier.go
  pkg/metrics/record.go
  pkg/remediator/reconcile/reconciler.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/syncer/client/client.go
  pkg/syncer/reconcile/apply.go
Labels: size/M, lgtm, approved

#503 Delete all Kubevirt labeled CRDs
  e2e/nomostest/clean.go
Labels: size/XS, lgtm, approved

#469 Nomos status rsync filter
  cmd/nomos/status/client.go
  cmd/nomos/status/cluster_state.go
  cmd/nomos/status/status.go
  e2e/testcases/cli_test.go
Labels: size/L, lgtm, approved

#504 Add script to report image vulnerabilities
  scripts/vulnerabilities.sh
Labels: size/L, lgtm, approved

#507 Update Go to v1.19
  Makefile
  build/all/Dockerfile
  build/buildenv/Dockerfile
  go.mod
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  scripts/lint-go.sh
Labels: lgtm, size/S, approved

#508 Update helm to v3.11.2 for hydration
  build/all/Dockerfile
Labels: size/XS, lgtm, approved
