Repository GoogleContainerTools/config-sync, pull requests merged in 2023-06, with the labels that each got.

#597 Reduce watch scope for reconciler-manager
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/XXL, lgtm, approved

#637 Fix reconciler-manager missing object updates
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/M, lgtm, approved

#598 Report Stalled condition if reconciler Terminating
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
Labels: size/M, lgtm, approved

#638 Nomos status filter separator fix (#612)
  cmd/nomos/status/cluster_state.go
  cmd/nomos/status/cluster_state_test.go
Labels: size/M, lgtm, approved

#640 Fix reconciler-manager skipping cleanup
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
Labels: size/M, lgtm, approved

#642 Fix flakey DriftProtection tests
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
  pkg/syncer/syncertest/fake/watcher.go
Labels: size/L, lgtm, approved

#616 Restart otel collector when custom logging config map is removed
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: size/M, lgtm, approved

#592 Rewrite sync controller garbage collection
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_sa_controller.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/util.go
Labels: size/L, lgtm, approved

#636 Rewrite the helm-sync tests to push and cleanup their own charts
  e2e/nomostest/helm/helm.go
  e2e/nomostest/testshell/shell.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  go.mod
  go.sum
  vendor/github.com/sergi/go-diff/AUTHORS
  vendor/github.com/sergi/go-diff/CONTRIBUTORS
  vendor/github.com/sergi/go-diff/LICENSE
  vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/diffmatchpatch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/match.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/mathutil.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/operation_string.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/patch.go
  vendor/github.com/sergi/go-diff/diffmatchpatch/stringutil.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kustomize/kyaml/copyutil/copyutil.go
Labels: size/XXL, lgtm, approved, tide/merge-method-squash

#573 helm api: allow user to specify a version range
  e2e/nomostest/helm/helm.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testdata/helm-charts/simple/templates/deployment.yaml
  e2e/testdata/root-sync-helm-chart-version-range-cr.yaml
  pkg/helm/helm.go
  pkg/parse/root.go
Labels: size/L, lgtm, approved

#646 Update base image to fix vulnerability
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#648 Update git-sync image to fix vulnerability
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#645 test: support parallel e2e tests on GKE
  docs/development.md
  e2e/flags.go
  e2e/nomostest/client.go
  e2e/nomostest/clusters/gke.go
  e2e/nomostest/clusters/kind.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/gke.go
  e2e/nomostest/ntopts/new.go
  e2e/testcases/main_test.go
Labels: size/L, lgtm, approved

#643 Remove the kubevirt e2e test
  e2e/nomostest/clean.go
  e2e/testcases/apply_scoped_resource_test.go
Labels: size/L, lgtm, approved

#650 Rewrite reconciler-manager error handling
  pkg/reconcilermanager/controllers/create_or_update.go
  pkg/reconcilermanager/controllers/errors.go
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret.go
Labels: lgtm, approved, size/XL

#652 helm: clear cache after getting chart version
  pkg/helm/helm.go
Labels: lgtm, size/S, approved

#653 test: use WI for helm-sync tests
  e2e/testcases/helm_sync_test.go
Labels: size/M, lgtm, approved

#651 test: refactor e2e clusters to interface
  e2e/nomostest/client.go
  e2e/nomostest/clusters/gke.go
  e2e/nomostest/clusters/kind.go
  e2e/nomostest/helm/helm.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/new.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
Labels: size/L, lgtm, approved

#654 fix: install/use binaries from local build dir
  Makefile
  Makefile.oss.prow
Labels: lgtm, size/S, approved

#658 ci: fix workload identity for reposync
  e2e/testcases/helm_sync_test.go
  e2e/testinfra/terraform/common/service_accounts.tf
  e2e/testinfra/terraform/modules/service_account/service_account.tf
Labels: lgtm, size/S, approved

#662 Bump helm sync resource limits
  e2e/testdata/root-sync-helm-chart-cr.yaml
Labels: size/XS, lgtm, approved

#657 test: enable workload identity for new gke clusters
  e2e/nomostest/clusters/gke.go
Labels: size/XS, lgtm, approved

#659 test: fix usage of flag pointers in tests
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/oci_sync_test.go
Labels: size/L, lgtm, approved

#664 ci: fix permissions for gcenode tests
  e2e/nomostest/clusters/gke.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testinfra/terraform/common/service_accounts.tf
Labels: size/M, lgtm, approved

#665 tweak memory request for some helm sync tests
  e2e/testdata/root-sync-helm-chart-cr.yaml
  e2e/testdata/root-sync-helm-chart-version-range-cr.yaml
Labels: size/XS, lgtm, approved

#498 feat: Add reconciler-manager finalizer
  cmd/reconciler-manager/main.go
  e2e/nomostest/git-server.go
  e2e/nomostest/ssh.go
  e2e/testcases/reconciler_manager_test.go
  pkg/metadata/finalizers.go
  pkg/reconcilermanager/controllers/errors.go
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/syncer/syncertest/fake/storage.go
  pkg/syncer/syncertest/fake/watcher.go
  pkg/util/watch/delete.go
  pkg/util/watch/listerwatcher.go
  pkg/util/watch/listerwatcher_test.go
  pkg/util/watch/until.go
Labels: size/XXL, lgtm, approved

#655 ci: add make targets for parallel gke e2e
  Makefile
  Makefile.e2e
  Makefile.e2e.ci
  Makefile.oss.prow
  build/prow/gke-e2e/Dockerfile
  build/prow/kubekins-e2e/Dockerfile
  build/test-e2e-go/e2e.sh
Labels: size/L, lgtm, approved

#667 ci: observe NUM_CLUSTERS env var for e2e
  e2e/flags.go
Labels: size/XS, lgtm, approved

#668 ci: copy nomos binary into path
  Makefile.build
  Makefile.e2e.ci
Labels: size/XS, lgtm, approved

#671 ci: use share-test-env for kind presubmits
  Makefile.e2e
Labels: size/XS, lgtm, approved

#669 test: add bookstore namespace to sync order tests
  e2e/testcases/sync_ordering_test.go
Labels: size/XS, lgtm, approved

#673 test: stricter namespace cleanup
  e2e/nomostest/reset.go
Labels: lgtm, size/S, approved

#675 ci: hack to enable nomos bugreport in pod
  e2e/testcases/cli_test.go
Labels: size/XS, lgtm, approved

#678 test: add conditional for invalid autopilot flags
  e2e/nomostest/clusters/gke.go
  e2e/testcases/main_test.go
Labels: lgtm, size/S, approved

#674 add retries around helm templating step
  cmd/helm-sync/main.go
  e2e/testdata/root-sync-helm-chart-cr.yaml
  e2e/testdata/root-sync-helm-chart-version-range-cr.yaml
  pkg/helm/helm.go
Labels: lgtm, size/S, approved

#676 Fix watching in TestKCCResourcesOnCSR
  e2e/nomostest/testwatcher/watch.go
  e2e/testcases/kcc_test.go
  pkg/syncer/syncertest/fake/cache.go
  pkg/syncer/syncertest/fake/informer_factory.go
  pkg/util/watch/dynamic_lister_watcher.go
  pkg/util/watch/options.go
  pkg/util/watch/options_test.go
  pkg/util/watch/typed_informer_factory.go
  pkg/util/watch/typed_lister_watcher.go
  pkg/util/watch/until.go
Labels: lgtm, approved, size/XL

#679 add junit cli to gke-e2e image
  build/prow/gke-e2e/Dockerfile
Labels: lgtm, size/S, approved

#666 fix: positional arg for docker build
  Makefile.oss.prow
Labels: size/XS, lgtm, approved

#672 Increase the default RestConfig timeout to 15s
  cmd/nomos/bugreport/bugreport.go
  cmd/nomos/flags/flags.go
  cmd/nomos/migrate/migrate.go
  cmd/nomos/status/status.go
  cmd/nomos/version/version.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1beta1/getters.go
  pkg/api/configsync/v1beta1/resource_override.go
  pkg/client/restconfig/restconfig.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/M, lgtm, approved

#681 test: retry deletion of gke clusters
  e2e/nomostest/clusters/gke.go
Labels: lgtm, size/S, approved

#682 Fix e2e tests failing on recoverable watch error
  e2e/nomostest/testwatcher/watch.go
Labels: size/L, lgtm, approved

#685 only run `helm show chart` for version range
  cmd/helm-sync/main.go
  e2e/testdata/root-sync-helm-chart-version-range-cr.yaml
  go.mod
  go.sum
  pkg/helm/helm.go
  vendor/github.com/Masterminds/semver/v3/.gitignore
  vendor/github.com/Masterminds/semver/v3/.golangci.yml
  vendor/github.com/Masterminds/semver/v3/CHANGELOG.md
  vendor/github.com/Masterminds/semver/v3/LICENSE.txt
  vendor/github.com/Masterminds/semver/v3/Makefile
  vendor/github.com/Masterminds/semver/v3/README.md
  vendor/github.com/Masterminds/semver/v3/SECURITY.md
  vendor/github.com/Masterminds/semver/v3/collection.go
  vendor/github.com/Masterminds/semver/v3/constraints.go
  vendor/github.com/Masterminds/semver/v3/doc.go
  vendor/github.com/Masterminds/semver/v3/version.go
  vendor/golang.org/x/mod/LICENSE
  vendor/golang.org/x/mod/PATENTS
  vendor/golang.org/x/mod/semver/semver.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#684 test: fix for reconcile timeout test on autopilot
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testdata/low-priority-pause-deployment.yaml
Labels: size/XS, lgtm, approved

#686 Use foreground delete on RootSyncs
  e2e/nomostest/reset.go
  e2e/testcases/reconciler_finalizer_test.go
Labels: size/M, lgtm, approved

#688 chore: bump helm version
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#687 Bundle the resource-group manifest into the Config Sync manifest
  manifests/base/kustomization.yaml
  manifests/oss/kustomization.yaml
Labels: size/XS, lgtm, approved

#690 [cherry-pick] chore: bump helm version (#688)
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#692 chore: bump gcenode-askpass image
  pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
Labels: size/XS, lgtm, approved

#689 test: use new logger for each sharedNT
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/testing/ntb.go
  e2e/nomostest/testlogger/testlogger.go
Labels: size/M, lgtm, approved

#693 [cherry-pick] chore: bump gcenode-askpass image (#692)
  pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
Labels: size/XS, lgtm, approved

#694 test: longer timeout for gke cluster creation
  e2e/nomostest/clusters/gke.go
Labels: lgtm, size/S, approved

#695 test: do not treat ECONNREFUSED as terminal err
  e2e/nomostest/prometheus_metrics.go
Labels: size/XS, lgtm, approved

#699 Bundle the resource-group manifest into the Config Sync manifest
  manifests/base/kustomization.yaml
  manifests/oss/kustomization.yaml
Labels: size/XS, lgtm, approved

#697 test: shift left e2e check images
  e2e/nomostest/docker.go
  e2e/nomostest/new.go
  e2e/testcases/main_test.go
Labels: size/M, lgtm, approved

#698 ci: extend gke operation timeouts
  e2e/nomostest/clusters/gke.go
Labels: lgtm, size/S, approved

#701 chore: bump kustomize to v5.1.0
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/controller_test.go
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#703 test: stricter regex for gke operation filter
  e2e/nomostest/clusters/gke.go
Labels: size/XS, lgtm, approved

#704 chore: bump kustomize to v5.1.0 (#701)
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/controller_test.go
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#705 test: consolidate/extend gke operation timeout
  e2e/nomostest/clusters/gke.go
Labels: lgtm, size/S, approved

#706 remove the render-helm-chart kpt function from ConfigSync
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  e2e/testcases/hydration_test.go
  e2e/testdata/hydration/krm-function-deprecated-GK-kustomization.yaml
  e2e/testdata/hydration/krm-function-helm-components-kustomization.yaml
  e2e/testdata/hydration/krm-function-helm-components-remote-values-kustomization.yaml
  e2e/testdata/hydration/krm-function-helm-overlay-kustomization.yaml
  pkg/kmetrics/fieldcount.go
  pkg/kmetrics/fieldcount_test.go
  pkg/kmetrics/testdata/withhelmcharts/helmchartconfig.yaml
  pkg/kmetrics/testdata/withhelmcharts/kustomization.yaml
Labels: size/L, lgtm, approved

#710 refactor: consolidate rsync helper functions
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#711 [resource-group-controller] update image with vulnerability fix
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#712 test: fix poll override logic in `nomostest`
  cmd/reconciler-manager/main.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
Labels: size/M, lgtm, approved

#707 perf: limit helm-sync polling to every hour when a version range is specified
  cmd/helm-sync/main.go
  cmd/reconciler-manager/main.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/testcases/helm_sync_test.go
  pkg/api/configsync/register.go
  pkg/helm/helm.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/util.go
  pkg/reconcilermanager/controllers/util_test.go
Labels: size/L, lgtm, approved

#713 test: add cluster-names e2e arg
  Makefile.e2e
  docs/development.md
  e2e/flags.go
  e2e/nomostest/client.go
  e2e/nomostest/clusters/gke.go
  e2e/nomostest/clusters/kind.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/new.go
  e2e/testcases/main_test.go
  go.mod
  go.sum
  pkg/util/env.go
  vendor/golang.org/x/exp/LICENSE
  vendor/golang.org/x/exp/PATENTS
  vendor/golang.org/x/exp/constraints/constraints.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#714 test: add cluster-prefix parameter
  e2e/flags.go
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved

#709 fix: check that symlink is unchanged for hydration
  pkg/parse/run.go
  pkg/parse/source.go
  pkg/parse/source_test.go
Labels: size/L, lgtm, approved

#715 test: enhance cleanup logic for destroy-clusters
  e2e/flags.go
  e2e/nomostest/client.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/new.go
  e2e/testcases/main_test.go
Labels: size/L, lgtm, approved

#708 feat: dynamically disable hydration-controller
  cmd/reconciler/main.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/cli_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/reconciler_manager_test.go
  pkg/hydrate/tool_util.go
  pkg/metadata/annotations.go
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/source.go
  pkg/parse/state.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/util.go
  pkg/reconcilermanager/controllers/util_test.go
Labels: lgtm, approved, size/XL
