Repository GoogleContainerTools/config-sync, pull requests merged in 2023-10, with the labels that each got.

#908 Remove PSP from installation guide
  docs/installation.md
Labels: size/XS, lgtm, approved

#909 chore: remove PSP manifests and code paths
  Makefile.build
  e2e/nomostest/config_sync.go
  e2e/nomostest/git-server.go
  e2e/nomostest/nt.go
  e2e/nomostest/reset.go
  manifests/acm-psp.yaml
  manifests/ns-reconciler-cluster-role.yaml
  manifests/operator/kustomization.yaml
  manifests/policy-controller-psp.yaml
  manifests/templates/otel-collector.yaml
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/L, lgtm, approved

#910 fix: TestAutopilotReconcilerAdjustment math
  e2e/testcases/reconciler_manager_test.go
Labels: size/L, lgtm, approved

#872 fix: Increase reconciler resources on autopilot
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/stress_test.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
  pkg/reconcilermanager/controllers/reconciler_container_resources.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/util/autopilot.go
Labels: lgtm, approved, size/XL

#912 revert resource increases
  pkg/reconcilermanager/controllers/reconciler_container_resources.go
Labels: size/XS, lgtm, approved, tide/merge-method-rebase

#913 chore: bump otel image to v0.54.0-gke.2
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#907 Tune retryCap used in unit test to fix flakiness
  pkg/hydrate/controller_test.go
  pkg/parse/run_test.go
  pkg/parse/source_test.go
Labels: lgtm, size/S, approved

#914 test: Fix TestStress100CRDs cleanup
  e2e/nomostest/testshell/shell.go
  e2e/testcases/stress_test.go
Labels: size/M, lgtm, approved

#915 test: Fix the missing KUBECONFIG env variable
  e2e/nomostest/testshell/shell.go
Labels: size/XS, lgtm, approved

#917 Update debian-base image for CVE fixes
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#916 Update otelcontribcol image from 0.54.0 to 0.86.0
  e2e/testcases/otel_collector_test.go
  e2e/testdata/otel-collector/otel-cm-monarch-rejected-labels.yaml
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/third_party/resourcegroup-manifest.yaml
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: size/M, lgtm, approved

#919 Update git-sync version for CVE fixes
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#918 Bump the git-sync version for CVE fixes
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#920 test: tune the retryCap to stabalize the unit test
  pkg/hydrate/controller_test.go
  pkg/parse/run_test.go
  pkg/parse/source_test.go
Labels: lgtm, size/S, approved

#921 Update debian-base image for CVE fixes (#917)
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#922 Update otelcontribcol image from 0.54.0 to 0.86.0 (#916)
  e2e/testcases/otel_collector_test.go
  e2e/testdata/otel-collector/otel-cm-monarch-rejected-labels.yaml
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/third_party/resourcegroup-manifest.yaml
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: lgtm, size/S, approved, tide/merge-method-rebase

#924 test: tune the retryCap to stabalize the unit test (#920)
  pkg/hydrate/controller_test.go
  pkg/parse/run_test.go
  pkg/parse/source_test.go
Labels: lgtm, size/S, approved, tide/merge-method-rebase

#923 Bump otel-agent's memory requests/limits on Autopilot clusters
  pkg/reconcilermanager/controllers/reconciler_container_resources.go
Labels: size/XS, lgtm, approved

#925 fix: remove policy-controller-psp from operator
  manifests/operator/kustomization.yaml
Labels: size/XS, lgtm, approved

#807 ci: use common distro for test images
  Makefile
  Makefile.build
  Makefile.e2e
  Makefile.oss.prow
  build/all/Dockerfile
  build/buildenv/Dockerfile
  build/prow/e2e/Dockerfile
  build/prow/vulnerability-scanner/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  scripts/e2e-kind.sh
  scripts/e2e.sh
Labels: size/L, lgtm, approved

#928 test: Prevent autopilot scale-to-zero
  e2e/nomostest/new.go
  e2e/testdata/autopilot-keepalive/deployment.yaml
  go.mod
Labels: size/M, lgtm, approved

#930 ci: remove upx from CLI build
  Makefile
  build/buildenv/Dockerfile
  scripts/build.sh
Labels: size/XS, lgtm, approved

#931 fix: use k8s yaml parser to unmarshal
  e2e/nomostest/new.go
  go.mod
Labels: size/XS, lgtm, approved

#932 fix: specify registry for auth-docker
  Makefile.build
Labels: size/XS, lgtm, approved

#936 Update resourcegroup to v1.0.19
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#937 Update kpt to v1.0.0-beta.46
  Makefile
  go.mod
  go.sum
  vendor/github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1/types.go
  vendor/github.com/GoogleContainerTools/kpt/pkg/live/inventoryrg.go
  vendor/k8s.io/api/apidiscovery/v2beta1/generated.proto
  vendor/k8s.io/api/apidiscovery/v2beta1/types.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/tools/record/event.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#941 Update git-sync to fix CVEs
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#942 Update otelcontribcol version to address CVEs
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
Labels: size/XS, lgtm, approved

#943 Update resource group version to v1.0.20
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#945 ci: add crane binary to e2e environments
  Makefile
  Makefile.e2e
  Makefile.oss.prow
Labels: lgtm, size/S, approved

#946 Update helm and kustomize versions to fix CVEs
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#948 fix: Ignore empty yaml documents
  pkg/importer/reader/parse_file.go
  pkg/importer/reader/parse_file_test.go
Labels: size/M, lgtm, approved

#950 Override the resource requests for helm-sync to address the flakiness of TestPublicHelm
  e2e/testdata/root-sync-helm-chart-cr.yaml
Labels: size/XS, lgtm, approved

#952 chore: bump git-sync for security fixes
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#947 fix: Don't panic on empty helm charts
  e2e/nomostest/helm/helm.go
  e2e/nomostest/name.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testdata/helm-charts/empty/Chart.yaml
  go.mod
  go.sum
  pkg/helm/helm.go
  vendor/github.com/ettle/strcase/.gitignore
  vendor/github.com/ettle/strcase/.golangci.yml
  vendor/github.com/ettle/strcase/.readme.tmpl
  vendor/github.com/ettle/strcase/LICENSE
  vendor/github.com/ettle/strcase/Makefile
  vendor/github.com/ettle/strcase/README.md
  vendor/github.com/ettle/strcase/caser.go
  vendor/github.com/ettle/strcase/convert.go
  vendor/github.com/ettle/strcase/doc.go
  vendor/github.com/ettle/strcase/initialism.go
  vendor/github.com/ettle/strcase/split.go
  vendor/github.com/ettle/strcase/strcase.go
  vendor/github.com/ettle/strcase/unicode.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#953 Update controller-gen to v0.13.0
  Makefile.reconcilermanager
  manifests/patch/kustomization.yaml
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configmanagement/v1/zz_generated.deepcopy.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
Labels: size/M, lgtm, approved

#955 fix: Pass --project flag to gcloud AR calls
  e2e/nomostest/helm/helm.go
Labels: size/XS, lgtm, approved

#954 Update buildenv to v0.3.0
  Makefile
  Makefile.gen
  Makefile.reconcilermanager
  build/buildenv/Dockerfile
Labels: size/M, lgtm, approved

#958 ci: run all of test-presubmit in a single container
  .dockerignore
  Makefile
  build/buildenv/Dockerfile
  scripts/generate-clientset.sh
  scripts/license-headers.sh
  scripts/lint-bash.sh
Labels: size/M, lgtm, approved

#957 ci: publish buildenv in postsubmit
  Makefile
  Makefile.e2e.ci
Labels: lgtm, size/S, approved

#926 test: Add stress tests for OCI and Helm
  e2e/nomostest/artifactregistry/crane.go
  e2e/nomostest/artifactregistry/helm.go
  e2e/nomostest/artifactregistry/image.go
  e2e/nomostest/artifactregistry/yaml.go
  e2e/nomostest/helm/helm.go
  e2e/nomostest/iam/account.go
  e2e/nomostest/workloadidentity/pool.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/otel_collector_test.go
  e2e/testcases/stress_test.go
  e2e/testdata/helm-charts/anvil-set/Chart.yaml
  e2e/testdata/helm-charts/anvil-set/templates/anvil.yaml
  e2e/testdata/helm-charts/anvil-set/templates/crd-anvil.yaml
  e2e/testdata/helm-charts/anvil-set/templates/ns.yaml
  e2e/testdata/helm-charts/anvil-set/values.yaml
Labels: size/XXL, lgtm, approved

#959 refactor: build resource-group image in repo
  Makefile
  Makefile.build
  build/all/Dockerfile
  cmd/resource-group/main.go
  go.mod
  go.sum
  manifests/base/kustomization.yaml
  manifests/templates/resourcegroup-manifest.yaml
  vendor/kpt.dev/resourcegroup/controllers/handler/crd_event_handler.go
  vendor/kpt.dev/resourcegroup/controllers/handler/event_handler.go
  vendor/kpt.dev/resourcegroup/controllers/handler/throttler.go
  vendor/kpt.dev/resourcegroup/controllers/log/setup.go
  vendor/kpt.dev/resourcegroup/controllers/metrics/metrics.go
  vendor/kpt.dev/resourcegroup/controllers/metrics/record.go
  vendor/kpt.dev/resourcegroup/controllers/metrics/register.go
  vendor/kpt.dev/resourcegroup/controllers/metrics/tagkeys.go
  vendor/kpt.dev/resourcegroup/controllers/metrics/views.go
  vendor/kpt.dev/resourcegroup/controllers/profiler/profile.go
  vendor/kpt.dev/resourcegroup/controllers/resourcegroup/condition.go
  vendor/kpt.dev/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
  vendor/kpt.dev/resourcegroup/controllers/resourcemap/resourcemap.go
  vendor/kpt.dev/resourcegroup/controllers/root/root_controller.go
  vendor/kpt.dev/resourcegroup/controllers/root/util.go
  vendor/kpt.dev/resourcegroup/controllers/runner/run.go
  vendor/kpt.dev/resourcegroup/controllers/status/status.go
  vendor/kpt.dev/resourcegroup/controllers/typeresolver/fakeresolver.go
  vendor/kpt.dev/resourcegroup/controllers/typeresolver/typeresolver.go
  vendor/kpt.dev/resourcegroup/controllers/watch/filteredwatcher.go
  vendor/kpt.dev/resourcegroup/controllers/watch/manager.go
  vendor/kpt.dev/resourcegroup/controllers/watch/watcher.go
  vendor/kpt.dev/resourcegroup/third_party/k8s.io/client-go/LICENSE
  vendor/kpt.dev/resourcegroup/third_party/k8s.io/client-go/tools/cache/reflector.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#960 ci: check analysis status in vuln scan script
  scripts/vulnerabilities.sh
Labels: size/M, lgtm, approved

#938 Custom ClusterRole for RootSync reconcilers
  docs/design-docs/01-explicit-only-namespace-strategy.md
  docs/design-docs/02-custom-root-reconciler-clusterrole.md
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/root_sync_test.go
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1beta1/resource_override.go
  pkg/core/names.go
  pkg/reconcilermanager/controllers/build_names.go
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: ok-to-test, lgtm, approved, size/XL

#962 chore: bump otelcontribcol to v0.87.0-gke.1
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#963 [cherry-pick] ci: check analysis status in vuln scan script (#960)
  scripts/vulnerabilities.sh
Labels: size/M, lgtm, approved

#964 chore: bump otelcontribcol to v0.87.0-gke.1 (#962)
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#967 chore: bump git-sync to v3.6.9-gke.5
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#970 chore: bump helm to v3.13.1-gke.2
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#971 [cherry-pick] chore: bump helm to v3.13.1-gke.2 (#970)
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#966 TestHelmLatestVersion: Remove helm chart version suffix
  e2e/nomostest/artifactregistry/helm.go
  e2e/nomostest/artifactregistry/image.go
Labels: size/M, lgtm, approved

#972 [vulnerability] Update git-sync version
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#973 fix: handle arguments in the logs
  pkg/client/restconfig/restconfig.go
  pkg/parse/run.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/syncer/reconcile/apply.go
Labels: lgtm, size/S, approved

#980 docs: update nomos cli readme
  cmd/nomos/README.md
Labels: size/XS, lgtm, approved

#976 refactor: remove uses of deprecated io/ioutil package
  cmd/gen-core-scoper/main.go
  cmd/nomos/initialize/init.go
  cmd/nomos/migrate/migrate.go
  cmd/nomos/parse/find_files_test.go
  cmd/nomos/status/status.go
  cmd/nomos/version/version.go
  e2e/nomostest/artifactregistry/yaml.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/docker.go
  e2e/nomostest/gitproviders/repository.go
  e2e/nomostest/new.go
  e2e/nomostest/ssh.go
  e2e/testcases/admission_test.go
  e2e/testcases/cli_test.go
  e2e/testcases/custom_resource_definitions_schema_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/stress_test.go
  pkg/bugreport/bugreport.go
  pkg/hydrate/controller.go
  pkg/hydrate/tool_util.go
  pkg/importer/filesystem/filesystemtest/test_dir.go
  pkg/importer/reader/parse_file.go
  pkg/reconcilermanager/controllers/parse.go
  pkg/testing/openapitest/doc.go
  pkg/util/log/logging.go
  pkg/vet/api_resources.go
Labels: size/L, lgtm, approved

#982 Log config contexts from nomos commands at -v=4
  cmd/nomos/status/client.go
  pkg/client/restconfig/config.go
Labels: size/M, lgtm, approved

#961 Validate all Config Sync controller Namespaces
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/reset.go
  e2e/testcases/otel_collector_test.go
  pkg/api/configmanagement/register.go
  pkg/bugreport/bugreport.go
  pkg/bugreport/constants.go
  pkg/importer/analyzer/validation/nonhierarchical/illegal_namespace_validator.go
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
  pkg/reconcilermanager/controllers/otel_sa_controller.go
  pkg/validate/raw/validate/namespace_validator_test.go
Labels: size/L, lgtm, approved

#984 test: Retry updates in reconciler-manager tests
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
Labels: lgtm, size/S, approved

#983 fix: Stop using the legacy gcp auth plugin
  cmd/reconciler-manager/main.go
  e2e/flags.go
  pkg/client/restconfig/restconfig.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure_stub.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/plugins.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/plugins_providers.go
  vendor/modules.txt
Labels: size/L, lgtm, approved
