Repository GoogleContainerTools/config-sync, pull requests merged in 2023-05, with the labels that each got.

#562 [CHERRYPICK] Increase the timeout to address the flakiness (#557)
  e2e/testcases/status_enablement_test.go
Labels: size/XS, lgtm, approved

#561 test: add wait for resourcegroup status
  e2e/testcases/override_reconcile_timeout_test.go
Labels: size/XS, lgtm, approved

#563 [CHERRYPICK] test: add wait for resourcegroup status (#561)
  e2e/testcases/override_reconcile_timeout_test.go
Labels: size/XS, lgtm, approved

#560 Template and e2e test for created notification
  e2e/nomostest/notification_config.go
  e2e/testcases/notification_test.go
Labels: size/L, lgtm, approved

#565 test: replace metrics timeout with wait timeout
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/prometheus_metrics.go
Labels: lgtm, size/S, approved

#567 [CHERRYPICK] test: replace metrics timeout with wait timeout (#565)
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/prometheus_metrics.go
Labels: lgtm, size/S, approved

#568 Update the test helm chart given that the ingress has been removed
  e2e/testdata/helm-charts/ns-chart/templates/NOTES.txt
Labels: size/XS, lgtm, approved

#569 Increase the test prometheus memory request
  e2e/testdata/prometheus/prometheus.yaml
Labels: size/XS, lgtm, approved

#570 Update base image to fix the vulnerability for CVE-2022-4415
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#571 Increase the test prometheus memory request (#569)
  e2e/testdata/prometheus/prometheus.yaml
Labels: size/XS, lgtm, approved

#572 Update base image to fix the vulnerability for CVE-2022-4415 (#570)
  build/all/Dockerfile
Labels: size/XS, lgtm, approved

#564 Template and e2e test for deleted notification
  e2e/nomostest/notification_config.go
  e2e/testcases/notification_test.go
Labels: size/M, lgtm, approved

#574 Bump the Kustomize CLI version to fix the vulnerabilities
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#576 Bump the Kustomize CLI version to fix the vulnerabilities (#574)
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#577 Update git-sync version for vulnerability fixes
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#578 Update git-sync version for vulnerability fixes (#577)
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#575 Template and e2e test for stalled notification
  e2e/nomostest/notification_config.go
  e2e/testcases/notification_test.go
Labels: size/M, lgtm, approved

#579 Empty Prometheus cache before each test case
  e2e/nomostest/nt.go
  e2e/testdata/prometheus/prometheus.yaml
Labels: size/M, lgtm, approved

#580 Empty Prometheus cache before each test case (#579)
  e2e/nomostest/nt.go
  e2e/testdata/prometheus/prometheus.yaml
Labels: size/M, lgtm, approved

#582 Use Lookup instead of GVKForObject for nicer error
  e2e/nomostest/testpredicates/predicates.go
  pkg/kinds/lookup.go
Labels: lgtm, size/S, approved

#583 Use watch after deleting objects in tests
  e2e/nomostest/clean.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/reset.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/basic_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/root_sync_test.go
Labels: size/L, lgtm, approved

#584 add commit log to release tag script
  Makefile.release
  scripts/tag-release-candidate.sh
Labels: lgtm, size/S, approved

#586 Bump the test prometheus memory request to 1.5Gi (#581)
  e2e/testdata/prometheus/prometheus.yaml
Labels: size/XS, lgtm, approved

#585 Bump the kustomize CLI version to fix a regression
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#588 Bump the kustomize CLI version to fix a regression (#585)
  Makefile
  build/all/Dockerfile
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#587 Fake client enhancements
  pkg/reconciler/finalizer/reposync_finalizer_test.go
  pkg/reconciler/finalizer/rootsync_finalizer_test.go
  pkg/syncer/syncertest/fake/client.go
Labels: size/L, lgtm, approved

#589 Fix TestSwitchFromGitToOci test cleanup
  e2e/testcases/oci_sync_test.go
Labels: size/M, lgtm, approved

#594 Clean up reconciler-manager logging
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/logger.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_sa_controller.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/secret_test.go
Labels: lgtm, approved, size/XL

#599 test: fix test cleanup for TestSwitchFromGitToOci
  e2e/testcases/oci_sync_test.go
Labels: size/M, lgtm, approved

#601 Set Prometheus retention size to limit the memory usage
  e2e/testdata/prometheus/prometheus.yaml
Labels: size/XS, lgtm, approved

#602 Set Prometheus retention size to limit the memory usage (#601)
  e2e/testdata/prometheus/prometheus.yaml
Labels: size/XS, lgtm, approved

#600 chore: cleanup legacy scripts
  e2e/testdata/reconciler-manager/reposync-sample.yaml
  scripts/debug-reconciler.sh
  scripts/multi-repo.sh
Labels: size/L, lgtm, approved

#603 ci: add postsubmit targets
  Makefile
  Makefile.build
  Makefile.e2e.ci
  Makefile.oss
Labels: size/M, lgtm, approved

#604 Drop the k8s client api latency metric to fix the OOMKilled issue
  e2e/testdata/prometheus/prometheus.yaml
Labels: size/XS, lgtm, approved

#606 fix: support auth for artifact registry with push-images
  Makefile.build
Labels: size/XS, lgtm, approved

#608 docs: add dev docs for using postsubmit artifacts
  docs/development.md
Labels: lgtm, size/S, approved

#605 Drop the k8s client api latency metric to fix the OOMKilled issue (#604)
  e2e/testdata/prometheus/prometheus.yaml
Labels: size/XS, lgtm, approved

#609 Add comment for why dropping k8s client api metric
  e2e/testdata/prometheus/prometheus.yaml
Labels: size/XS, lgtm, approved

#612 Nomos status filter separator fix
  cmd/nomos/status/cluster_state.go
  cmd/nomos/status/cluster_state_test.go
Labels: size/M, lgtm, approved

#607 update vulnerability scan script for CI usage
  Makefile.build
  Makefile.e2e.ci
  build/prow/vulnerability-scanner/Dockerfile
  scripts/pull-postsubmit-retry.sh
  scripts/vulnerabilities.sh
Labels: size/L, lgtm, approved

#614 docs: add user-guide for installing notification
  docs/user-guides/notifications/getting-started.md
Labels: lgtm, size/S, approved

#620 fix: move prerequisites to pull-gcs recipe
  Makefile.e2e.ci
Labels: size/XS, lgtm, approved

#619 add build-status script
  Makefile
  docs/development.md
  scripts/build-status.sh
  scripts/lib/manifests.sh
  scripts/vulnerabilities.sh
Labels: size/L, lgtm, approved

#622 Add conversion-gen for configsync.gke.io/v1alpha1
  clientgen/apis/fake/register.go
  clientgen/apis/scheme/register.go
  pkg/api/configsync/v1alpha1/conversion.go
  pkg/api/configsync/v1alpha1/doc.go
  pkg/api/configsync/v1alpha1/register.go
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
  pkg/core/scheme.go
  scripts/generate-clientset.sh
Labels: size/XXL, lgtm, approved

#623 Fix ErrorStatus to be consistently nil when empty
  cmd/nomos/status/cluster_state_test.go
  pkg/reposync/conditions.go
  pkg/reposync/conditions_test.go
  pkg/rootsync/conditions.go
  pkg/rootsync/conditions_test.go
Labels: lgtm, size/S, approved

#617 Add fake.ClientSet & fake.MemoryStorage
  pkg/core/scheme.go
  pkg/kinds/convert.go
  pkg/kinds/strings.go
  pkg/parse/root_test.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/remediator/reconcile/reconciler_test.go
  pkg/syncer/syncertest/fake/client.go
  pkg/syncer/syncertest/fake/client_set.go
  pkg/syncer/syncertest/fake/common.go
  pkg/syncer/syncertest/fake/dynamic_client.go
  pkg/syncer/syncertest/fake/minimize.go
  pkg/syncer/syncertest/fake/minimize_test.go
  pkg/syncer/syncertest/fake/storage.go
  pkg/syncer/syncertest/fake/subresource_storage.go
  pkg/syncer/syncertest/fake/watcher.go
  pkg/util/mutate/mutate_test.go
Labels: size/XXL, lgtm, approved

#625 Fix fake watcher sending on a closed event channel
  pkg/syncer/syncertest/fake/storage.go
  pkg/syncer/syncertest/fake/watcher.go
Labels: size/M, lgtm, approved

#624 Add constant & helper library for list resources
  cmd/nomos/status/client.go
  e2e/nomostest/clean.go
  e2e/testcases/multi_sync_test.go
  pkg/importer/reader/reader.go
  pkg/kinds/convert.go
  pkg/kinds/convert_test.go
  pkg/kinds/lists.go
  pkg/syncer/scheme/scheme.go
  pkg/syncer/syncertest/fake/common.go
  pkg/syncer/syncertest/fake/dynamic_client.go
  pkg/syncer/syncertest/fake/storage.go
Labels: size/L, lgtm, approved

#626 Delete more carefully in e2e cleanup/reset
  e2e/nomostest/clean.go
  e2e/nomostest/crds.go
  e2e/nomostest/prometheus.go
  e2e/nomostest/reset.go
Labels: size/L, lgtm, approved

#628 Fix reconciler-manager upsertSecret
  pkg/reconcilermanager/controllers/secret.go
Labels: size/L, lgtm, approved

#629 Add helper funcs for creating and casting new objs
  e2e/nomostest/config_sync.go
  e2e/nomostest/testwatcher/watch.go
  e2e/testcases/reconciler_finalizer_test.go
  pkg/kinds/cast.go
  pkg/kinds/convert.go
  pkg/kinds/convert_test.go
  pkg/kinds/lists.go
  pkg/kinds/new.go
  pkg/reconciler/finalizer/rootsync_finalizer_test.go
  pkg/remediator/queue/queue.go
  pkg/remediator/watch/listwatch.go
  pkg/syncer/syncertest/fake/common.go
  pkg/syncer/syncertest/fake/storage.go
  pkg/webhook/validate.go
Labels: size/L, lgtm, approved

#630 Use gcenode v1.0.1 in config sync to fix CVE
  pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
Labels: size/XS, lgtm, approved

#631 Fix reconciler-manager to handle async deletion
  pkg/reconcilermanager/controllers/garbage_collector.go
Labels: size/XS, lgtm, approved

#632 Use gcenode v1.0.1 in config sync to fix CVE (#630)
  pkg/reconcilermanager/controllers/gcenode_askpass_sidecar.go
Labels: size/XS, lgtm, approved

#627 move images to test infra registry
  Makefile
  Makefile.build
  Makefile.oss.prow
  e2e/nomostest/git-server.go
  e2e/nomostest/testing/env.go
  e2e/testcases/oci_sync_test.go
  e2e/testdata/proxy/tinyproxy.yaml
  e2e/testinfra/README.md
  scripts/publish-test-oci-images.sh
Labels: size/L, lgtm, approved

#633 Configure test logging for klog
  Makefile
  cmd/junit-report/resetfailure/main_test.go
  cmd/nomos/initialize/main_test.go
  cmd/nomos/parse/main_test.go
  cmd/nomos/status/main_test.go
  cmd/nomos/version/main_test.go
  cmd/nomos/vet/main_test.go
  pkg/applier/main_test.go
  pkg/applier/stats/main_test.go
  pkg/bugreport/main_test.go
  pkg/core/main_test.go
  pkg/declared/main_test.go
  pkg/diff/main_test.go
  pkg/hydrate/main_test.go
  pkg/importer/customresources/main_test.go
  pkg/importer/filesystem/main_test.go
  pkg/importer/reader/main_test.go
  pkg/kinds/main_test.go
  pkg/kmetrics/main_test.go
  pkg/metadata/main_test.go
  pkg/parse/main_test.go
  pkg/reconciler/finalizer/main_test.go
  pkg/reconcilermanager/controllers/main_test.go
  pkg/remediator/queue/main_test.go
  pkg/remediator/reconcile/main_test.go
  pkg/remediator/watch/main_test.go
  pkg/reposync/main_test.go
  pkg/rootsync/main_test.go
  pkg/status/main_test.go
  pkg/syncer/client/main_test.go
  pkg/syncer/decode/main_test.go
  pkg/syncer/differ/main_test.go
  pkg/syncer/reconcile/fight/main_test.go
  pkg/syncer/reconcile/main_test.go
  pkg/syncer/scheme/main_test.go
  pkg/syncer/syncertest/fake/main_test.go
  pkg/util/clusterconfig/main_test.go
  pkg/util/compare/main_test.go
  pkg/util/discovery/main_test.go
  pkg/util/log/main_test.go
  pkg/util/mutate/main_test.go
  pkg/validate/final/validate/main_test.go
  pkg/validate/main_test.go
  pkg/validate/objects/main_test.go
  pkg/validate/raw/hydrate/main_test.go
  pkg/validate/raw/validate/main_test.go
  pkg/validate/scoped/hydrate/main_test.go
  pkg/validate/scoped/validate/main_test.go
  pkg/validate/tree/hydrate/main_test.go
  pkg/validate/tree/validate/main_test.go
  pkg/vet/main_test.go
  pkg/webhook/configuration/main_test.go
  pkg/webhook/main_test.go
  scripts/generate-test-loggers.sh
Labels: size/XXL, lgtm, approved

#635 Add DeleteObjectListItemsAndWait e2e func
  e2e/nomostest/clean.go
  pkg/kinds/lists.go
Labels: size/M, lgtm, approved

#634 Add rsync manager lifecycle tests
  pkg/core/names.go
  pkg/reconcilermanager/controllers/controller.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/syncer/syncertest/fake/cache.go
  pkg/syncer/syncertest/fake/informer_factory.go
  vendor/github.com/go-logr/logr/funcr/funcr.go
  vendor/github.com/go-logr/logr/testr/testr.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved
