Repository GoogleContainerTools/config-sync, pull requests merged in 2023-12, with the labels that each got.

#1057 fix: Delay RSync controller registration
  cmd/reconciler-manager/main.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/reconciler_manager_test.go
  go.mod
  go.sum
  pkg/api/configsync/register.go
  pkg/reconcilermanager/controllers/controller.go
  pkg/reconcilermanager/controllers/crd_controller.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_sa_controller.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
  vendor/golang.org/x/exp/slices/cmp.go
  vendor/golang.org/x/exp/slices/slices.go
  vendor/golang.org/x/exp/slices/sort.go
  vendor/golang.org/x/exp/slices/zsortanyfunc.go
  vendor/golang.org/x/exp/slices/zsortordered.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#1065 chore: bump git-sync for security fixes
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#1066 fix: Prevent RSync from premature Current status
  manifests/reposync-crd.yaml
  manifests/resourcegroup-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/sync_types.go
  pkg/api/configsync/v1beta1/sync_types.go
  pkg/api/kpt.dev/v1alpha1/resourcegroup_types.go
  pkg/parse/root_test.go
  pkg/validate/validate_test.go
Labels: lgtm, size/S, approved

#1062 Add hydration-controller validation to logging test
  e2e/testcases/override_log_level_test.go
Labels: size/L, lgtm, approved

#1068 chore: Validate RSync reconciliation status
  pkg/kinds/resources.go
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
  pkg/syncer/syncertest/fake/dynamic_client.go
  pkg/util/watch/until.go
Labels: size/L, lgtm, approved

#1056 feat: add managed-by label for manager
  pkg/metadata/labels.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret_test.go
Labels: size/L, lgtm, approved

#1069 chore: Make fake client more like the real client
  pkg/reconcilermanager/controllers/otel_controller_test.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/syncer/syncertest/fake/dynamic_client.go
  pkg/syncer/syncertest/fake/minimize.go
  pkg/syncer/syncertest/fake/minimize_test.go
  pkg/syncer/syncertest/fake/storage.go
  pkg/syncer/syncertest/fake/subresource_storage.go
  pkg/util/mutate/mutate_test.go
Labels: lgtm, approved, size/XL

#1072 ci: add test runner iam to terraform config
  .gitignore
  e2e/testinfra/terraform/prow/service_accounts.tf
Labels: size/M, lgtm, approved

#1073 test: annotate git-server as not safe to evict
  e2e/nomostest/git-server.go
Labels: size/XS, lgtm, approved

#1074 Remove #kpt channel from communication
  README.md
Labels: size/XS, lgtm, approved

#1071 Add unit test scenario for APIVERSION
  pkg/vet/api_resources_test.go
Labels: size/M, lgtm, approved

#1075 test: fix multi sync test repo initialization
  e2e/testcases/multi_sync_test.go
Labels: lgtm, size/S, approved

#1076 fix: remove a false condition that sets the dynamic mode (#1059)
  e2e/testcases/namespace_selectors_test.go
  pkg/validate/scoped/hydrate/namespace_hydrator.go
  pkg/validate/scoped/hydrate/namespace_hydrator_test.go
Labels: size/M, lgtm, approved

#1079 test: fix multi sync flake with InitGitRepos
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/multi_sync_test.go
Labels: size/M, lgtm, approved

#1077 test: auto-rotate service account key & secret
  e2e/nomostest/artifactregistry/image.go
  e2e/testcases/helm_sync_test.go
Labels: size/L, lgtm, approved

#1078 test: address edge cases for e2e secret rotation
  e2e/testcases/helm_sync_test.go
  e2e/testinfra/terraform/prow/service_accounts.tf
Labels: size/M, lgtm, approved

#1080 fix: use project_id for GSA email
  e2e/testinfra/terraform/prow/service_accounts.tf
Labels: size/XS, lgtm, approved

#1081 Bump base image versions and helm/kustomize versions to fix CVEs
  Makefile
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#1082 Update git-sync and opentelemetry images for CVE fixes
  Makefile
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#1083 Update opentelemetry image for CVE fixes
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1084 fix: enable user output for version list
  e2e/testcases/helm_sync_test.go
Labels: size/XS, lgtm, approved

#1085 Update helm version to fix CVEs
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#1088 Update otel image to fix CVE
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved
