Repository GoogleContainerTools/config-sync, pull requests merged in 2023-01, with the labels that each got.

#335 Update license header to fix the presubmit failure
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
Labels: size/XS, lgtm, approved

#324 Add Config Sync resource related attributes to GCM
  cmd/hydration-controller/main.go
  cmd/reconciler-manager/main.go
  cmd/reconciler/main.go
  manifests/otel-agent-cm.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  pkg/kmetrics/register.go
  pkg/metrics/otel.go
  pkg/metrics/register.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: size/M, lgtm, approved

#242 Add reconciler finalizer to optionally destroy user objects
  e2e/nomostest/nt.go
  e2e/nomostest/policy/reposync.go
  e2e/nomostest/predicates.go
  e2e/testcases/reconciler_finalizer_test.go
  manifests/ns-reconciler-cluster-role.yaml
  pkg/api/configsync/v1beta1/reposync_types.go
  pkg/api/configsync/v1beta1/rootsync_types.go
  pkg/applier/applier.go
  pkg/applier/applier_err.go
  pkg/applier/applier_test.go
  pkg/applier/clientset.go
  pkg/applier/destroyer_test.go
  pkg/applier/stats/stats_test.go
  pkg/diff/precedence.go
  pkg/diff/precedence_test.go
  pkg/metadata/annotations.go
  pkg/metadata/finalizers.go
  pkg/metadata/metadata.go
  pkg/reconciler/finalizer/controller.go
  pkg/reconciler/finalizer/finalizer.go
  pkg/reconciler/finalizer/predicates.go
  pkg/reconciler/finalizer/reposync_finalizer.go
  pkg/reconciler/finalizer/reposync_finalizer_test.go
  pkg/reconciler/finalizer/rootsync_finalizer.go
  pkg/reconciler/finalizer/rootsync_finalizer_test.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reposync/conditions.go
  pkg/reposync/conditions_test.go
  pkg/rootsync/conditions.go
  pkg/rootsync/conditions_test.go
  pkg/syncer/reconcile/as_unstructured.go
  pkg/util/mutate/mutate.go
  pkg/util/mutate/mutate_test.go
Labels: size/XXL, lgtm, approved

#337 add docs for release branch infra provisioning
  e2e/testinfra/terraform/README.md
Labels: lgtm, size/S, approved

#338 update provisioning scripts for multi-project
  Makefile.build
  Makefile.oss.prow
  scripts/set-up-workload-identity-configs.sh
Labels: size/L, lgtm, approved

#339 Add instructions for configuring test resources
  e2e/testinfra/README.md
Labels: size/M, lgtm, approved

#341 fix the override reconcile timeout test (#320)
  e2e/nomostest/client.go
  e2e/nomostest/predicates.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testdata/low-priority-pause-deployment.yaml
  go.mod
  go.sum
  pkg/kinds/kinds.go
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/kpt.dev/resourcegroup/LICENSE
  vendor/kpt.dev/resourcegroup/apis/kpt.dev/v1alpha1/groupversion_info.go
  vendor/kpt.dev/resourcegroup/apis/kpt.dev/v1alpha1/resourcegroup_types.go
  vendor/kpt.dev/resourcegroup/apis/kpt.dev/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#343 Update git-sync version to 3.6.2 to clear vulnerabilities
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#344 Update git-sync version to 3.6.2 to clear vulnerabilities (#343)
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#345 add nomos image to build/publish
  Makefile
  Makefile.build
  build/all/Dockerfile
  e2e/nomostest/docker.go
  e2e/nomostest/ntopts/new.go
  e2e/testcases/cli_test.go
Labels: size/M, lgtm, approved

#346 add nomos image to build/publish (#345)
  Makefile
  Makefile.build
  build/all/Dockerfile
  e2e/nomostest/docker.go
  e2e/nomostest/ntopts/new.go
  e2e/testcases/cli_test.go
Labels: size/M, lgtm, approved

#348 improve logging of nomos image test
  e2e/testcases/cli_test.go
Labels: size/XS, lgtm, approved

#349 improve logging of nomos image test (#348)
  e2e/testcases/cli_test.go
Labels: size/XS, lgtm, approved

#347 Postprocess the junit report by appending a testcases.Failure (#329)
  Makefile.build
  build/test-e2e-go/e2e.sh
  build/test-e2e-go/gke/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  cmd/junit-report/main.go
  cmd/junit-report/resetfailure/reset_failure.go
  cmd/junit-report/resetfailure/reset_failure_test.go
  e2e/testdata/junit-report-updated.xml
  e2e/testdata/junit-report.xml
  go.mod
  go.sum
  scripts/build-junitreport-cli.sh
  scripts/lint-license-headers.sh
  vendor/github.com/jstemmer/go-junit-report/v2/LICENSE
  vendor/github.com/jstemmer/go-junit-report/v2/gtr/gtr.go
  vendor/github.com/jstemmer/go-junit-report/v2/junit/junit.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#352 Checkpoint & revert protected namespaces in e2e
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/namespaces_test.go
Labels: size/M, lgtm, approved

#351 Fix AsUnstructured to include the GVK
  pkg/syncer/reconcile/as_unstructured.go
  pkg/syncer/reconcile/as_unstructured_test.go
Labels: size/M, lgtm, approved

#354 Add RSync -> RoleBinding dependencies in e2e tests
  e2e/nomostest/config_sync.go
  e2e/nomostest/git.go
  e2e/testcases/composition_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/oci_sync_test.go
Labels: size/L, lgtm, approved

#356 Log object JSON when ValidateNotFound errors
  e2e/nomostest/validate.go
Labels: lgtm, size/S, approved

#357 Update git repo format when changed by ReInit
  e2e/nomostest/git.go
Labels: size/XS, lgtm, approved

#358 Simplify TestReconcilerFinalizer cleanup
  e2e/testcases/reconciler_finalizer_test.go
Labels: size/L, lgtm, approved

#353 make default VERSION and IMAGE_TAG the same
  Makefile
Labels: size/XS, lgtm, approved

#359 make default VERSION and IMAGE_TAG the same (#353)
  Makefile
Labels: size/XS, lgtm, approved

#342 add log/metric writing roles to compute account
  e2e/testinfra/terraform/common/service_accounts.tf
Labels: size/XS, lgtm, approved

#362 Add log.AsYAML and log.AsYAMLDiff
  go.mod
  go.sum
  pkg/util/log/stringer.go
  pkg/util/log/stringer_test.go
  vendor/github.com/kylelemons/godebug/LICENSE
  vendor/github.com/kylelemons/godebug/diff/diff.go
  vendor/modules.txt
Labels: lgtm, approved, size/XL

#361 Replace Wait with Watch (continued)
  e2e/nomostest/clean.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/wait.go
  e2e/nomostest/watch.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/reconciler_finalizer_test.go
  pkg/util/log/stringer.go
  pkg/util/log/stringer_test.go
Labels: lgtm, approved, size/XL

#363 Add TaskGroup to exec tasks in parallel
  e2e/nomostest/taskgroup/taskgroup.go
  e2e/testcases/multi_sync_test.go
Labels: size/L, lgtm, approved

#205 Use deletion propagation for e2e test cleanup
  e2e/nomostest/clean.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/deletion_propagation.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/reset.go
  e2e/nomostest/watch.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/root_sync_test.go
Labels: size/XXL, lgtm, approved

#364 Revert "Use deletion propagation for e2e test cleanup"
  e2e/nomostest/clean.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/deletion_propagation.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/reset.go
  e2e/nomostest/watch.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/root_sync_test.go
Labels: size/XXL, lgtm, approved

#365 Clean RepoSyncs with deletion-propagation enabled
  e2e/nomostest/clean.go
  e2e/nomostest/deletion_propagation.go
Labels: size/L, lgtm, approved

#366 Fix RepoSync Clean to allow NoMatch error
  e2e/nomostest/clean.go
Labels: size/XS, lgtm, approved

#368 Improve e2e uninstall of config-sync
  e2e/nomostest/clean.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/webhook.go
Labels: size/L, lgtm, approved

#369 Stream e2e log output
  Makefile.e2e
  Makefile.e2e.ci
Labels: lgtm, size/S, approved

#370 Escape the newline character in the apply/reconcile log
  pkg/applier/status.go
  pkg/applier/status_test.go
  pkg/applier/utils.go
Labels: size/M, lgtm, approved

#367 Prevent declaring the reconciler's own RSync object in its repo
  cmd/nomoserrors/examples/examples.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/root_sync_test.go
  pkg/parse/namespace.go
  pkg/parse/root.go
  pkg/validate/objects/raw.go
  pkg/validate/raw/raw.go
  pkg/validate/raw/validate/self_reconcile_validator.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: size/L, lgtm, approved

#334 Re-enable the validation for the resource_conflicts metric
  e2e/nomostest/metrics/validate.go
Labels: size/XS, lgtm, approved

#374 Update the public helm chart used by the namespace repo
  e2e/testcases/helm_sync_test.go
Labels: size/XS, lgtm, approved

#376 Disable MariaDB persistence to avoid leaking PVCs
  e2e/testdata/root-sync-helm-chart-cr.yaml
Labels: size/XS, lgtm, approved
