Repository GoogleContainerTools/config-sync, pull requests merged in 2023-09, with the labels that each got.

#852 Fix TestManagingReconciler
  e2e/testcases/reconciler_manager_test.go
Labels: size/XS, lgtm, approved

#789 chore: upgrade kind version to v0.20.0
  Makefile
  e2e/nomostest/clusters/kind.go
  go.mod
  go.sum
  vendor/github.com/google/safetext/LICENSE
  vendor/github.com/google/safetext/common/common.go
  vendor/github.com/google/safetext/yamltemplate/yamltemplate.go
  vendor/modules.txt
  vendor/sigs.k8s.io/kind/pkg/apis/config/defaults/image.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/types.go
  vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/installcni/cni.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/waitforready/waitforready.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/delete/delete.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeadm/config.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/paths.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/read.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/write.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/loadbalancer/config.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/loadbalancer/const.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/logs/logs.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/provision.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/OWNERS
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/network.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provision.go
  vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/provider.go
  vendor/sigs.k8s.io/kind/pkg/cluster/nodeutils/util.go
  vendor/sigs.k8s.io/kind/pkg/cluster/provider.go
  vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go
  vendor/sigs.k8s.io/kind/pkg/fs/fs.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/convert_v1alpha4.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/encoding/load.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/types.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/validate.go
  vendor/sigs.k8s.io/kind/pkg/internal/apis/config/zz_generated.deepcopy.go
Labels: size/XXL, lgtm, approved

#855 test: wait for deployments before checking pods
  e2e/testcases/multi_sync_test.go
Labels: lgtm, size/S, approved

#856 Inject GSA email to root-reconciler when using FWI
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/M, lgtm, approved

#857 Inject GSA email to root-reconciler when using FWI (#856)
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/M, lgtm, approved

#858 Update helm binary to fix CVE
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#859 Update helm binary to fix CVE (#858)
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#853 Remove client-side throttling from nomos status
  e2e/testcases/stress_test.go
  pkg/client/restconfig/config.go
Labels: lgtm, size/S, approved

#861 Add more logs when the test fails
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved

#860 fix: Retry status updates
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/reconciler_manager_test.go
  pkg/reconciler/finalizer/reposync_finalizer.go
  pkg/reconciler/finalizer/reposync_finalizer_test.go
  pkg/reconciler/finalizer/rootsync_finalizer.go
  pkg/reconciler/finalizer/rootsync_finalizer_test.go
  pkg/reconcilermanager/controllers/create_or_update.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/status/api_server_error.go
  pkg/util/mutate/mutate.go
  pkg/util/mutate/mutate_test.go
Labels: lgtm, approved, size/XL

#862 Merge reset and printTestLogs into a single cleanup block (#861)
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved

#864 test: Fix TestMustRemoveCRD to use Watch
  e2e/testcases/custom_resource_definitions_test.go
Labels: size/XS, lgtm, approved

#865 test: Fix TestComposition to allow status changes
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/composition_test.go
Labels: size/M, lgtm, approved

#866 fix: Record metrics when delete fails
  pkg/applier/applier.go
Labels: size/XS, lgtm, approved

#867 text: Fix TestConflictingDefinitions_RootToRoot
  e2e/testcases/multi_sync_test.go
Labels: lgtm, size/S, approved

#870 fix: TestCRDDeleteBeforeRemoveCustomResourceV1
  e2e/testcases/custom_resources_test.go
Labels: size/M, lgtm, approved

#874 test: Use partial metadata when counting lists
  e2e/testcases/stress_test.go
Labels: lgtm, size/S, approved

#873 Add context to setup/teardown error messages
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
Labels: size/M, lgtm, approved

#869 Proposal: Explicit-only namespace strategy for RootSyncs
  docs/design-docs/01-explicit-only-namespace-strategy.md
Labels: size/L, ok-to-test, lgtm, approved

#877 Stop rebuilding the kubekins-e2e image in Config Sync
  Makefile.oss.prow
  build/prow/kubekins-e2e/Dockerfile
Labels: size/M, lgtm, approved

#879 ci: enable presubmits on new buildenv before publishing
  Makefile
  Makefile.build
Labels: size/XS, lgtm, approved

#871 docs: fix description of num-clusters flag
  docs/development.md
Labels: size/XS, lgtm, approved

#876 chore: Configure container resources at runtime
  e2e/nomostest/client.go
  e2e/nomostest/nt.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/reconciler_manager_test.go
  manifests/templates/reconciler-manager-configmap.yaml
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_container_resources.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/XXL, lgtm, approved

#880 Update Config Sync component versions to fix CVEs
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/third_party/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#878 Update go version in the test images
  Makefile
  Makefile.build
  build/buildenv/Dockerfile
  build/prow/gke-e2e/Dockerfile
  build/test-e2e-go/kind/Dockerfile
  scripts/test-unit.sh
Labels: lgtm, size/S, approved

#875 Update Go to 1.20.8 to fix CVEs
  build/all/Dockerfile
  build/prow/vulnerability-scanner/Dockerfile
  go.mod
Labels: size/XS, lgtm, approved

#881 fix: explicitly set makefile shell to bash
  Makefile
  Makefile.build
Labels: size/XS, lgtm, approved

#882 test: Fix TestAutopilotReconcilerAdjustment
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/reconciler_manager_test.go
Labels: size/L, lgtm, approved

#884 Bump Kustomize version to fix CVE
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#883 feat: add namespaceStrategy API
  clientgen/apis/clientset.go
  clientgen/apis/fake/clientset_generated.go
  clientgen/apis/fake/register.go
  clientgen/apis/scheme/register.go
  cmd/reconciler/main.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/namespace_strategy_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/reconciler_manager_test.go
  manifests/rootsync-crd.yaml
  pkg/api/configsync/register.go
  pkg/api/configsync/v1alpha1/getters.go
  pkg/api/configsync/v1alpha1/reposync_types.go
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1alpha1/rootsync_types.go
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/getters.go
  pkg/api/configsync/v1beta1/reposync_types.go
  pkg/api/configsync/v1beta1/resource_override.go
  pkg/api/configsync/v1beta1/rootsync_types.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/util.go
Labels: size/XXL, lgtm, approved

#885 Store last hydration error in-memory for rehydrate
  pkg/hydrate/controller.go
  pkg/hydrate/controller_test.go
Labels: size/M, lgtm, approved

#890 ci: fix junit test output parsing
  build/test-e2e-go/e2e.sh
Labels: size/XS, lgtm, approved

#891 fix: add askpass to override container enum
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1beta1/resource_override.go
Labels: lgtm, size/S, approved

#892 fix: increase default cpuRequest for askpass
  pkg/reconcilermanager/controllers/reconciler_container_resources.go
Labels: size/XS, lgtm, approved

#894 fix: add otel-agent to override api
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1beta1/resource_override.go
Labels: lgtm, size/S, approved

#895 fix: increase default memoryRequest for helm-sync
  pkg/reconcilermanager/controllers/reconciler_container_resources.go
Labels: size/XS, lgtm, approved

#868 Nomos CLI: replace APIGROUP with APIVERSION
  cmd/nomoserrors/examples/examples.go
  e2e/testcases/cli_test.go
  pkg/vet/api_resources.go
  pkg/vet/api_resources_test.go
Labels: size/L, lgtm, approved

#898 fix: persist deployment fields during allowListing
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
Labels: size/M, lgtm, approved

#899 Nomos CLI: replace APIGROUP with APIVERSION (#868)
  cmd/nomoserrors/examples/examples.go
  e2e/testcases/cli_test.go
  pkg/vet/api_resources.go
  pkg/vet/api_resources_test.go
Labels: size/L, lgtm, approved

#901 Add a stress test with 100 CRDs (#804)
  e2e/testcases/stress_test.go
Labels: size/M, lgtm, approved

#904 Refactor git-sync env variables to constants
  e2e/testcases/no_ssl_verify_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/private_cert_secret_test.go
  pkg/reconcilermanager/controllers/gitsync_env.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#896 new askpass sidecar
  Makefile
  Makefile.build
  build/all/Dockerfile
  cmd/gcenode-askpass-sidecar/main.go
  go.mod
  manifests/templates/reconciler-manager-configmap.yaml
  pkg/askpass/askpass.go
  pkg/askpass/askpass_test.go
Labels: size/L, lgtm, approved, tide/merge-method-squash

#900 Migrate to git-sync v4
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  pkg/api/configsync/register.go
  pkg/api/configsync/v1alpha1/getters.go
  pkg/api/configsync/v1alpha1/gitconfig.go
  pkg/api/configsync/v1beta1/getters.go
  pkg/api/configsync/v1beta1/gitconfig.go
  pkg/reconcilermanager/controllers/gitsync_env.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/util.go
Labels: size/L, lgtm, approved

#903 [CHERRY-PICK] fix: persist deployment fields during allowListing (#898)
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
Labels: size/M, lgtm, approved

#902 Remove client-side throttling from nomos status (#853)
  e2e/testcases/stress_test.go
  pkg/client/restconfig/config.go
Labels: lgtm, size/S, approved

#886 Add internal retry for SourceCommitAndDir and readHydratedDir
  e2e/testcases/policy_dir_test.go
  pkg/hydrate/controller.go
  pkg/hydrate/controller_test.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/source.go
  pkg/parse/source_test.go
  pkg/util/retry.go
Labels: lgtm, approved, size/XL

#905 [CHERRY-PICK] new askpass sidecar (#896)
  Makefile
  Makefile.build
  build/all/Dockerfile
  cmd/gcenode-askpass-sidecar/main.go
  go.mod
  manifests/templates/reconciler-manager-configmap.yaml
  pkg/askpass/askpass.go
  pkg/askpass/askpass_test.go
Labels: size/L, lgtm, approved

#887 Expose transient errors in the R*Sync status field
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/state.go
  pkg/status/multierror.go
Labels: size/M, lgtm, approved

#888 feat: update API docs for namespaceStrategy
  cmd/reconciler/main.go
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1beta1/resource_override.go
Labels: size/M, lgtm, approved
