Repository GoogleContainerTools/config-sync, pull requests merged in 2024-11, with the labels that each got.

#1470 chore: Clean up sync event naming & cache resets
  cmd/reconciler/main.go
  pkg/api/configsync/register.go
  pkg/parse/event_handler.go
  pkg/parse/events/builder.go
  pkg/parse/events/events.go
  pkg/parse/events/funnel_test.go
  pkg/parse/root_reconciler_test.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/reconciler/reconciler.go
Labels: size/L, lgtm, approved

#1473 ci: rename the kustomize tarball to config-sync.tar.gz
  Makefile.build
Labels: size/XS, lgtm, approved

#1472 fix: ignored conflicts and watch updates
  pkg/parse/event_handler.go
  pkg/parse/events/publisher.go
Labels: lgtm, size/S, approved

#1475 chore: test retry with long and short sync periods
  pkg/parse/events/funnel_test.go
Labels: size/L, lgtm, approved

#1479 chore: bump otelcontribcol to 0.103.0-gke.5
  Makefile
Labels: size/XS, lgtm, approved

#1478 chore: bump git-sync to latest version
  Makefile
Labels: size/XS, lgtm, approved

#1481 fix: surface source status update error
  pkg/parse/run.go
Labels: size/XS, lgtm, approved

#1482 chore: extract reconciler.Render method
  pkg/hydrate/controller.go
  pkg/parse/reconciler.go
  pkg/parse/run.go
  pkg/parse/state.go
  pkg/status/transient_error.go
Labels: size/L, lgtm, approved

#1484 chore: clarify syncPath vs syncDir
  pkg/hydrate/controller.go
  pkg/hydrate/controller_test.go
  pkg/parse/reconciler.go
  pkg/parse/repo_sync_parser.go
  pkg/parse/root_reconciler_test.go
  pkg/parse/root_sync_parser.go
  pkg/parse/run.go
  pkg/parse/source.go
  pkg/parse/source_test.go
  pkg/parse/state.go
Labels: size/L, lgtm, approved

#1485 chore: ReconcilerState cleanup
  pkg/parse/event_handler.go
  pkg/parse/run.go
  pkg/parse/state.go
Labels: size/L, lgtm, approved

#1488 chore: cleanup reconciler set status method usage
  pkg/parse/reconciler.go
  pkg/parse/repo_sync_client.go
  pkg/parse/root_sync_client.go
  pkg/parse/run.go
  pkg/parse/status.go
Labels: size/L, lgtm, approved

#1489 chore: git sync update to v4.3.0-gke.3__linux_amd64
  Makefile
Labels: size/XS, lgtm, approved

#1480 chore: extract Reconciler.Fetch method
  pkg/parse/reconciler.go
  pkg/parse/run.go
  pkg/parse/state.go
Labels: size/L, lgtm, approved

#1490 chore: updated the golang.org/x/oauth2 to v0.24.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/token.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#1492 chore: update git-sync to v4.3.0-gke.4__linux_amd64
  Makefile
Labels: size/XS, lgtm, approved

#1491 chore: DefaultRunFunc -> reconciler.Reconcile
  pkg/parse/event_handler.go
  pkg/parse/reconciler.go
  pkg/parse/root_reconciler_test.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/reconciler/reconciler.go
Labels: size/L, lgtm, approved

#1494 fix: out-of-order status updates
  pkg/parse/run.go
Labels: size/M, lgtm, approved

#1495 chore: split parse & update methods
  pkg/parse/cache.go
  pkg/parse/root_reconciler_test.go
  pkg/parse/run.go
  pkg/parse/updater.go
  pkg/webhook/configuration/update.go
Labels: size/L, lgtm, approved

#1460 chore: merge sync & full-sync events
  pkg/parse/event_handler.go
  pkg/parse/events/builder.go
  pkg/parse/events/doc.go
  pkg/parse/events/events.go
  pkg/parse/events/funnel_test.go
  pkg/parse/opts.go
  pkg/parse/root_reconciler_test.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/state.go
  pkg/reconciler/reconciler.go
Labels: size/L, lgtm, approved

#1498 fix: tollerate stale resource group discovery
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
  pkg/resourcegroup/controllers/root/root_controller_test.go
  pkg/resourcegroup/controllers/runner/run.go
  pkg/resourcegroup/controllers/typeresolver/fake_discovery.go
  pkg/resourcegroup/controllers/typeresolver/typeresolver.go
  pkg/resourcegroup/controllers/typeresolver/typeresolver_test.go
Labels: lgtm, approved, size/XL
