Repository GoogleContainerTools/config-sync, pull requests merged in 2024-09, with the labels that each got.

#1417 e2e: Use Must with WatchForAllSyncs
  e2e/nomostest/new.go
  e2e/testcases/acme_test.go
  e2e/testcases/admission_test.go
  e2e/testcases/adopt_client_side_applied_test.go
  e2e/testcases/apiservice_test.go
  e2e/testcases/basic_test.go
  e2e/testcases/cli_test.go
  e2e/testcases/cluster_resources_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/custom_resource_definitions_schema_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/declared_fields_test.go
  e2e/testcases/gatekeeper_test.go
  e2e/testcases/git_sync_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/kptfile_test.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/local_config_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/multiversion_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespace_selectors_test.go
  e2e/testcases/namespace_strategy_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/no_ssl_verify_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/otel_collector_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/override_role_refs_test.go
  e2e/testcases/preserve_fields_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/remediator_test.go
  e2e/testcases/resource_group_controller_test.go
  e2e/testcases/root_sync_test.go
  e2e/testcases/ssh_known_hosts_test.go
  e2e/testcases/status_enablement_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/sync_ordering_test.go
Labels: size/XXL, lgtm, approved

#1410 e2e: refactor sync expectations
  e2e/nomostest/config_sync.go
  e2e/nomostest/config_sync_sources.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/syncsource/syncsource.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/cli_test.go
  e2e/testcases/gcenode_test.go
  e2e/testcases/github_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/policy_dir_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/proxy_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/workload_identity_test.go
Labels: lgtm, approved, size/XL

#1418 ci: remove GCP_PROJECT arg from test-e2e-kind
  Makefile.e2e
Labels: size/XS, lgtm, approved

#1419 test: fix sha1Func for oci workload identity test
  e2e/testcases/workload_identity_test.go
Labels: size/XS, lgtm, approved

#1421 fix: set expected oci digest for wi tests
  e2e/testcases/workload_identity_test.go
Labels: lgtm, size/S, approved

#1422 chore: bump otelcontribcol to 0.103.0-gke.4
  Makefile
Labels: size/XS, lgtm, approved

#1423 test: Fix RootSync spec in TestStressLargeRequest
  e2e/testcases/stress_test.go
Labels: size/XS, lgtm, approved

#1425 [cherry-pick] chore: bump otelcontribcol to 0.103.0-gke.4 (#1422)
  Makefile
Labels: size/XS, lgtm, approved

#1424 test: fix gcr workload identity tests
  e2e/testcases/workload_identity_test.go
Labels: size/M, lgtm, approved

#1426 test: fix git dir for kcc test RootSync
  e2e/testcases/kcc_test.go
Labels: size/XS, lgtm, approved

#1427 chore: bump git-sync to v4.2.4-gke.4
  Makefile
Labels: size/XS, lgtm, approved

#1428 [cherry-pick] chore: bump git-sync to v4.2.4-gke.4 (#1427)
  Makefile
Labels: size/XS, lgtm, approved

#1430 e2e: Fix RSync constructor expectations
  e2e/nomostest/config_sync.go
Labels: lgtm, size/S, approved

#1420 chore: clean up unused e2e-kind make targets
  Makefile.e2e
Labels: lgtm, size/S, approved

#1432 chore: update debian-base:bookworm
  Makefile
Labels: size/XS, lgtm, approved

#1434 chore: git-sync cve fixes
  Makefile
Labels: size/XS, lgtm, approved

#1431 Include ConfigMaps from all controller namespaces in bugreport
  e2e/testcases/cli_test.go
  pkg/bugreport/bugreport.go
Labels: lgtm, size/S, approved

#1436 refactor: clean up unused clusterName in otelreconciler
  cmd/reconciler-manager/main.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: lgtm, size/S, approved

#1435 e2e: Add watch predicate options
  e2e/nomostest/clean.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/crds.go
  e2e/nomostest/reset.go
  e2e/nomostest/testwatcher/watch.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/admission_test.go
  e2e/testcases/cli_test.go
  e2e/testcases/cluster_resources_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/composition_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/github_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespace_selectors_test.go
  e2e/testcases/namespace_strategy_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/no_ssl_verify_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_log_level_test.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/preserve_fields_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/profiling_test.go
  e2e/testcases/proxy_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/resource_group_controller_test.go
  e2e/testcases/root_sync_test.go
  e2e/testcases/ssh_known_hosts_test.go
  e2e/testcases/status_enablement_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/sync_ordering_test.go
  e2e/testcases/workload_identity_test.go
Labels: size/XXL, lgtm, approved

#1429 e2e: Update WatchForSync to take a SyncSource
  e2e/nomostest/config_sync_sources.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/composition_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/override_role_refs_test.go
  e2e/testcases/profiling_test.go
Labels: lgtm, approved, size/XL

#1438 Bump git-sync to v4.2.4-gke.8 (#1437)
  Makefile
Labels: size/XS, lgtm, approved

#1440 fix: Remove ApplySet part-of label on abandon
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/sync_ordering_test.go
  pkg/applier/applier.go
  pkg/applier/clientset.go
  pkg/metadata/metadata.go
  pkg/metadata/metadata_test.go
  pkg/reconciler/reconciler.go
  pkg/syncer/reconcile/apply.go
  pkg/syncer/syncertest/fake/applier.go
Labels: lgtm, approved, size/XL

#1439 Only watch ResourceGroups with the correct owner label
  e2e/nomostest/testresourcegroup/resourcegroup.go
  pkg/resourcegroup/controllers/root/root_controller.go
  pkg/resourcegroup/controllers/root/root_controller_test.go
Labels: size/L, ok-to-test, lgtm, approved

#1443 test: fix the autobursting detection
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved

#1444 test: fix the autobursting detection (#1443)
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved
