Repository GoogleContainerTools/config-sync, pull requests merged in 2024-05, with the labels that each got.

#1202 chore: update golang.org/x/net library
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mmap_nomremap.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#1205 Remove unused GVK return from Applier.Apply
  pkg/applier/applier.go
  pkg/applier/applier_test.go
  pkg/parse/root_test.go
  pkg/parse/updater.go
Labels: size/M, lgtm, approved

#1201 [chore] Bump otelcontribcol to 0.99.0-gke.1
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1206 Unwrap single status.MultiErrors
  e2e/testcases/cli_test.go
  pkg/applier/applier.go
  pkg/applier/applier_err_test.go
  pkg/applier/applier_test.go
  pkg/applier/destroyer_test.go
  pkg/diff/precedence_test.go
  pkg/hydrate/controller_test.go
  pkg/kinds/convert_test.go
  pkg/kinds/lookup_test.go
  pkg/remediator/watch/manager_test.go
  pkg/status/multierror.go
  pkg/testing/testerrors/testerrors.go
  pkg/util/watch/options_test.go
  pkg/validate/objects/tree_test.go
  pkg/validate/raw/validate/cluster_selector_validator_test.go
  pkg/validate/raw/validate/disallowed_fields_validator_test.go
Labels: lgtm, approved, size/XL

#1203 chore: update owners
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1208 Fix status errors to work with errors.Is
  pkg/status/error_builder.go
  pkg/status/error_impl.go
  pkg/status/management_conflict_error.go
  pkg/status/message_error_impl.go
  pkg/status/path_error_impl.go
  pkg/status/resource_error_impl.go
  pkg/status/wrapped_error_impl.go
  pkg/testing/testerrors/testerrors.go
Labels: size/L, lgtm, approved

#1209 Test errors more strictly
  pkg/applier/applier_test.go
  pkg/hydrate/controller.go
  pkg/parse/repository_scope_test.go
  pkg/parse/root_test.go
  pkg/parse/run_test.go
  pkg/reconciler/finalizer/reposync_finalizer_test.go
  pkg/reconciler/finalizer/rootsync_finalizer_test.go
  pkg/remediator/reconcile/reconciler_test.go
  pkg/remediator/reconcile/worker_test.go
  pkg/remediator/watch/manager_test.go
  pkg/status/multierror.go
  pkg/status/multierror_test.go
  pkg/syncer/client/client_test.go
  pkg/util/clusterconfig/crd_test.go
  pkg/util/mutate/mutate_test.go
  pkg/util/retry.go
Labels: lgtm, approved, size/XL

#1210 chore: bumping up to golang:1.21.9-bookworm
  Makefile
Labels: size/XS, lgtm, approved

#1211 Add e2e NT.ClusterVersion detection
  e2e/nomostest/clusterversion/cluster_version.go
  e2e/nomostest/clusterversion/cluster_version_test.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/multiversion_test.go
Labels: size/L, lgtm, approved

#1196 Add memory test doc for 1.18
  docs/memory-usage-reduce-1160-1180.md
Labels: size/M, lgtm, approved

#1214 chore: use trusted golang base image
  Makefile
Labels: size/XS, lgtm, approved

#1213 test: remove v1beta1 CRD/RBAC e2e tests
  e2e/nomostest/nt.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/multiversion_test.go
  e2e/testdata/customresources/v1beta1_crds/anvil-crd-only-v2.yaml
  e2e/testdata/customresources/v1beta1_crds/anvil-crd-structural-v1.yaml
  e2e/testdata/customresources/v1beta1_crds/anvil-crd-structural.yaml
  e2e/testdata/customresources/v1beta1_crds/anvil-crd-v1.yaml
  e2e/testdata/customresources/v1beta1_crds/anvil-crd-v2.yaml
  e2e/testdata/customresources/v1beta1_crds/anvil-crd.yaml
  e2e/testdata/customresources/v1beta1_crds/clusteranvil-crd-v1.yaml
  e2e/testdata/customresources/v1beta1_crds/clusteranvil-crd-v2.yaml
  e2e/testdata/customresources/v1beta1_crds/clusteranvil-crd.yaml
Labels: lgtm, approved, size/XL

#1215 chore: bump helm to v3.14.4-gke.1
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#1216 chore: bump debian-base to bookworm-v1.0.2-gke.2
  Makefile
Labels: size/XS, lgtm, approved

#1204 Fix declared.Resources to be consistently ordered
  go.mod
  go.sum
  pkg/applier/applier.go
  pkg/applier/fake/applier.go
  pkg/declared/namespace_safeguard.go
  pkg/declared/namespace_safeguard_test.go
  pkg/declared/resources.go
  pkg/declared/resources_test.go
  pkg/importer/filesystem/config_parser.go
  pkg/importer/filesystem/fake/config_parser.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run_test.go
  pkg/parse/source_test.go
  pkg/remediator/conflict/handler.go
  pkg/remediator/fake/remediator.go
  pkg/remediator/watch/manager_test.go
  pkg/syncer/reconcile/fight/handler.go
  pkg/testing/fake/objects.go
  vendor/github.com/elliotchance/orderedmap/v2/LICENSE
  vendor/github.com/elliotchance/orderedmap/v2/list.go
  vendor/github.com/elliotchance/orderedmap/v2/orderedmap.go
  vendor/github.com/wk8/go-ordered-map/.gitignore
  vendor/github.com/wk8/go-ordered-map/.golangci.yml
  vendor/github.com/wk8/go-ordered-map/LICENSE
  vendor/github.com/wk8/go-ordered-map/Makefile
  vendor/github.com/wk8/go-ordered-map/README.md
  vendor/github.com/wk8/go-ordered-map/orderedmap.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#1217 refactor: clean up top level testing directory
  pkg/util/clusterconfig/crd_test.go
  testing/testoutput/allconfigs.go
  testing/testoutput/annotations.go
Labels: size/L, lgtm, approved

#1218 chore: bump git-sync to v4.2.1-gke.10
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#1220 test: use longer waits for managed field tests
  e2e/testcases/managed_resources_test.go
Labels: size/M, lgtm, approved

#1221 chore: fix typo in kcc condition err
  pkg/resourcegroup/controllers/status/status.go
Labels: size/XS, lgtm, approved

#1222 test: print RootSync for truncateSourceError
  e2e/testcases/stress_test.go
Labels: size/XS, lgtm, approved

#1227 test: use SSA to create parent RootSync
  e2e/nomostest/new.go
Labels: size/XS, lgtm, approved

#1229 test: use SSA to create parent RootSync (#1227)
  e2e/nomostest/new.go
Labels: size/XS, lgtm, approved

#1228 Add tests to cover the behaviour of backoff and jitter on retry
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/reconciler/reconciler.go
Labels: size/L, ok-to-test, lgtm, approved

#1230 Add retry when cleanup test finalizers
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/reconciler_manager_test.go
Labels: size/M, lgtm, approved

#1231 e2e: attempt to uninstall packages in cleanup
  e2e/nomostest/clean.go
  e2e/nomostest/testpredicates/predicates.go
Labels: size/L, lgtm, approved

#1233 chore: filter vulnerability status by the analysis type
  scripts/vulnerabilities.sh
Labels: size/XS, lgtm, approved

#1236 test: clean up legacy monorepo e2e options
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/nomostest/ntopts/new.go
  e2e/nomostest/ntopts/nomos.go
Labels: size/M, lgtm, approved

#1234 [metric] #1 Turn metric names to const
  pkg/metrics/metrics.go
  pkg/metrics/views.go
  pkg/resourcegroup/controllers/metrics/metrics.go
  pkg/resourcegroup/controllers/metrics/views.go
Labels: size/L, lgtm, approved

#1238 test: log cluster hash and version along with the cluster name
  e2e/nomostest/client.go
  e2e/nomostest/clusters/gke.go
  e2e/nomostest/clusters/kind.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/new.go
Labels: size/M, lgtm, approved

#1242 test: fix panic in metric validation
  pkg/testing/testmetrics/testexporter.go
Labels: lgtm, size/S, approved

#1199 Add event handler to Applier/Destroyer
  pkg/applier/applier.go
  pkg/applier/applier_test.go
  pkg/applier/destroyer_test.go
  pkg/applier/fake/applier.go
  pkg/applier/stats/stats.go
  pkg/parse/root_test.go
  pkg/parse/updater.go
  pkg/reconciler/finalizer/base_finalizer.go
  pkg/reconciler/finalizer/finalizer.go
  pkg/reconciler/finalizer/reposync_finalizer.go
  pkg/reconciler/finalizer/reposync_finalizer_test.go
  pkg/reconciler/finalizer/rootsync_finalizer.go
  pkg/reconciler/finalizer/rootsync_finalizer_test.go
Labels: lgtm, approved, size/XL
