Repository GoogleContainerTools/config-sync, pull requests merged in 2024-06, with the labels that each got.

#1235 [metric] #2 Revert declared_resources metric name
  e2e/testcases/otel_collector_test.go
  e2e/testdata/otel-collector/otel-cm-full-gcm.yaml
  go.mod
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: lgtm, approved, size/XL

#1243 Mount empty volume for hydration-controller's service account
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, needs-ok-to-test, lgtm, approved

#1241 Use field managers for all K8s API calls
  cmd/nomos/hydrate/hydrate.go
  cmd/nomos/util/constants.go
  cmd/nomos/vet/vet_impl.go
  pkg/api/configsync/register.go
  pkg/applier/utils.go
  pkg/parse/namespace.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run.go
  pkg/reconciler/finalizer/reposync_finalizer.go
  pkg/reconciler/finalizer/rootsync_finalizer.go
  pkg/reconciler/finalizer/rootsync_finalizer_test.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/create_or_update.go
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
  pkg/reconcilermanager/controllers/reconciler_finalizer_handler.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/remediator/reconcile/reconciler_test.go
  pkg/remediator/reconcile/worker_test.go
  pkg/resourcegroup/controllers/resourcegroup/constants.go
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
  pkg/resourcegroup/controllers/root/root_controller.go
  pkg/resourcegroup/controllers/root/root_controller_test.go
  pkg/syncer/client/client.go
  pkg/syncer/client/client_test.go
  pkg/syncer/reconcile/apply.go
  pkg/syncer/syncertest/fake/applier.go
  pkg/syncer/syncertest/fake/client.go
  pkg/syncer/syncertest/fake/dynamic_client.go
  pkg/syncer/syncertest/fake/storage.go
  pkg/util/mutate/mutate.go
  pkg/util/mutate/mutate_test.go
  pkg/validate/scoped/hydrate/namespace_hydrator.go
  pkg/validate/scoped/hydrate/namespace_hydrator_test.go
  pkg/validate/scoped/scoped.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
  pkg/webhook/configuration/update.go
Labels: lgtm, approved, size/XL

#1244 Rename declared.RootReconciler to RootScope
  cmd/nomos/hydrate/hydrate.go
  cmd/nomos/vet/vet_impl.go
  cmd/nomoserrors/examples/examples.go
  cmd/reconciler/main.go
  e2e/nomostest/kustomizecomponents/validate.go
  e2e/testcases/composition_test.go
  e2e/testcases/gcenode_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespace_strategy_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/workload_identity_test.go
  pkg/applier/applier.go
  pkg/applier/applier_test.go
  pkg/declared/resource_manager.go
  pkg/declared/resource_manager_test.go
  pkg/declared/scope.go
  pkg/diff/diff_test.go
  pkg/diff/precedence.go
  pkg/diff/precedence_test.go
  pkg/parse/annotations.go
  pkg/parse/repository_scope.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/source_test.go
  pkg/reconciler/finalizer/controller.go
  pkg/reconciler/finalizer/finalizer.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/remediator/reconcile/reconciler_test.go
  pkg/remediator/reconcile/worker_test.go
  pkg/remediator/remediator.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/filteredwatcher_test.go
  pkg/remediator/watch/watcher.go
  pkg/reposync/constants.go
  pkg/validate/raw/raw.go
  pkg/validate/scoped/hydrate/namespace_hydrator.go
  pkg/validate/scoped/hydrate/namespace_hydrator_test.go
  pkg/validate/scoped/scoped.go
  pkg/validate/validate_test.go
Labels: size/L, lgtm, approved

#1246 test: fix flakiness of TestResourceGroupCustomResource
  e2e/testcases/custom_resources_test.go
Labels: ok-to-test, lgtm, size/S, approved

#1248 Bump otelcontrolcol to 0.102.0-gke.2
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1249 Bump otelcontrolcol to 0.102.0-gke.2 (#1248)
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1232 [metric] #3 Reset the declared_resources metric when at a new commit [restored]
  e2e/testcases/otel_collector_test.go
  pkg/declared/resources.go
Labels: size/L, lgtm, approved

#1251 test: log the repo creation timestamp
  e2e/nomostest/reset.go
Labels: size/XS, lgtm, approved

#1250 Update Bitbucket workspace
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/XS, lgtm, approved

#1255 Fix TestReconcileRepoSyncLifecycleValidToInvalid
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
Labels: lgtm, size/S, approved

#1252 test: Update Bitbucket workspace (#1250)
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/XS, lgtm, approved

#1258 Modify install-kustomize script
  scripts/install-kustomize.sh
Labels: size/XS, needs-ok-to-test, lgtm, approved

#1259 Move haiyanmeng to emeritus owner
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1260 test: fix panic in metric validation (again)
  pkg/testing/testmetrics/testexporter.go
Labels: size/XS, lgtm, approved

#1256 Add --load-restrictor flag to Kustomize build
  e2e/testdata/hydration/helm-overlay/base/kustomization.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/.helmignore
  e2e/testdata/hydration/helm-overlay/charts/coredns/Chart.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/README.md
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/NOTES.txt
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/_helpers.tpl
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/clusterrole-autoscaler.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/clusterrole.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/clusterrolebinding-autoscaler.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/clusterrolebinding.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/configmap-autoscaler.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/configmap.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/deployment-autoscaler.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/deployment.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/hpa.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/poddisruptionbudget.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/podsecuritypolicy.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/service-metrics.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/service.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/serviceaccount-autoscaler.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/serviceaccount.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/templates/servicemonitor.yaml
  e2e/testdata/hydration/helm-overlay/charts/coredns/values.yaml
  pkg/hydrate/tool_util.go
Labels: size/XS, ok-to-test, lgtm, approved

#1261 fix: deadlock in Updater.Errors()
  pkg/parse/updater.go
Labels: size/XS, lgtm, approved

#1257 Refactor parser.Options to use a normal mutex
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run_test.go
  pkg/parse/source_test.go
Labels: lgtm, size/S, approved

#1240 feat: add OSS migration logic
  cmd/nomos/migrate/configmanagement.go
  cmd/nomos/migrate/migrate.go
  cmd/nomos/migrate/monorepo.go
  cmd/nomos/status/client.go
  cmd/nomos/util/configmanagement.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/cli_test.go
  e2e/testdata/configmanagement/1.18.0/config-management-operator.yaml
  pkg/api/configsync/register.go
  pkg/kinds/kinds.go
Labels: size/XXL, lgtm, approved

#1262 test: remove flaky `TestBackoffReimportCount`
  pkg/parse/run_test.go
Labels: needs-ok-to-test, lgtm, size/S, approved

#1264 Use default timeout for metric value check
  e2e/testcases/otel_collector_test.go
Labels: size/XS, lgtm, approved

#1265 test: add actual value to metrics validation errs
  e2e/testcases/otel_collector_test.go
Labels: lgtm, size/S, approved

#1267 ci: omit nomos migrate output from test logs
  cmd/junit-report/resetfailure/reset_failure.go
  e2e/testcases/cli_test.go
  scripts/e2e.sh
Labels: lgtm, size/S, approved

#1245 test: adds cleanup logic to remove fake finalizer
  e2e/nomostest/clean.go
Labels: lgtm, size/S, approved

#1268 test: Only check declared_resources metric
  e2e/testcases/otel_collector_test.go
Labels: lgtm, size/S, approved

#1270 chore: Bump otelcontribcol to 0.102.0-gke.4
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1271 chore: Bump otelcontribcol to 0.102.0-gke.4 (#1270)
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1254 [metric] Reset declared_resource to 0 when commit updates with test fix (#1232)
  e2e/testcases/otel_collector_test.go
  pkg/declared/resources.go
Labels: size/L, lgtm, approved

#1274 Dedupe management conflict errors
  pkg/applier/management_conflict_err.go
  pkg/parse/namespace.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/sync_status_cache.go
  pkg/parse/updater.go
  pkg/reconciler/reconciler.go
  pkg/remediator/remediator.go
  pkg/status/management_conflict_error.go
Labels: size/L, lgtm, approved

#1275 fix: only use local config if file exists
  pkg/client/restconfig/config.go
  pkg/client/restconfig/restconfig.go
  pkg/client/restconfig/restconfig_test.go
Labels: size/M, lgtm, approved

#1277 test: clean up ConfigManagement in e2e test
  e2e/testcases/cli_test.go
Labels: size/M, lgtm, approved

#1278 chore: bump golang to 1.21.11
  Makefile
Labels: size/XS, lgtm, approved

#1279 refactor: parametrize git-sync and otel version
  Makefile
  Makefile.build
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: lgtm, size/S, approved

#1280 e2e: update hydration tests to watch for errors
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/hydration_test.go
Labels: size/M, lgtm, approved

#1281 chore: bump git-sync to v4.2.1-gke.12
  Makefile
Labels: size/XS, lgtm, approved

#1282 cleanup: remove unused methods from remediator
  pkg/remediator/fake/remediator.go
  pkg/remediator/remediator.go
Labels: lgtm, size/S, approved

#1283 fix: remediator error reporting after new commit
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/run.go
  pkg/parse/updater.go
  pkg/remediator/fake/remediator.go
  pkg/remediator/remediator.go
  pkg/remediator/watch/manager.go
Labels: size/L, lgtm, approved

#1284 chore: bump helm to v3.14.4-gke.2
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#1285 chore: bump kustomize to v5.4.2-gke.0
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#1286 Revert "fix: multiple sync status update bugs (#1283)"
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/run.go
  pkg/parse/updater.go
  pkg/remediator/fake/remediator.go
  pkg/remediator/remediator.go
  pkg/remediator/watch/manager.go
Labels: size/L, lgtm, approved

#1287 e2e: cleanup hydration tests
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/hydration_test.go
Labels: size/L, lgtm, approved

#1289 refactor: use SourceType type in RSync spec
  cmd/hydration-controller/main.go
  cmd/nomos/status/cluster_state.go
  cmd/nomos/status/cluster_state_test.go
  cmd/reconciler/main.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/sync.go
  e2e/testcases/cli_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/workload_identity_test.go
  pkg/api/configsync/register.go
  pkg/api/configsync/v1alpha1/reposync_types.go
  pkg/api/configsync/v1alpha1/rootsync_types.go
  pkg/api/configsync/v1alpha1/sync_types.go
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/reposync_types.go
  pkg/api/configsync/v1beta1/rootsync_types.go
  pkg/api/configsync/v1beta1/sync_types.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/hydrate/controller.go
  pkg/hydrate/controller_test.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run_test.go
  pkg/parse/source.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/controllers/helm_value_files.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/secret_test.go
  pkg/reconcilermanager/controllers/util.go
  pkg/reconcilermanager/controllers/validate_secret_test.go
  pkg/reconcilermanager/controllers/volumes.go
  pkg/testing/fake/reposync.go
  pkg/testing/fake/rootsync.go
  pkg/validate/raw/validate/repo_sync_validator.go
  pkg/validate/raw/validate/root_sync_validator.go
  pkg/validate/raw/validate/source_spec_validator.go
  pkg/validate/raw/validate/source_spec_validator_test.go
  pkg/validate/validate_test.go
Labels: lgtm, approved, size/XL

#1291 test: wait for ACM operator to become ready
  e2e/testcases/cli_test.go
Labels: size/M, lgtm, approved

#1292 refactor: use SourceFormat in RSync spec
  cmd/nomos/flags/flags.go
  cmd/nomos/hydrate/hydrate.go
  cmd/nomos/migrate/migrate.go
  cmd/nomos/vet/vet.go
  cmd/nomos/vet/vet_impl.go
  cmd/nomos/vet/vet_test.go
  cmd/reconciler/main.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/gitproviders/repository.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/nomostest/reset.go
  e2e/testcases/cli_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/stress_test.go
  pkg/api/configsync/register.go
  pkg/api/configsync/v1alpha1/reposync_types.go
  pkg/api/configsync/v1alpha1/rootsync_types.go
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
  pkg/api/configsync/v1beta1/reposync_types.go
  pkg/api/configsync/v1beta1/rootsync_types.go
  pkg/hydrate/for_each_cluster.go
  pkg/hydrate/tool_util.go
  pkg/importer/analyzer/transform/selectors/namespace_selectors.go
  pkg/importer/filesystem/config_parser.go
  pkg/importer/filesystem/fake/config_parser.go
  pkg/importer/filesystem/parser.go
  pkg/importer/filesystem/source_format.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run_test.go
  pkg/parse/source_test.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/controllers/util.go
Labels: size/L, lgtm, approved

#1288 test: increase helm-sync memory for TestPublicHelm
  e2e/testcases/helm_sync_test.go
  e2e/testdata/root-sync-helm-chart-cr.yaml
Labels: size/L, lgtm, approved

#1293 chore: bump otelcontribcol to v0.102.0-gke.5
  Makefile
Labels: size/XS, lgtm, approved

#1290 fix: multiple status update bugs
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run.go
  pkg/parse/updater.go
  pkg/remediator/fake/remediator.go
  pkg/remediator/remediator.go
  pkg/remediator/watch/manager.go
Labels: size/L, lgtm, approved

#1294 test: clean up root reconciler ClusterRoleBindings
  e2e/nomostest/clean.go
Labels: size/M, lgtm, approved

#1295 chore: bump git-sync to v4.2.3-gke.2__linux_amd64
  Makefile
Labels: size/XS, lgtm, approved

#1296 Refactor reconciler status caching
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/state.go
  pkg/parse/status.go
Labels: size/L, lgtm, approved

#1298 feat: error backoff for oci-sync
  cmd/helm-sync/main.go
  cmd/oci-sync/main.go
  pkg/parse/state.go
  pkg/util/retry.go
Labels: size/M, lgtm, approved
