Repository GoogleContainerTools/config-sync, pull requests merged in 2024-02, with the labels that each got.

#1120 test: fix test failures caused by sub tests running in parallel
  e2e/nomostest/client.go
  e2e/testcases/workload_identity_test.go
Labels: size/XS, lgtm, approved

#1121 feature: add BYOID support for OCI artifacts and Helm charts
  cmd/helm-sync/main.go
  cmd/oci-sync/main.go
  e2e/nomostest/nt.go
  e2e/nomostest/testing/env.go
  e2e/nomostest/testutils/fleet_membership.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/workload_identity_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/register.go
  pkg/api/configsync/v1alpha1/helmconfig.go
  pkg/api/configsync/v1alpha1/ociconfig.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/api/configsync/v1beta1/ociconfig.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/helm/helm.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/util.go
  pkg/validate/raw/validate/source_spec_validator.go
Labels: lgtm, approved, size/XL

#1117 Aggregate kustomize metrics labels
  e2e/testcases/otel_collector_test.go
  e2e/testdata/otel-collector/otel-cm-kustomize-rejected-labels.yaml
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: size/L, lgtm, approved

#1125 chore: bump git-sync and debian-base images
  Makefile
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#1127 Add required IAM settings for the test infra
  e2e/testinfra/terraform/common/service_accounts.tf
  e2e/testinfra/terraform/prow/service_accounts.tf
Labels: lgtm, size/S, approved

#1130 fix: use google-cloud-cli package instead of sdk
  build/prow/e2e/Dockerfile
Labels: size/XS, lgtm, approved

#1131 fix: use google-cloud-cli package instead of sdk (#1130)
  build/prow/e2e/Dockerfile
Labels: size/XS, lgtm, approved, tide/merge-method-rebase

#1116 fix: get AR authenticator with retries
  cmd/oci-sync/main.go
  pkg/oci/fetcher.go
Labels: size/M, lgtm, approved

#1132 [chore] Update otel-collector for CVE fix
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1133 [chore] Update otel-collector for CVE fix (#1132)
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved, tide/merge-method-rebase

#1134 fix: enable user output for version list (#1084)
  e2e/testcases/helm_sync_test.go
Labels: size/XS, lgtm, approved

#1135 test: fix test failures with invalid image digest
  e2e/testcases/workload_identity_test.go
Labels: lgtm, size/S, approved

#1137 test: move the fake test finalizer removal function into a cleanup b lock (#1106)
  e2e/testcases/reconciler_finalizer_test.go
Labels: size/M, lgtm, approved

#1138 test: refactor helm provider to not depend on gitproviders
  e2e/nomostest/config_sync.go
  e2e/nomostest/gitproviders/repository.go
  e2e/nomostest/ntopts/new.go
  e2e/nomostest/registry_server.go
  e2e/nomostest/registryproviders/helm.go
  e2e/nomostest/registryproviders/image.go
  e2e/nomostest/testkubeclient/object.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/workload_identity_test.go
Labels: lgtm, approved, size/XL

#1136 fix: use more limited securityContext for pods
  manifests/templates/admission-webhook.yaml
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/M, lgtm, approved

#1139 test: prevent eviction of test pods
  e2e/nomostest/git-server.go
  e2e/nomostest/registry_server.go
  e2e/testdata/prometheus/prometheus.yaml
Labels: lgtm, size/S, approved

#1140 fix: stop validating root secrets
  pkg/reconcilermanager/controllers/rootsync_controller.go
Labels: lgtm, size/S, approved

#1141 chore: Add subnets in us-central2
  e2e/testinfra/terraform/prow/networks.tf
Labels: size/M, lgtm, approved

#1143 chore: replace e2e region usc2 with usw1
  e2e/testinfra/terraform/prow/networks.tf
Labels: size/M, lgtm, approved

#1144 test: rename test-e2e-kind targets and dev docs
  Makefile.e2e
  docs/testing.md
Labels: size/M, lgtm, approved

#1145 chore: update the base image of the test-git-server
  Makefile.build
Labels: size/XS, lgtm, approved

#1148 e2e: Add registry login/logout to test setup
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/nomostest/ntopts/new.go
  e2e/nomostest/registry_server.go
  e2e/nomostest/registryproviders/artifact_registry.go
  e2e/nomostest/registryproviders/local.go
  e2e/nomostest/registryproviders/registry_provider.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/stress_test.go
Labels: size/L, lgtm, approved

#1146 test: add a test to confirm the git-sync not pulling latest issue
  e2e/nomostest/git-server.go
  e2e/testcases/git_sync_test.go
Labels: size/M, lgtm, approved

#1147 fix: update git-sync to v4.2.1 to fix a pulling issue
  Makefile
  e2e/testcases/git_sync_test.go
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/M, lgtm, approved

#1150 fix: stop validating root secrets (#1140)
  pkg/reconcilermanager/controllers/rootsync_controller.go
Labels: lgtm, size/S, approved

#1154 test: update e2e test to fix gitlab push error (#1153)
  e2e/testcases/git_sync_test.go
Labels: size/XS, lgtm, approved
