Repository GoogleContainerTools/config-sync, pull requests merged in 2024-10, with the labels that each got.

#1445 test: fix flaky controller-manager tests
  pkg/reconcilermanager/controllers/reposync_controller_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
Labels: size/M, lgtm, approved

#1446 chore: cleanup some logs
  pkg/parse/updater.go
  pkg/reconciler/finalizer/base_finalizer.go
  pkg/remediator/conflict/handler.go
  pkg/remediator/reconcile/reconciler.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/manager.go
  pkg/resourcegroup/controllers/watch/manager.go
Labels: size/M, lgtm, approved

#1447 chore: remove ClearManagementConflictsWithKind
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/manager.go
Labels: lgtm, size/S, approved

#1448 ci fix: updated to the new bitbucket ws
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/XS, lgtm, approved

#1449 cherry-pick: ci fix: updated to the new bitbucket ws (#1448)
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/XS, lgtm, approved

#1450 chore: share mapper between controllers
  cmd/reconciler-manager/main.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/controllers/crd_controller.go
  pkg/remediator/remediator.go
  pkg/remediator/watch/listwatch.go
  pkg/remediator/watch/manager.go
  pkg/remediator/watch/manager_test.go
  pkg/remediator/watch/watcher.go
  pkg/util/watch/mapper.go
Labels: size/L, lgtm, approved

#1454 feat: stall nomos migrate if HNC is enabled
  cmd/nomos/migrate/configmanagement.go
  cmd/nomos/util/configmanagement.go
  e2e/testcases/cli_test.go
Labels: size/M, lgtm, approved

#1453 feat: add bash script for uninstalling ACM
  build/prow/e2e/Dockerfile.dockerignore
  e2e/testcases/cli_test.go
  installation/uninstall_configmanagement.sh
Labels: size/L, lgtm, approved

#1456 PR feedback follow up for manual install
  e2e/testcases/cli_test.go
  e2e/testdata/configmanagement/uninstall/uninstall_configmanagement.sh
  installation/README.md
Labels: size/M, lgtm, approved

#1457 ci: add tooling to package kustomization bundle
  Makefile.build
Labels: lgtm, size/S, approved

#1459 Update description of admission-webhook in install
  installation/kustomization.yaml
Labels: size/XS, lgtm, approved

#1452 Feature: support OCI signature verification by setting the `configsync.gke.io/image-to-sync` annotation in RSync
  Makefile.build
  build/prow/e2e/Dockerfile
  e2e/nomostest/nt.go
  e2e/nomostest/oci-image-verification-server.go
  e2e/nomostest/registryproviders/oci_image.go
  e2e/nomostest/registryproviders/registry_provider.go
  e2e/nomostest/reset.go
  e2e/nomostest/ssh.go
  e2e/nomostest/testshell/shell.go
  e2e/testcases/oci_signature_verification_test.go
  e2e/testinfra/terraform/modules/service_account/service_account.tf
  pkg/metadata/annotations.go
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/run.go
  test/docker/presync-webhook-server/Dockerfile
  test/docker/presync-webhook-server/go.mod
  test/docker/presync-webhook-server/go.sum
  test/docker/presync-webhook-server/oci-signature-verification-server.go
Labels: size/XXL, lgtm, approved

#1462 Add Cosign to e2e image
  build/prow/e2e/Dockerfile
Labels: size/XS, lgtm, approved

#1461 chore: Extract Reconciler from Parser
  pkg/declared/resources.go
  pkg/parse/event_handler.go
  pkg/parse/opts.go
  pkg/parse/parser.go
  pkg/parse/reconciler.go
  pkg/parse/repo_sync_client.go
  pkg/parse/repo_sync_parser.go
  pkg/parse/root_reconciler_test.go
  pkg/parse/root_sync_client.go
  pkg/parse/root_sync_client_test.go
  pkg/parse/root_sync_parser.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/source_test.go
  pkg/parse/state.go
  pkg/parse/sync_status_client.go
  pkg/parse/updater.go
  pkg/reconciler/reconciler.go
Labels: size/XXL, lgtm, approved

#1463 Add cosign to test image dependency
  Makefile
  Makefile.e2e
  build/prow/e2e/Dockerfile
Labels: lgtm, size/S, approved

#1464 e2e: Only create registry secret when using local registry provider
  e2e/nomostest/oci-image-verification-server.go
Labels: lgtm, size/S, approved

#1467 Add authentication step to Terraform setup guide
  e2e/testinfra/terraform/README.md
Labels: size/XS, lgtm, approved

#1471 Use placeholder for git-sync and otelcontribcol image versions
  Makefile
  test/kustomization/expected.yaml
Labels: lgtm, size/S, approved

#1469 Switch to use the OSS git-sync with githubapp support
  Makefile
Labels: size/XS, lgtm, approved
