Repository GoogleContainerTools/config-sync, pull requests merged in 2024-08, with the labels that each got.

#1370 fix: treat IsNotFound as conflict on Create
  pkg/syncer/client/client.go
  pkg/syncer/client/client_test.go
  pkg/syncer/reconcile/apply.go
Labels: lgtm, size/S, approved

#1374 added security.md
  SECURITY.md
Labels: size/XS, lgtm, approved

#1373 Bump Helm version to v3.15.3-gke.0
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#1376 Revert "Bump otelcontribcol version to v0.106.0-gke.2 (#1369)"
  Makefile
  manifests/base/kustomization.yaml
  manifests/otel-agent-cm.yaml
  manifests/otel-agent-reconciler-cm.yaml
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/L, lgtm, approved

#1378 Update otelcontribcol to v0.103.0-gke.3
  Makefile
Labels: size/XS, lgtm, approved

#1379 test: update test expectations for autopilot bursting
  e2e/nomostest/clusterversion/cluster_version.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/reconciler_manager_test.go
Labels: size/L, lgtm, approved

#1375 fix: conflict metric on watched resource not found
  pkg/parse/updater.go
  pkg/remediator/fake/remediator.go
  pkg/remediator/remediator.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/manager.go
  pkg/remediator/watch/manager_test.go
  pkg/remediator/watch/watcher.go
Labels: size/L, lgtm, approved

#1382 test: fix autopilot bursting check
  e2e/nomostest/nt.go
Labels: size/XS, lgtm, approved

#1383 test: fix reset enabling deletion propagation after update
  e2e/nomostest/reset.go
  e2e/testcases/helm_sync_test.go
Labels: lgtm, size/S, approved

#1381 Align otel-agent feature gate in resource group controller
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1385 e2e: refactor validateNumberOfObjectsEquals
  e2e/testcases/stress_test.go
Labels: size/M, lgtm, approved

#1387 Bump github.com/docker/docker to fix vulnerability
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, needs-ok-to-test, lgtm, approved

#1386 test: fix cluster version comparison
  e2e/nomostest/clean.go
  e2e/nomostest/clusterversion/cluster_version.go
  e2e/nomostest/clusterversion/cluster_version_test.go
  e2e/nomostest/nt.go
Labels: size/L, lgtm, approved

#1384 Add profiling tests and watch filtering doc
  docs/watch-filtering/README.md
  docs/watch-filtering/scenario-a-results.png
  docs/watch-filtering/scenario-a-v1.18.3.png
  docs/watch-filtering/scenario-a-v1.19.0.png
  docs/watch-filtering/scenario-b-results.png
  docs/watch-filtering/scenario-b-v1.18.3.png
  docs/watch-filtering/scenario-b-v1.19.0.png
  docs/watch-filtering/scenario-c-results.png
  docs/watch-filtering/scenario-c-v1.18.3.png
  docs/watch-filtering/scenario-c-v1.19.0.png
  e2e/flags.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/new.go
  e2e/nomostest/ntopts/test_type.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/main_test.go
  e2e/testcases/profiling_test.go
  e2e/testcases/resource_group_controller_test.go
  e2e/testcases/stress_test.go
Labels: lgtm, approved, size/XL

#1392 test: delete GAR repositories on teardown
  e2e/nomostest/registryproviders/artifact_registry.go
Labels: lgtm, size/S, approved

#1371 refactor: WaitForRootSyncStalledError ns arg
  e2e/nomostest/config_sync.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/proxy_test.go
  e2e/testcases/reconciler_manager_test.go
Labels: size/M, lgtm, approved

#1394 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS, ok-to-test, lgtm, approved

#1396 e2e: simplify RSync test setup
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/nomostest/prometheus_metrics.go
  e2e/nomostest/syncsource/syncsource.go
  e2e/testcases/admission_test.go
  e2e/testcases/cli_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/composition_test.go
  e2e/testcases/gcenode_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespace_strategy_test.go
  e2e/testcases/no_ssl_verify_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_log_level_test.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/override_role_refs_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/ssh_known_hosts_test.go
  e2e/testcases/workload_identity_test.go
  pkg/core/id.go
Labels: size/L, lgtm, approved

#1398 e2e: add options to SyncWithGitSource
  e2e/nomostest/gitproviders/repository.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/nomostest/reset.go
  e2e/nomostest/syncsource/syncsource.go
  e2e/testcases/acme_test.go
  e2e/testcases/apiservice_test.go
  e2e/testcases/cli_test.go
  e2e/testcases/composition_test.go
  e2e/testcases/declared_fields_test.go
  e2e/testcases/gatekeeper_test.go
  e2e/testcases/gcenode_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespace_selectors_test.go
  e2e/testcases/namespace_strategy_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/otel_collector_test.go
  e2e/testcases/override_log_level_test.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testcases/override_role_refs_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/profiling_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/root_sync_test.go
  e2e/testcases/ssh_known_hosts_test.go
  e2e/testcases/status_enablement_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/sync_ordering_test.go
  e2e/testcases/workload_identity_test.go
Labels: size/L, lgtm, approved

#1401 test: improve runtime of TestDependencyWithReconciliation
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/sync_ordering_test.go
Labels: lgtm, size/S, approved

#1404 chore: clean up unused wait test helpers
  e2e/nomostest/wait_for_sync.go
Labels: size/M, lgtm, approved

#1405 chore: bump golangci-lint to 1.60.3
  Makefile
  cmd/nomos/migrate/migrate.go
  cmd/nomos/version/version_test.go
  e2e/nomostest/portforwarder/port_forwarder.go
  e2e/testcases/cli_test.go
  pkg/declared/resources_test.go
  pkg/diff/diff_test.go
  pkg/kmetrics/exec.go
  pkg/parse/annotations_test.go
  pkg/parse/root_test.go
  pkg/remediator/queue/deleted_test.go
  pkg/resourcegroup/controllers/status/status.go
  pkg/validate/scoped/hydrate/namespace_hydrator.go
  pkg/validate/validate_test.go
Labels: size/M, lgtm, approved

#1403 test: reduce polling periods for e2e tests
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/testcases/managed_resources_test.go
Labels: size/M, lgtm, approved

#1407 chore: rebalance e2e test groups
  Makefile.e2e
Labels: size/XS, lgtm, approved

#1406 e2e: Add SyncSource.Path
  e2e/nomostest/config_sync.go
  e2e/nomostest/config_sync_sources.go
  e2e/nomostest/git-server.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/nomostest/registryproviders/artifact_registry.go
  e2e/nomostest/registryproviders/local.go
  e2e/nomostest/registryproviders/oci_image.go
  e2e/nomostest/registryproviders/registry_provider.go
  e2e/nomostest/sync.go
  e2e/nomostest/syncsource/syncsource.go
  e2e/nomostest/testing/env.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/cli_test.go
  e2e/testcases/composition_test.go
  e2e/testcases/gcenode_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/kcc_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/otel_collector_test.go
  e2e/testcases/override_log_level_test.go
  e2e/testcases/policy_dir_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/profiling_test.go
  e2e/testcases/proxy_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/root_sync_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/workload_identity_test.go
  pkg/core/id.go
  pkg/kinds/lookup.go
  pkg/syncer/syncertest/fake/common.go
  pkg/syncer/syncertest/fake/storage.go
  pkg/syncer/syncertest/fake/subresource_storage.go
Labels: size/XXL, lgtm, approved

#1372 feat: add github app auth to git-sync api
  Makefile
  e2e/flags.go
  e2e/nomostest/gitproviders/bitbucket.go
  e2e/nomostest/gitproviders/github.go
  e2e/nomostest/ntopts/new.go
  e2e/nomostest/ntopts/test_type.go
  e2e/testcases/github_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/register.go
  pkg/api/configsync/v1alpha1/gitconfig.go
  pkg/api/configsync/v1beta1/gitconfig.go
  pkg/reconcilermanager/controllers/constants.go
  pkg/reconcilermanager/controllers/gitsync_env.go
  pkg/reconcilermanager/controllers/gitsync_env_test.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/validate_secret.go
  pkg/reconcilermanager/controllers/validate_secret_test.go
  pkg/validate/raw/validate/source_spec_validator.go
Labels: size/XXL, lgtm, approved

#1412 test: fix logic to create ca certs when git=csr
  e2e/nomostest/config_sync.go
  e2e/nomostest/ssh.go
  e2e/testcases/composition_test.go
  e2e/testcases/reconciler_manager_test.go
Labels: size/M, lgtm, approved

#1414 e2e: Add SetRSyncTestDefaults
  e2e/nomostest/config_sync.go
Labels: size/L, lgtm, approved

#1415 [cherry-pick] test: fix logic to create ca certs when git=csr (#1412)
  e2e/nomostest/config_sync.go
  e2e/nomostest/ssh.go
  e2e/testcases/composition_test.go
  e2e/testcases/reconciler_manager_test.go
Labels: size/M, lgtm, approved

#1413 e2e: Add ReadOnlyRepository
  e2e/nomostest/config_sync.go
  e2e/nomostest/config_sync_sources.go
  e2e/nomostest/gitproviders/repository.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/reset.go
  e2e/nomostest/syncsource/syncsource.go
  e2e/testcases/acme_test.go
  e2e/testcases/admission_test.go
  e2e/testcases/adopt_client_side_applied_test.go
  e2e/testcases/apiservice_test.go
  e2e/testcases/basic_test.go
  e2e/testcases/cli_test.go
  e2e/testcases/cluster_resources_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/composition_test.go
  e2e/testcases/custom_resource_definitions_schema_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/declared_fields_test.go
  e2e/testcases/gatekeeper_test.go
  e2e/testcases/gcenode_test.go
  e2e/testcases/git_sync_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/invalid_auth_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/kptfile_test.go
  e2e/testcases/lifecycle_directives_test.go
  e2e/testcases/local_config_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/multiversion_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespace_selectors_test.go
  e2e/testcases/namespace_strategy_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/no_ssl_verify_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/otel_collector_test.go
  e2e/testcases/override_git_sync_depth_test.go
  e2e/testcases/override_log_level_test.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testcases/override_resource_limits_test.go
  e2e/testcases/override_role_refs_test.go
  e2e/testcases/policy_dir_test.go
  e2e/testcases/preserve_fields_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/profiling_test.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/remediator_test.go
  e2e/testcases/resource_group_controller_test.go
  e2e/testcases/root_sync_test.go
  e2e/testcases/ssh_known_hosts_test.go
  e2e/testcases/status_enablement_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/sync_ordering_test.go
  e2e/testcases/workload_identity_test.go
Labels: lgtm, approved, size/XL

#1416 e2e: Clean up TestControllerValidationErrors
  e2e/nomostest/clean.go
  e2e/nomostest/config_sync.go
  e2e/testcases/multi_sync_test.go
Labels: size/L, lgtm, approved
