Repository GoogleContainerTools/config-sync, pull requests merged in 2024-01, with the labels that each got.

#1092 chore: bump manifest headers to 2024
  manifests/cluster-selector-crd.yaml
  manifests/hierarchyconfig-crd.yaml
  manifests/namespace-selector-crd.yaml
  manifests/reposync-crd.yaml
  manifests/resourcegroup-crd.yaml
  manifests/rootsync-crd.yaml
Labels: lgtm, size/S, approved

#1094 Update git-sync version to fix CVEs
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#1091 fix: Add 5m buffer time to askpass
  pkg/askpass/askpass.go
  pkg/askpass/askpass_test.go
Labels: lgtm, size/S, approved

#1093 chore: ignore self-assignment lint for validation
  scripts/install-helm.sh
  scripts/install-kustomize.sh
Labels: size/XS, lgtm, approved

#1097 v1.17 cherry-pick: chore: bump manifest headers to 2024 (#1092)
  manifests/cluster-selector-crd.yaml
  manifests/hierarchyconfig-crd.yaml
  manifests/namespace-selector-crd.yaml
  manifests/reposync-crd.yaml
  manifests/resourcegroup-crd.yaml
  manifests/rootsync-crd.yaml
Labels: lgtm, size/S, approved

#1098 Update debian bookworm image
  Makefile
Labels: size/XS, lgtm, approved

#1099 chore: update golang image to debian bookworm
  Makefile
Labels: size/XS, lgtm, approved

#1101 Remove the `webhooks` field from the validatingwebhookconfigurations object
  manifests/templates/admission-webhook.yaml
Labels: size/XS, lgtm, approved

#1102 fix: reverse log level ordering for zap/otel-agent
  e2e/testcases/override_log_level_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/resource_override.go
  pkg/api/configsync/v1beta1/resource_override.go
  pkg/reconcilermanager/controllers/reconciler_container_log_level.go
  pkg/reconcilermanager/controllers/reconciler_container_log_level_test.go
Labels: size/L, lgtm, approved

#1105 Increase the default memory/cpu requests for helm-sync on Autopilot clusters
  pkg/reconcilermanager/controllers/reconciler_container_resources.go
Labels: size/XS, lgtm, approved

#1106 test: move the fake test finalizer removal function into a cleanup block
  e2e/testcases/reconciler_finalizer_test.go
Labels: size/M, lgtm, approved

#1107 ci: set CGO_ENABLED=0 for local crane binary
  Makefile
Labels: size/XS, lgtm, approved

#1109 refactor: rename test opt to RequireLocalGitProvider
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/ssh_known_hosts_test.go
Labels: lgtm, size/S, approved

#1104 feat: add CA cert support for oci-sync
  e2e/flags.go
  e2e/nomostest/git-server.go
  e2e/nomostest/gitproviders/repository.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/nomostest/registry_server.go
  e2e/nomostest/registryproviders/image.go
  e2e/nomostest/registryproviders/local.go
  e2e/nomostest/registryproviders/registry_provider.go
  e2e/nomostest/reset.go
  e2e/nomostest/ssh.go
  e2e/testcases/private_cert_secret_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/gitconfig.go
  pkg/api/configsync/v1alpha1/ociconfig.go
  pkg/api/configsync/v1alpha1/zz_generated.deepcopy.go
  pkg/api/configsync/v1beta1/gitconfig.go
  pkg/api/configsync/v1beta1/ociconfig.go
  pkg/api/configsync/v1beta1/zz_generated.deepcopy.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/util.go
  pkg/reconcilermanager/controllers/util_test.go
Labels: size/XXL, lgtm, approved

#1112 Fix sample dashboard metric resource type
  dashboard/cloud_monitoring_dashboard.json
Labels: lgtm, size/S, approved

#1111 feat: add CA cert support for helm-sync
  cmd/helm-sync/main.go
  e2e/flags.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/nomostest/registry_server.go
  e2e/nomostest/registryproviders/helm.go
  e2e/nomostest/registryproviders/local.go
  e2e/nomostest/registryproviders/registry_provider.go
  e2e/testcases/private_cert_secret_test.go
  manifests/reposync-crd.yaml
  manifests/rootsync-crd.yaml
  pkg/api/configsync/v1alpha1/helmconfig.go
  pkg/api/configsync/v1beta1/helmconfig.go
  pkg/helm/helm.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/util.go
  pkg/reconcilermanager/controllers/util_test.go
Labels: lgtm, approved, size/XL

#1114 fix: update the incorrect error messages
  pkg/validate/raw/validate/source_spec_validator.go
Labels: size/M, lgtm, approved

#1118 chore: bump debian base image for security patches
  Makefile
Labels: size/XS, lgtm, approved

#1115 refactor: extracts test utils to a common package
  e2e/nomostest/artifactregistry/image.go
  e2e/nomostest/kustomizecomponents/validate.go
  e2e/nomostest/nt.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/testutils/finalizer.go
  e2e/nomostest/testutils/fleet_membership.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/hydration_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/workload_identity_test.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
Labels: size/XXL, lgtm, approved

#1119 chore: bump git-sync to latest patch
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved
