Repository GoogleContainerTools/config-sync, pull requests merged in 2024-07, with the labels that each got.

#1299 Inject Parser.Clock for testing
  pkg/parse/cache.go
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/source_test.go
  pkg/parse/state.go
  pkg/parse/status.go
  pkg/reconciler/reconciler.go
Labels: size/XXL, lgtm, approved

#1276 Fix sync status lost on reconciler pod replacement
  pkg/parse/cache.go
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run.go
  pkg/parse/source.go
  pkg/parse/source_test.go
  pkg/parse/status.go
Labels: lgtm, approved, size/XL

#1304 Run make in buildenv container by default
  Makefile
Labels: lgtm, size/S, approved

#1307 Update git-sync version for CVE fixes
  Makefile
Labels: size/XS, lgtm, approved

#1310 Cherrypick 1.18.3 for more CVE fixes
  Makefile
Labels: size/XS, lgtm, approved, tide/merge-method-rebase

#1308 Replace lint-license.sh with make lint-license
  Makefile
  scripts/lint-license.sh
Labels: size/M, lgtm, approved

#1312 chore: bump controller-gen to 0.15.0
  Makefile.reconcilermanager
  manifests/cluster-selector-crd.yaml
  manifests/hierarchyconfig-crd.yaml
  manifests/namespace-selector-crd.yaml
  manifests/reposync-crd.yaml
  manifests/resourcegroup-crd.yaml
  manifests/rootsync-crd.yaml
Labels: size/XXL, lgtm, approved

#1309 ci: publish all infra images in postsubmit
  Makefile
  Makefile.build
  Makefile.e2e.ci
  Makefile.oss.prow
Labels: size/M, lgtm, approved

#1311 ci: bump go environment to 1.22
  Makefile
Labels: size/XS, lgtm, approved

#1313 chore: bump Go to 1.22
  go.mod
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/client_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_intermediate_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_leaf_cert.der
  vendor/github.com/google/s2a-go/internal/v2/certverifier/testdata/server_root_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.der
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/remotesigner/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/testdata/server_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/client_key.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/internal/v2/tlsconfigstore/testdata/server_key.pem
  vendor/github.com/google/s2a-go/testdata/client_cert.pem
  vendor/github.com/google/s2a-go/testdata/client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_client_key.pem
  vendor/github.com/google/s2a-go/testdata/mds_root_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_cert.pem
  vendor/github.com/google/s2a-go/testdata/mds_server_key.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_cert.pem
  vendor/github.com/google/s2a-go/testdata/self_signed_key.pem
  vendor/github.com/google/s2a-go/testdata/server_cert.pem
  vendor/github.com/google/s2a-go/testdata/server_key.pem
Labels: lgtm, approved, size/XL

#1314 Add fake.Cache.RemoveInformer
  pkg/syncer/syncertest/fake/cache.go
Labels: size/M, lgtm, approved

#1317 Update staticcheck to test Go 1.22
  .golangci.yaml
Labels: size/XS, lgtm, approved

#1318 Update git-sync to v4.2.3-gke.5__linux_amd64
  Makefile
Labels: size/XS, lgtm, approved

#1316 Update cli-utils to v0.37.2
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/cli-utils/pkg/apply/applier_builder.go
  vendor/sigs.k8s.io/cli-utils/pkg/apply/builder.go
  vendor/sigs.k8s.io/cli-utils/pkg/apply/destroyer_builder.go
  vendor/sigs.k8s.io/cli-utils/pkg/apply/mutator/apply_time_mutator.go
  vendor/sigs.k8s.io/cli-utils/pkg/apply/task/apply_task.go
  vendor/sigs.k8s.io/cli-utils/pkg/jsonpath/jsonpath.go
  vendor/sigs.k8s.io/cli-utils/pkg/kstatus/watcher/default_status_watcher.go
  vendor/sigs.k8s.io/cli-utils/pkg/kstatus/watcher/dynamic_informer_factory.go
  vendor/sigs.k8s.io/cli-utils/pkg/kstatus/watcher/object_status_reporter.go
Labels: size/L, lgtm, approved

#1320 Update git-sync to v4.2.3-gke.5__linux_amd64 (#1318)
  Makefile
Labels: size/XS, lgtm, approved

#1319 Update golangci-lint to v1.59.1
  Makefile
  cmd/nomos/status/cluster_state.go
  cmd/nomos/util/util.go
  cmd/nomos/version/version.go
  pkg/applier/status.go
  pkg/util/env.go
  pkg/util/log/error.go
Labels: size/M, lgtm, approved

#1324 cherry-pick: test: increase helm-sync memory for TestPublicHelm (#1288)
  e2e/testcases/helm_sync_test.go
  e2e/testdata/root-sync-helm-chart-cr.yaml
Labels: size/L, lgtm, approved

#1325 Bump otel-collector image to fix CVEs
  Makefile
Labels: size/XS, lgtm, approved

#1327 cherrypick: Bump otel-collector image to fix CVEs (#1325)
  Makefile
Labels: size/XS, lgtm, approved

#1322 feat: allow nomos migrate to continue on error
  cmd/nomos/migrate/migrate.go
Labels: size/XS, lgtm, approved

#1323 cherry-pick: e2e: attempt to uninstall packages in cleanup (#1231)
  e2e/nomostest/clean.go
  e2e/nomostest/testpredicates/predicates.go
Labels: size/L, lgtm, approved

#1328 Remediate watch filter label removal
  pkg/remediator/reconcile/worker.go
  pkg/remediator/reconcile/worker_test.go
Labels: size/L, lgtm, approved

#1330 feat: add --version flag to nomos CLI
  cmd/nomos/nomos.go
Labels: lgtm, size/S, approved

#1333 ci: publish operator manifest on postsubmit
  Makefile.e2e.ci
Labels: lgtm, size/S, approved

#1331 ci: fix go lint deprecated field
  .golangci.yaml
Labels: size/XS, lgtm, approved

#1336 ci: sideload dockerhub images into kind
  Makefile
  e2e/nomostest/clusters/kind.go
  e2e/nomostest/prometheus.go
  e2e/nomostest/registry_server.go
  e2e/nomostest/testing/env.go
  e2e/testdata/prometheus/prometheus.yaml
Labels: lgtm, approved, size/XL

#1329 feat: filter contexts before creating rest configs
  cmd/nomos/status/client.go
  cmd/nomos/version/version.go
  cmd/nomos/version/version_test.go
  pkg/bugreport/bugreport.go
  pkg/client/restconfig/config.go
  pkg/client/restconfig/config_test.go
Labels: size/L, lgtm, approved

#1332 feat: only sync once for oci image with digest
  cmd/oci-sync/main.go
  e2e/testcases/oci_sync_test.go
  pkg/oci/fetcher.go
  pkg/oci/fetcher_test.go
Labels: size/L, lgtm, approved

#1335 Fix remediator to catch conflicts during apply
  pkg/parse/updater.go
  pkg/remediator/fake/remediator.go
  pkg/remediator/remediator.go
  pkg/remediator/watch/listwatch.go
  pkg/remediator/watch/manager.go
  pkg/remediator/watch/manager_test.go
Labels: size/L, lgtm, approved

#1338 e2e: export kind logs on failure or debug
  e2e/nomostest/clusters/kind.go
Labels: size/XS, lgtm, approved

#1337 ci: sideload dockerhub images into kind (#1336)
  Makefile
  e2e/nomostest/clusters/kind.go
  e2e/nomostest/prometheus.go
  e2e/nomostest/registry_server.go
  e2e/nomostest/testing/env.go
  e2e/testdata/prometheus/prometheus.yaml
Labels: lgtm, approved, size/XL

#1343 e2e: watch Role during RootToRoot conflict test
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/multi_sync_test.go
Labels: size/M, lgtm, approved

#1341 test: update kind to use in-memory etcd
  e2e/nomostest/clusters/kind.go
Labels: size/XS, lgtm, approved

#1345 test: add tests for prependRootSyncRemediatorStatus
  pkg/parse/root_test.go
Labels: size/L, lgtm, approved

#1344 Simplify management conflict error
  e2e/testcases/multi_sync_test.go
  pkg/applier/management_conflict_err.go
  pkg/core/decorate.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run.go
  pkg/status/management_conflict_error.go
Labels: size/L, lgtm, approved

#1349 chore: bump k8s patch version
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#1351 fix misspelling on setRenderingStatus function
  pkg/parse/namespace.go
  pkg/parse/root.go
Labels: lgtm, size/S, approved

#1353 feat: remove kube-system from nomos bugreport
  e2e/testcases/cli_test.go
  pkg/bugreport/bugreport.go
Labels: lgtm, size/S, approved

#1352 feat: remove PoCo from nomos bugreport
  e2e/testcases/cli_test.go
  pkg/bugreport/bugreport.go
  pkg/bugreport/constants.go
Labels: lgtm, size/S, approved

#1348 fix: remediator ignores no resource/kind match
  cmd/nomoserrors/examples/examples.go
  e2e/testcases/custom_resources_test.go
  pkg/remediator/reconcile/reconciler_test.go
  pkg/syncer/client/client.go
  pkg/syncer/client/client_test.go
  pkg/syncer/client/retriable_errors.go
  pkg/syncer/reconcile/apply.go
Labels: size/M, lgtm, approved

#1354 fix: RepoSync management conflict reporting
  e2e/testcases/multi_sync_test.go
  pkg/parse/run.go
  pkg/parse/updater.go
  pkg/remediator/conflict/handler.go
  pkg/remediator/remediator.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/manager.go
  pkg/syncer/syncertest/fake/conflict_handler.go
Labels: size/L, lgtm, approved

#1342 fix: remediator management conflict detection
  pkg/remediator/conflict/handler.go
  pkg/remediator/reconcile/reconciler.go
  pkg/remediator/reconcile/reconciler_test.go
  pkg/remediator/reconcile/worker.go
  pkg/remediator/reconcile/worker_test.go
  pkg/remediator/remediator.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/syncer/syncertest/fake/conflict_handler.go
Labels: size/L, lgtm, approved

#1355 test: always override resources for wordpress
  e2e/testcases/helm_sync_test.go
  e2e/testdata/root-sync-helm-chart-version-range-cr.yaml
Labels: size/L, lgtm, approved

#1357 feat: only output yaml in bugreport
  e2e/testcases/cli_test.go
  pkg/bugreport/bugreport.go
Labels: size/M, lgtm, approved

#1356 fix: applier not recording conflict metric
  pkg/parse/run.go
  pkg/parse/sync_status_cache.go
  pkg/parse/updater.go
  pkg/remediator/conflict/handler.go
  pkg/remediator/reconcile/reconciler.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/status/error_builder.go
  pkg/status/management_conflict_error.go
Labels: size/L, lgtm, approved

#1359 test: cleanup monorepo CRDs after migrate test
  e2e/testcases/cli_test.go
Labels: lgtm, size/S, approved

#1360 fix: bugreport logs for resourcegroup and askpass
  e2e/testcases/cli_test.go
  pkg/bugreport/bugreport.go
Labels: lgtm, size/S, approved

#1361 test: also expect askpass for gcpserviceaccount
  e2e/testcases/cli_test.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
Labels: lgtm, size/S, approved

#1301 Add watch filtering by applyset label
  e2e/testcases/managed_resources_test.go
  e2e/testcases/preserve_fields_test.go
  pkg/applier/applier_test.go
  pkg/applier/clientset.go
  pkg/applyset/applyset.go
  pkg/core/decorate.go
  pkg/kinds/resources.go
  pkg/metadata/applyset.go
  pkg/parse/annotations.go
  pkg/parse/annotations_test.go
  pkg/parse/root_test.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/remediator/watch/filteredwatcher_test.go
  pkg/remediator/watch/manager.go
  pkg/remediator/watch/manager_test.go
  pkg/remediator/watch/watcher.go
Labels: size/XXL, lgtm, approved

#1347 test: improve logging for flaky TestCRD test
  e2e/testcases/custom_resources_test.go
Labels: lgtm, size/S, approved

#1364 test: fix logging to print correct line numbers
  e2e/nomostest/new.go
  e2e/nomostest/testing/ntb.go
  e2e/nomostest/testing/wrapper.go
  e2e/nomostest/testlogger/testlogger.go
  e2e/nomostest/wait_for_sync.go
Labels: size/L, lgtm, approved

#1363 clean up stale references to the importer
  pkg/diff/precedence.go
  pkg/diff/precedence_test.go
  pkg/importer/metrics.go
  pkg/importer/reader/parse_file.go
  pkg/webhook/validate_test.go
Labels: size/L, lgtm, approved

#1365 fix: syncer client not handling resource not found
  e2e/testcases/custom_resources_test.go
  pkg/remediator/reconcile/reconciler.go
  pkg/syncer/client/client.go
  pkg/syncer/client/client_test.go
Labels: size/L, lgtm, approved

#1367 docs: fix e2e test docs and add quickstart
  docs/testing.md
Labels: lgtm, size/S, approved

#1366 fix: CRD deletion race not reporting conflict
  pkg/parse/updater.go
  pkg/remediator/watch/manager.go
  pkg/remediator/watch/manager_test.go
  pkg/syncer/client/retriable_errors.go
Labels: size/M, lgtm, approved

#1368 fix: remediator deleting objects after adoption
  pkg/diff/precedence.go
  pkg/diff/precedence_test.go
  pkg/webhook/validate_test.go
Labels: size/M, lgtm, approved
