Repository GoogleContainerTools/config-sync, pull requests merged in 2024-04, with the labels that each got.

#1190 base image update for golang and debian bookworm
  Makefile
Labels: size/XS, lgtm, approved

#1192 fix: only instantiate ValueConverter when webhook is enabled
  pkg/reconciler/reconciler.go
Labels: lgtm, size/S, approved

#1191 Fix a race condition on reconciler finalizer removal
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
  pkg/reconcilermanager/controllers/reconciler_finalizer_handler.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
Labels: size/L, lgtm, approved

#1194 Improvements for the NamespaceSelector dynamic mode
  pkg/parse/root.go
  pkg/reconciler/reconciler.go
  pkg/validate/scoped/hydrate/namespace_hydrator.go
  pkg/validate/scoped/hydrate/namespace_hydrator_test.go
Labels: size/M, lgtm, approved

#1086 Update doc.go
  pkg/reconciler/doc.go
Labels: size/XS, ok-to-test, lgtm, approved

#1197 chore: update debian-base:bookworm image
  Makefile
Labels: size/XS, lgtm, approved

#1200 chore: update git-sync dependency to fix CVEs
  manifests/templates/reconciler-manager-configmap.yaml
Labels: size/XS, lgtm, approved

#1193 Add resource to apply failed events
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespace_strategy_test.go
  e2e/testcases/remediator_test.go
  e2e/testcases/sync_ordering_test.go
  pkg/applier/applier.go
  pkg/applier/applier_err.go
  pkg/applier/applier_test.go
Labels: size/L, ok-to-test, lgtm, approved
