Repository GoogleContainerTools/config-sync, pull requests merged in 2024-03, with the labels that each got.

#1149 test: fix helm client e2e auth
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/registry_server.go
  e2e/nomostest/registryproviders/artifact_registry.go
  e2e/nomostest/registryproviders/helm_chart.go
  e2e/nomostest/registryproviders/local.go
  e2e/nomostest/registryproviders/oci_image.go
  e2e/nomostest/registryproviders/registry_provider.go
  e2e/nomostest/testshell/gcloud.go
  e2e/nomostest/testshell/helm_client.go
  e2e/nomostest/testshell/kubectl.go
  e2e/nomostest/testshell/oci_client.go
  e2e/nomostest/testshell/shell.go
  e2e/testcases/cli_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/workload_identity_test.go
  e2e/testdata/helm-charts/simple/Chart.yaml
Labels: size/XXL, lgtm, approved

#1157 [chore] Update otel-collector for CVE fix
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1158 [chore] Update otel-collector for CVE fix (#1157)
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1156 test: fix registry cleanup to delete images after
  e2e/nomostest/nt.go
  e2e/nomostest/registry_server.go
  e2e/nomostest/registryproviders/artifact_registry.go
  e2e/nomostest/registryproviders/local.go
  e2e/nomostest/registryproviders/registry_provider.go
Labels: size/L, lgtm, approved

#1159 test: fix flake with TestNamespaceRepo
  e2e/testcases/namespace_repo_test.go
Labels: size/XS, lgtm, approved

#1162 ci: tag all infra images with proper prefix
  Makefile
  Makefile.build
  Makefile.e2e.ci
  Makefile.oss.prow
Labels: lgtm, size/S, approved

#1163 fix: build-cli in postsubmit
  Makefile.e2e.ci
Labels: size/XS, lgtm, approved

#1166 chore: bump subcomponent versions
  Makefile
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
  pkg/hydrate/tool_util.go
Labels: lgtm, size/S, approved

#1167 removed ctrl.Log
  cmd/admission-webhook/main.go
  cmd/reconciler-manager/main.go
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
  pkg/resourcegroup/controllers/root/suite_test.go
  pkg/resourcegroup/controllers/runner/run.go
Labels: size/M, lgtm, approved

#1160 Update csr e2e tests to push sources during test
  Makefile.oss.prow
  e2e/flags.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/git-server.go
  e2e/nomostest/gitproviders/cloud_source_repository.go
  e2e/nomostest/gitproviders/cloud_source_repository_test.go
  e2e/nomostest/gitproviders/git-provider.go
  e2e/nomostest/gitproviders/repository.go
  e2e/nomostest/new.go
  e2e/nomostest/ntopts/new.go
  e2e/nomostest/ntopts/test_type.go
  e2e/nomostest/registryproviders/oci_image.go
  e2e/testcases/csr_auth_test.go
  e2e/testcases/gcenode_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/main_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/workload_identity_test.go
  e2e/testinfra/README.md
  scripts/push-test-helm-charts-to-ar.sh
  scripts/push-to-test-csr-repos.sh
Labels: size/XXL, lgtm, approved

#1170 Fix issue with helm not being executable
  scripts/install-helm.sh
Labels: size/XS, ok-to-test, lgtm, approved

#1171 ci: grant test runner CSR admin
  e2e/testinfra/terraform/prow/service_accounts.tf
Labels: size/XS, lgtm, approved

#1172 Log ssh-keygen output on failure
  e2e/nomostest/ssh.go
Labels: lgtm, size/S, approved

#1176 [chore] Bump otelcontribcol version
  manifests/templates/otel-collector.yaml
  manifests/templates/reconciler-manager-configmap.yaml
  manifests/templates/reconciler-manager.yaml
  manifests/templates/resourcegroup-manifest.yaml
Labels: size/XS, lgtm, approved

#1174 test: fix CI failures when running with --git-provider=csr
  e2e/nomostest/config_sync.go
  e2e/nomostest/ssh.go
  e2e/testcases/composition_test.go
  e2e/testcases/git_sync_test.go
  e2e/testcases/invalid_auth_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/proxy_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testinfra/terraform/modules/service_account/service_account.tf
Labels: size/L, lgtm, approved

#1177 test: fix typo in the KSA names
  e2e/testinfra/terraform/modules/service_account/service_account.tf
Labels: size/XS, lgtm, approved

#1175 Add retry with backoff on error to helm-sync
  cmd/helm-sync/main.go
  e2e/nomostest/config_sync.go
Labels: size/M, ok-to-test, lgtm, approved, tide/merge-method-squash

#1161 Add test coverage for RepoSync auth types
  Makefile.oss.prow
  e2e/nomostest/config_sync.go
  e2e/nomostest/kustomizecomponents/validate.go
  e2e/testcases/cli_test.go
  e2e/testcases/gcenode_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/workload_identity_test.go
  e2e/testdata/helm-charts/simple-ns-chart/Chart.yaml
  e2e/testdata/helm-charts/simple-ns-chart/templates/deployment.yaml
  e2e/testdata/helm-charts/simple-ns-chart/values.yaml
  e2e/testdata/hydration/namespace-repo/kustomization.yml
  e2e/testdata/hydration/namespace-repo/test-ns/kustomization.yaml
  e2e/testinfra/terraform/common/service_accounts.tf
  e2e/testinfra/terraform/prow/service_accounts.tf
Labels: lgtm, approved, size/XL

#1179 test: properly skip tests that use test wrapper
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/new.go
  e2e/testcases/cli_test.go
  scripts/e2e.sh
Labels: size/L, lgtm, approved

#1164 Check for AdmissionWebhook during validation
  cmd/reconciler/main.go
  e2e/nomostest/new.go
  e2e/nomostest/webhook.go
  e2e/testcases/admission_test.go
  pkg/parse/namespace.go
  pkg/parse/opts.go
  pkg/parse/root.go
  pkg/parse/root_test.go
  pkg/parse/run.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/reconcilermanager/controllers/util.go
  pkg/testing/fake/admission_webhook.go
  pkg/validate/objects/raw.go
  pkg/validate/raw/raw.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: lgtm, approved, size/XL

#1180 test: set memory request and limit for stress test
  e2e/testcases/stress_test.go
  e2e/testdata/root-sync-crontab-crs.yaml
Labels: size/M, lgtm, approved

#1181 chore: update auto-generated conversion code
  pkg/api/configsync/v1alpha1/zz_generated.conversion.go
Labels: size/XS, lgtm, approved

#1182 test: use a new Bitbucket workspace
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/XS, lgtm, approved

#1178 Remove unused annotation webhook-configuration-update
  pkg/metadata/annotations.go
  pkg/webhook/configuration/update.go
Labels: lgtm, size/S, approved

#1184 test: fix test failures caused by sub tests running in parallel
  e2e/testcases/cli_test.go
Labels: size/XS, lgtm, approved

#1183 test: add the parent directory to the package path
  e2e/testcases/gcenode_test.go
Labels: size/XS, lgtm, approved

#1185 test: add missing IAM bindings for the cross-project Fleet WI
  e2e/testinfra/terraform/prow/service_accounts.tf
Labels: size/M, lgtm, approved

#1186 [chore] Bump Helm to v3.14.3-gke.1
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#1189 [chore] Bump Helm to v3.14.3-gke.2
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved
