Repository GoogleContainerTools/config-sync, pull requests merged in 2024-12, with the labels that each got.

#1502 Improves the flag description of `nomos status`
  cmd/nomos/status/status.go
Labels: lgtm, size/S, approved

#1487 Feature: pause hydration when image verification fails
  cmd/hydration-controller/main.go
  cmd/reconciler/main.go
  manifests/templates/reconciler-manager-configmap.yaml
  pkg/hydrate/controller.go
  pkg/hydrate/controller_test.go
  pkg/parse/run.go
  pkg/parse/run_test.go
  pkg/parse/source.go
  pkg/reconciler/reconciler.go
  test/kustomization/expected.yaml
Labels: size/L, lgtm, approved

#1503 fix: don't log context canceled as an error
  pkg/parse/event_handler.go
  pkg/remediator/reconcile/worker.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/manager.go
  pkg/status/error.go
Labels: lgtm, size/S, approved

#1506 removing vendor folder from ai
  .aiexclude
Labels: size/XS, lgtm, approved

#1507 fix: ignore gcloud operations list warnings
  e2e/nomostest/clusters/gke.go
Labels: size/XS, lgtm, approved

#1508 fix: mutex unlocking in LoggingTokenProvider
  pkg/auth/token_provider.go
Labels: size/XS, lgtm, approved

#1511 test: remove cross-project fleet workload identity tests
  Makefile.oss.prow
  e2e/nomostest/testutils/fleet_membership.go
  e2e/testcases/workload_identity_test.go
  e2e/testinfra/README.md
  e2e/testinfra/terraform/prow/service_accounts.tf
  scripts/set-up-workload-identity-configs.sh
Labels: size/L, lgtm, approved

#1477 fix: the ignore mutation annotation in the applier
  e2e/testcases/ignore_mutation_test.go
  e2e/testcases/managed_resources_test.go
  pkg/applier/applier.go
  pkg/applier/applier_test.go
  pkg/applier/fake/applier.go
  pkg/applier/utils.go
  pkg/applier/utils_test.go
  pkg/declared/resources.go
  pkg/declared/resources_test.go
  pkg/metadata/metadata.go
  pkg/metadata/metadata_test.go
  pkg/parse/root_reconciler_test.go
  pkg/parse/updater.go
  pkg/remediator/reconcile/reconciler.go
  pkg/remediator/reconcile/reconciler_test.go
  pkg/remediator/watch/filteredwatcher.go
  pkg/remediator/watch/filteredwatcher_test.go
  pkg/syncer/reconcile/as_unstructured.go
  pkg/syncer/syncertest/reconcile.go
Labels: size/XXL, lgtm, approved

#1512 test: remove cross-project fleet workload identity tests (#1511)
  Makefile.oss.prow
  e2e/nomostest/testutils/fleet_membership.go
  e2e/testcases/workload_identity_test.go
  e2e/testinfra/README.md
  e2e/testinfra/terraform/prow/service_accounts.tf
  scripts/set-up-workload-identity-configs.sh
Labels: size/L, lgtm, approved

#1486 fix: modify the Remediator to revert Config Sync metadata changes on drift
  e2e/testcases/ignore_mutation_test.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/metadata/metadata.go
  pkg/remediator/reconcile/reconciler.go
  pkg/remediator/reconcile/reconciler_test.go
Labels: size/L, lgtm, approved

#1514 fix: errorCountAfterTruncation=0 not set
  pkg/parse/root_sync_client.go
  pkg/parse/run_test.go
Labels: lgtm, size/S, approved

#1515 Remove nan-yu from the maintainers list
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#310 e2e: Improve rendering status validation
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/hydration_test.go
Labels: size/L, lgtm, approved

#1517 Exclude vendor folder from AI review
  .aiexclude
Labels: size/XS, lgtm, approved

#1519 chore: bump Go version used by build images
  Makefile
Labels: size/XS, lgtm, approved
