Repository GoogleContainerTools/config-sync, pull requests merged in 2025-07, with the labels that each got.

#1772 chore: bump otelcontribcol to v0.118.0-gke.10
  Makefile
Labels: size/XS, lgtm, approved

#1771 chore: bump k8s.io/kubernetes to v1.32.6
  go.mod
  go.sum
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
  vendor/modules.txt
Labels: lgtm, size/S, approved

#1770 ci: Update Bitbucket workspace
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/XS, lgtm, approved

#1775 [cherry-pick] ci: Update Bitbucket workspace (#1770)
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/XS, lgtm, approved

#1778 test: refactor Wait to return error
  e2e/nomostest/config_sync.go
  e2e/nomostest/testutils/fleet_membership.go
  e2e/nomostest/wait.go
  e2e/testcases/acme_test.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/gatekeeper_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/reconciler_manager_test.go
  e2e/testcases/stress_test.go
  e2e/testcases/workload_identity_test.go
Labels: size/L, lgtm, approved

#1781 test: refactor TestAcmeCorpRepo
  e2e/nomostest/wait.go
  e2e/testcases/acme_test.go
Labels: size/L, lgtm, approved

#1782 added agent context files
  .gitignore
Labels: size/XS, lgtm, approved, tide/merge-method-squash

#1785 fix: use write lock for DeleteIgnored
  pkg/declared/resources.go
Labels: size/XS, lgtm, approved

#1783 fix: use intended 1hr backoff cap for oci-sync/helm-sync
  cmd/helm-sync/main.go
  cmd/oci-sync/main.go
  pkg/util/retry.go
  pkg/util/retry_test.go
Labels: size/M, lgtm, approved

#1789 test: fix GetDeploymentPod for failed Pods
  e2e/nomostest/testkubeclient/client.go
Labels: lgtm, size/S, approved

#1796 feat: Add support for proxy with githubapp auth
  e2e/nomostest/config_sync.go
  e2e/testcases/proxy_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/validate/rsync/validate/source_spec_validator.go
  pkg/validate/rsync/validate/source_spec_validator_test.go
Labels: ok-to-test, lgtm, approved, size/XL

#1790 ci: Add TF configs for SSM
  e2e/testinfra/terraform/common/registries.tf
  e2e/testinfra/terraform/common/service_accounts.tf
  e2e/testinfra/terraform/common/services.tf
  e2e/testinfra/terraform/main.tf
  e2e/testinfra/terraform/modules/service_account/service_account.tf
  e2e/testinfra/terraform/modules/service_account/variables.tf
  e2e/testinfra/terraform/prow/service_accounts.tf
Labels: size/M, lgtm, approved

#1803 test: fix SSM credential helper entry to use explicit hostname
  e2e/nomostest/gitproviders/repository.go
  e2e/nomostest/gitproviders/secure_source_manager.go
Labels: size/XS, lgtm, approved

#1804 test: fix tests failing with SSM gitprovider
  e2e/testcases/multi_sync_test.go
  e2e/testcases/reconciler_manager_test.go
Labels: lgtm, size/S, approved
