Repository GoogleContainerTools/config-sync, pull requests merged in 2025-05, with the labels that each got.

#1652 feat: print applier stats in reconciler finalizer
  pkg/reconciler/finalizer/base_finalizer.go
Labels: size/L, approved

#1655 chore: add Makefile rule to clean up unused images
  docs/development.md
Labels: lgtm, size/S, approved

#1657 Enable cloud logging API in CI projects
  e2e/testinfra/terraform/common/services.tf
Labels: size/XS, lgtm, approved

#1659 Fix retry in postsync cloud logging tests
  e2e/testcases/postsync_logging_test.go
Labels: size/XS, lgtm, approved

#1660 chore: bump otelcontribcol to 0.118.0-gke.9
  Makefile
Labels: size/XS, lgtm, approved

#1661 Remove buildx builder instance after image push
  Makefile.build
Labels: size/XS, lgtm, approved

#1663 test: wait for GKE cluster readiness
  e2e/nomostest/clusters/gke.go
  e2e/nomostest/retry/retry.go
Labels: size/M, lgtm, approved

#1664 test: Update Bitbucket workspace
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/XS, lgtm, approved

#1667 test: Revert parsing hack for go-junit-report
  build/prow/e2e/Dockerfile
  cmd/junit-report/resetfailure/reset_failure.go
  go.mod
  go.sum
  scripts/e2e.sh
  vendor/github.com/jstemmer/go-junit-report/v2/gtr/gtr.go
  vendor/github.com/jstemmer/go-junit-report/v2/junit/junit.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#1669 Revert "test: Revert parsing hack for go-junit-report (#1667)"
  build/prow/e2e/Dockerfile
  cmd/junit-report/resetfailure/reset_failure.go
  go.mod
  go.sum
  scripts/e2e.sh
  vendor/github.com/jstemmer/go-junit-report/v2/gtr/gtr.go
  vendor/github.com/jstemmer/go-junit-report/v2/junit/junit.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#1670 [cherry-pick] test: Update Bitbucket workspace (#1664)
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/XS, lgtm, approved

#1666 test: add checks for Config Sync _sync labels on reconciler metrics
  e2e/testcases/otel_collector_test.go
Labels: size/L, lgtm, approved

#1671 chore: update Go version to 1.24.3 in Makefile and go.mod
  Makefile
Labels: size/XS, lgtm, approved

#1674 chore: add issue templates
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/question.yaml
Labels: size/L, lgtm, approved

#1673 ci: configure dependabot for gomod
  .github/dependabot.yml
Labels: lgtm, size/S, approved

#1682 chore: update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1681 ci: skip kind updates in dependabot
  .github/dependabot.yml
Labels: size/XS, lgtm, approved

#1689 ci: increase memory request and limits for helm-sync on Autopilot
  e2e/testcases/helm_sync_test.go
Labels: size/XS, lgtm, approved

#1688 ci: install go-junit-report at runtime
  Makefile
  Makefile.e2e
  build/prow/e2e/Dockerfile
  tools/tools.go
  vendor/github.com/jstemmer/go-junit-report/v2/.gitignore
  vendor/github.com/jstemmer/go-junit-report/v2/CONTRIBUTING.md
  vendor/github.com/jstemmer/go-junit-report/v2/Makefile
  vendor/github.com/jstemmer/go-junit-report/v2/README.md
  vendor/github.com/jstemmer/go-junit-report/v2/internal/gojunitreport/go-junit-report.go
  vendor/github.com/jstemmer/go-junit-report/v2/main.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/benchmark.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/event.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/gotest.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/internal/collector/collector.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/json.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/report_builder.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#1690 chore: bump github.com/jstemmer/go-junit-report/v2 from 2.0.0 to 2.1.0
  cmd/junit-report/resetfailure/reset_failure.go
  go.mod
  go.sum
  scripts/e2e.sh
  vendor/github.com/jstemmer/go-junit-report/v2/Makefile
  vendor/github.com/jstemmer/go-junit-report/v2/README.md
  vendor/github.com/jstemmer/go-junit-report/v2/gtr/gtr.go
  vendor/github.com/jstemmer/go-junit-report/v2/internal/gojunitreport/go-junit-report.go
  vendor/github.com/jstemmer/go-junit-report/v2/junit/junit.go
  vendor/github.com/jstemmer/go-junit-report/v2/main.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/event.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/gotest.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/internal/collector/collector.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/internal/reader/reader.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/json.go
  vendor/github.com/jstemmer/go-junit-report/v2/parser/gotest/report_builder.go
  vendor/modules.txt
Labels: size/XXL, lgtm, approved

#1694 ci: ensure go-junit-report is available in local gobin
  Makefile
Labels: size/XS, lgtm, approved

#1692 test: add target to update expect kustomization file
  Makefile
  scripts/test-kustomization.sh
Labels: lgtm, size/S, approved

#1707 [cherry-pick] ci: increase memory request and limits for helm-sync on Autopilot
  e2e/testcases/helm_sync_test.go
Labels: size/XS, lgtm, approved

#1693 test: fix hasTolerations segfault
  e2e/testcases/reconciler_manager_test.go
Labels: size/XS, lgtm, approved

#1715 chore: bump controller-runtime from 0.20.4 to 0.21.0
  go.mod
  go.sum
  vendor/github.com/open-policy-agent/cert-controller/pkg/rotator/rotator.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/.golangci.yml
  vendor/sigs.k8s.io/controller-runtime/Makefile
  vendor/sigs.k8s.io/controller-runtime/OWNERS_ALIASES
  vendor/sigs.k8s.io/controller-runtime/README.md
  vendor/sigs.k8s.io/controller-runtime/alias.go
  vendor/sigs.k8s.io/controller-runtime/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/multi_namespace_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/config/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/priorityqueue/priorityqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/binaries.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/event/event.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/enqueue_mapped.go
  vendor/sigs.k8s.io/controller-runtime/pkg/handler/eventhandler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/metrics/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/metrics/workqueue.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/source/event_handler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/source/kind.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/warning_handler.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/multi.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics/metrics.go
Labels: size/XXL, lgtm, approved

#1665 Refactor Otel Collector Googlecloud ConfigMap Generation
  pkg/metrics/otel.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
Labels: lgtm, approved, size/XL

#1717 fix: add completion message to nomos init command only
  cmd/nomos/initialize/init.go
  cmd/nomos/nomos.go
Labels: size/XS, lgtm, approved, tide/merge-method-squash

#1719 chore: bump base image for CVE fix
  Makefile
Labels: size/XS, lgtm, approved

#1722 fix: typo in ManagedResourceInUnmanagedNamespace
  pkg/importer/analyzer/validation/nonhierarchical/managed_namespace_validator.go
Labels: size/XS, lgtm, approved

#1723 test: use Watcher for validating Stalled errors
  e2e/nomostest/config_sync.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/testwatcher/watch.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/basic_test.go
  e2e/testcases/github_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/proxy_test.go
  e2e/testcases/reconciler_manager_test.go
Labels: size/L, lgtm, approved

#1721 test: add e2e test for adopting implicit namespace
  e2e/testcases/lifecycle_directives_test.go
Labels: size/M, lgtm, approved
