Repository GoogleContainerTools/config-sync, pull requests merged in 2025-06, with the labels that each got.

#1731 chore: bump base image and git-sync
  Makefile
Labels: size/XS, lgtm, approved

#1736 [cherry-pick] fix: handle IsNoMatchError for remediator startWatch (#1734)
  pkg/remediator/watch/filteredwatcher.go
Labels: size/XS, lgtm, approved

#1740 fix: remove deprecated gcp plugin from r-g-ctrllr
  pkg/resourcegroup/controllers/runner/run.go
Labels: size/XS, lgtm, approved

#1745 [cherry-pick] fix: register auth plugins for nomos (#1739)
  cmd/nomos/nomos.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure_stub.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/plugins.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/plugins_providers.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#1744 fix: add validation to spec.helm.chart
  e2e/testcases/helm_sync_test.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/validate/rsync/validate/source_spec_validator.go
  pkg/validate/rsync/validate/source_spec_validator_test.go
Labels: size/L, lgtm, approved

#1752 [cherry-pick]: bump nginx image used by TestDeclaredFieldsPod
  e2e/testcases/declared_fields_test.go
Labels: lgtm, size/S, approved

#1747 chore: clean up new source spec secret errors
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/constants.go
  pkg/reconcilermanager/controllers/validate_secret.go
  pkg/reconcilermanager/controllers/validate_secret_test.go
  pkg/validate/rsync/validate/source_spec_validator.go
Labels: size/M, lgtm, approved

#1757 chore: bump git-sync to v4.4.2
  Makefile
Labels: size/XS, lgtm, approved
