Repository GoogleContainerTools/config-sync, pull requests merged in 2025-03, with the labels that each got.

#1582 chore: bump git-sync to v4.3.0-gke.11__linux_amd64
  Makefile
Labels: size/XS, lgtm, approved

#1583 chore: bump otelcontribcol to v0.103.0-gke.8
  Makefile
Labels: size/XS, lgtm, approved

#1577 test: re-introduce e2e syncing condition validation
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/testwatcher/watch.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/gatekeeper_test.go
  e2e/testcases/github_test.go
  e2e/testcases/helm_sync_test.go
  e2e/testcases/invalid_auth_test.go
  e2e/testcases/invalid_git_branch_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/namespace_repo_test.go
  e2e/testcases/namespace_selectors_test.go
  e2e/testcases/namespace_strategy_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/oci_sync_test.go
  e2e/testcases/policy_dir_test.go
  e2e/testcases/private_cert_secret_test.go
  e2e/testcases/remediator_test.go
  e2e/testcases/root_sync_test.go
  e2e/testcases/sync_ordering_test.go
Labels: size/L, lgtm, approved

#1584 chore: bump debian-base to bookworm-v1.0.4-gke.4
  Makefile
Labels: size/XS, lgtm, approved

#1571 fix: ResourceGroup unnecessary condition updates
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
Labels: size/M, lgtm, approved

#1581 test: remove obsolete comments and wrap Validate with nt.Must
  e2e/testcases/cluster_selectors_test.go
Labels: size/L, lgtm, approved

#1574 fix: ResourceGroup status updates missed
  pkg/resourcegroup/controllers/root/root_controller.go
Labels: size/M, lgtm, approved

#1588 fix: inventory client deleting unmanaged fields
  internal/third_party/github.com/GoogleContainerTools/kpt/pkg/live/inventoryrg.go
  vendor/github.com/GoogleContainerTools/kpt/pkg/live/inventoryrg.go
Labels: size/L, lgtm, approved

#1572 fix: ResourceGroup resource reconcile status
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
Labels: size/L, lgtm, approved

#1590 chore: Remove TODOs in ResourceGroup controller
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
Labels: lgtm, size/S, approved

#1594 test: refactor WatchForSync to take opt struct
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/profiling_test.go
Labels: size/M, lgtm, approved

#1592 test: truncate Pod logs for each test case
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
Labels: lgtm, size/S, approved

#1579 test: add ResourceGroup assertions to WatchForSync
  e2e/nomostest/sync.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/testresourcegroup/resourcegroup.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/basic_test.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/override_reconcile_timeout_test.go
  e2e/testcases/status_enablement_test.go
  pkg/resourcegroup/controllers/root/root_controller.go
  pkg/resourcegroup/controllers/status/status.go
  pkg/resourcegroup/resourcegroup.go
  pkg/resourcegroup/resourcegroup_test.go
Labels: size/L, lgtm, approved

#1596 test: cleanup ResourceGroup controller e2e tests
  e2e/nomostest/testkubeclient/client.go
  e2e/testcases/cluster_selectors_test.go
  e2e/testcases/custom_resource_definitions_test.go
  e2e/testcases/custom_resources_test.go
  e2e/testcases/multiversion_test.go
  e2e/testcases/resource_group_controller_test.go
Labels: size/L, lgtm, approved

#1587 Update gcloud image to latest version
  Makefile
Labels: size/XS, lgtm, approved

#1593 e2e: Use Semantic.DeepEqual to test empty status
  e2e/testcases/status_enablement_test.go
Labels: size/XS, lgtm, approved

#1597 test: fix uses of RetryOnConflict
  e2e/testcases/reconciler_manager_test.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
Labels: size/M, lgtm, approved

#1598 test: fix coredns helm chart to reconcile
  e2e/testdata/helm-charts/coredns/templates/configmap.yaml
  e2e/testdata/helm-charts/coredns/templates/service.yaml
  e2e/testdata/helm-charts/coredns/templates/serviceaccount.yaml
Labels: size/XS, lgtm, approved

#1599 test: skip resourcegroup checks in stress tests
  e2e/testcases/stress_test.go
Labels: size/XS, lgtm, approved

#1602 test: make KubeClient print object kind and type
  e2e/nomostest/testkubeclient/client.go
Labels: lgtm, size/S, approved

#1601 test: Fix TestStressManyDeployments reconciling
  e2e/flags.go
  e2e/nomostest/client.go
  e2e/testcases/main_test.go
  e2e/testcases/stress_test.go
Labels: size/M, lgtm, approved

#1603 test: fix TestStressResourceGroup
  e2e/testcases/stress_test.go
Labels: size/M, lgtm, approved

#1606 test: remove dead code in flag code
  e2e/testcases/main_test.go
Labels: size/XS, lgtm, approved

#1600 test: fix ResourceGroup expectations
  e2e/nomostest/sync.go
  e2e/nomostest/wait_for_sync.go
  e2e/testcases/status_enablement_test.go
  e2e/testcases/stress_test.go
Labels: size/M, lgtm, approved

#1610 style: remove unused cluster config functions
  pkg/api/configmanagement/v1/cluster_config.go
Labels: size/M, lgtm, approved

#1609 test: Fix TestKCCResourceGroup
  e2e/nomostest/testkubeclient/client.go
  e2e/testcases/kcc_test.go
  e2e/testcases/resource_group_controller_test.go
  e2e/testcases/stress_test.go
Labels: size/L, lgtm, approved

#1612 chore: update git-sync for CVE fix gkecl/1292759
  Makefile
Labels: size/XS, lgtm, approved

#1607 chore: Update Helm to fix CVE-2025-22870
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#1611 feat: Delete the ResourceGroup when the RSync is deleted
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/reconciler_manager_test.go
  pkg/core/scheme.go
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#1614 chore: fix Kustomize deprecated field commonLabels in helm test
  e2e/testdata/hydration/helm-components-remote-values-kustomization.yaml
  e2e/testdata/hydration/helm-overlay/base/base_value_overrides.yaml
  e2e/testdata/hydration/helm-overlay/base/kustomization.yaml
  e2e/testdata/hydration/helm-overlay/kustomization.yaml
  e2e/testdata/hydration/remote-overlay-kustomization.yaml
  e2e/testdata/hydration/resource-duplicate/kustomization.yaml
Labels: size/M, lgtm, approved

#1613 chore: update base image, Helm and Otelcontribcol
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#1615 refactor: consolidate constants used by resourcegroup
  e2e/nomostest/testresourcegroup/resourcegroup.go
  e2e/testcases/kcc_test.go
  e2e/testcases/stress_test.go
  pkg/applier/applier.go
  pkg/applier/clientset.go
  pkg/applier/constants.go
  pkg/applier/utils.go
  pkg/metadata/annotations.go
  pkg/reconcilermanager/controllers/util.go
  pkg/resourcegroup/controllers/metrics/metrics.go
  pkg/resourcegroup/controllers/metrics/record.go
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
  pkg/resourcegroup/controllers/status/status.go
  pkg/resourcegroup/resourcegroup.go
  pkg/resourcegroup/resourcegroup_test.go
Labels: size/L, lgtm, approved

#1617 test: log more details for unexpected status
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/wait.go
Labels: size/M, lgtm, approved

#1569 test: refactor some unit tests to use exact errors
  pkg/declared/namespace_safeguard_test.go
  pkg/remediator/reconcile/reconciler_test.go
  pkg/validate/raw/validate/source_spec_validator_test.go
Labels: size/M, lgtm, approved

#1618 test: refine ResourceGroup expectations
  e2e/nomostest/sync.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/nomostest/testresourcegroup/resourcegroup.go
Labels: size/M, lgtm, approved

#1621 chore: remove owner refs dead code
  pkg/reconcilermanager/controllers/reconciler_base.go
Labels: size/XS, lgtm, approved

#1620 refactor: return bool from metadata methods
  e2e/nomostest/deletion_propagation.go
  e2e/testcases/otel_collector_test.go
  pkg/core/decorate.go
  pkg/core/decorate_test.go
  pkg/reconcilermanager/controllers/otel_base_controller.go
  pkg/reconcilermanager/controllers/reconciler_base.go
Labels: size/XXL, lgtm, approved

#1622 refactor: cleanup UpdateStatusMode
  pkg/applier/applier.go
Labels: lgtm, size/S, approved

#1623 test: fix stress test being OOMKilled
  e2e/nomostest/testpredicates/predicates.go
Labels: size/XS, lgtm, approved
