Repository GoogleContainerTools/config-sync, pull requests merged in 2025-04, with the labels that each got.

#1625 e2e: fix OOMKill when testing with --debug
  pkg/util/log/stringer.go
  pkg/util/log/stringer_test.go
Labels: size/L, lgtm, approved

#1628 fix: omit resource statuses when status is disabled
  pkg/applier/inventory/inventory_converter.go
  pkg/applier/inventory/inventory_converter_test.go
Labels: size/L, lgtm, approved

#1629 refactor: Add enum for StatusMode
  cmd/reconciler/main.go
  e2e/testcases/status_enablement_test.go
  e2e/testcases/stress_test.go
  pkg/applier/applier.go
  pkg/applier/applier_test.go
  pkg/applier/clientset.go
  pkg/applier/inventory/inventory_converter.go
  pkg/applier/inventory/inventory_converter_test.go
  pkg/metadata/annotations.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/util.go
  pkg/resourcegroup/resourcegroup.go
Labels: size/L, lgtm, approved

#1631 feat: add completion message to main command execution
  cmd/nomos/nomos.go
Labels: size/XS, lgtm, approved

#1634 refactor: Add ManagementMode enum
  e2e/nomostest/clean.go
  e2e/nomostest/metrics/expectations.go
  e2e/nomostest/testpredicates/predicates.go
  e2e/testcases/ignore_mutation_test.go
  e2e/testcases/local_config_test.go
  e2e/testcases/managed_resources_test.go
  e2e/testcases/namespace_strategy_test.go
  e2e/testcases/namespaces_test.go
  e2e/testcases/sync_ordering_test.go
  pkg/applier/applier.go
  pkg/applier/applier_test.go
  pkg/applier/inventory/inventory_converter.go
  pkg/applier/inventory/inventory_converter_test.go
  pkg/applier/utils.go
  pkg/diff/diff.go
  pkg/diff/precedence.go
  pkg/hydrate/clean.go
  pkg/importer/analyzer/validation/nonhierarchical/management_annotation_validator.go
  pkg/metadata/annotation_management_mode.go
  pkg/metadata/annotations.go
  pkg/metadata/metadata.go
  pkg/metadata/metadata_test.go
  pkg/parse/annotations.go
  pkg/parse/annotations_test.go
  pkg/parse/root_reconciler_test.go
  pkg/remediator/reconcile/reconciler.go
  pkg/syncer/differ/decorations.go
  pkg/syncer/differ/differ.go
  pkg/syncer/differ/differ_test.go
  pkg/syncer/differ/namespace.go
  pkg/syncer/differ/namespace_test.go
  pkg/syncer/syncertest/reconcile.go
  pkg/validate/final/validate/unmanaged_namespace_validator.go
  pkg/validate/final/validate/unmanaged_namespace_validator_test.go
  pkg/validate/raw/validate/annotation_validator_test.go
  pkg/validate/raw/validate/management_annotation.go
  pkg/validate/raw/validate/management_annotation_test.go
  pkg/validate/validate_test.go
  pkg/webhook/fields_test.go
  pkg/webhook/validate_test.go
Labels: lgtm, approved, size/XL

#1636 refactor: ManagementAnnotation readability
  pkg/validate/raw/validate/management_annotation.go
Labels: size/XS, lgtm, approved

#1626 feat: unmanage orphaned objects during RSync deletion
  e2e/nomostest/config_sync.go
  e2e/nomostest/new.go
  e2e/nomostest/nt.go
  e2e/nomostest/ntopts/multi_repo.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/sync_ordering_test.go
  pkg/metadata/annotations.go
  pkg/metadata/metadata.go
  pkg/parse/annotations.go
  pkg/reconciler/finalizer/base_finalizer.go
  pkg/reconciler/finalizer/controller.go
  pkg/reconciler/finalizer/finalizer.go
  pkg/reconciler/finalizer/reposync_finalizer.go
  pkg/reconciler/finalizer/reposync_finalizer_test.go
  pkg/reconciler/finalizer/rootsync_finalizer.go
  pkg/reconciler/finalizer/rootsync_finalizer_test.go
  pkg/reconciler/reconciler.go
  pkg/syncer/syncertest/fake/storage.go
Labels: lgtm, approved, size/XL

#1638 test: fix TestSplitRSyncsWithDeletion on CSR
  e2e/testcases/sync_ordering_test.go
  e2e/testinfra/terraform/modules/service_account/service_account.tf
Labels: lgtm, size/S, approved

#1639 refactor: DeletionPropagationPolicy helpers
  e2e/nomostest/clean.go
  e2e/nomostest/config_sync.go
  e2e/nomostest/deletion_propagation.go
  e2e/nomostest/reset.go
  e2e/testcases/reconciler_finalizer_test.go
  e2e/testcases/reconciler_manager_test.go
  pkg/metadata/annotation_deletion_propagation_policy.go
  pkg/metadata/annotations.go
  pkg/reconciler/finalizer/controller.go
  pkg/reconciler/finalizer/reposync_finalizer_test.go
  pkg/reconciler/finalizer/rootsync_finalizer_test.go
Labels: size/L, lgtm, approved

#1640 test: fix TestMaxRepoSyncNameLength test flake
  e2e/testcases/basic_test.go
Labels: lgtm, size/S, approved

#1642 chore: update Debian base image version to bookworm-v1.0.4-gke.7
  Makefile
Labels: size/XS, lgtm, approved

#1643 chore: Bump git-sync to v4.3.0-gke.16__linux_amd64
  Makefile
Labels: size/XS, lgtm, approved

#1644 chore: Bump otelcontribcol to v0.118.0-gke.7
  Makefile
Labels: size/XS, lgtm, approved

#1641 perf: Reduce inventory update request size
  go.mod
  go.sum
  pkg/applier/clientset.go
  pkg/applier/inventory/inventory_converter.go
  pkg/applier/inventory/inventory_converter_test.go
  pkg/applier/status.go
  pkg/applier/status_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/cli-utils/pkg/apis/actuation/actuationstatus_string.go
  vendor/sigs.k8s.io/cli-utils/pkg/apis/actuation/actuationstrategy_string.go
  vendor/sigs.k8s.io/cli-utils/pkg/apis/actuation/reconcilestatus_string.go
  vendor/sigs.k8s.io/cli-utils/pkg/apis/actuation/types.go
  vendor/sigs.k8s.io/cli-utils/pkg/apis/actuation/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/cli-utils/pkg/apply/task/inv_add_task.go
  vendor/sigs.k8s.io/cli-utils/pkg/inventory/configmap-client-factory.go
  vendor/sigs.k8s.io/cli-utils/pkg/inventory/inventory-client.go
  vendor/sigs.k8s.io/cli-utils/pkg/inventory/inventorycm.go
  vendor/sigs.k8s.io/cli-utils/pkg/inventory/status-policy.go
  vendor/sigs.k8s.io/cli-utils/pkg/inventory/statuspolicy_string.go
  vendor/sigs.k8s.io/cli-utils/pkg/object/object_status_set.go
Labels: size/XXL, lgtm, approved

#1648 test: fix fake client resource in errors
  pkg/reconciler/finalizer/reposync_finalizer_test.go
  pkg/reconciler/finalizer/rootsync_finalizer_test.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
  pkg/syncer/client/client_test.go
  pkg/syncer/syncertest/fake/common.go
  pkg/util/mutate/mutate_test.go
Labels: lgtm, size/S, approved

#1646 chore: fix CVE-2025-22872 in helm and otelcontribcol
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#1650 test: fix TestOtelCollectorDeployment expectation
  e2e/testcases/otel_collector_test.go
Labels: size/XS, lgtm, approved

#1649 fix: remove RSync object from validation errors
  cmd/nomoserrors/examples/examples.go
  pkg/reconcilermanager/controllers/helm_value_files.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
  pkg/validate/raw/raw.go
  pkg/validate/raw/validate/repo_sync_validator.go
  pkg/validate/raw/validate/root_sync_validator.go
  pkg/validate/raw/validate/source_spec_validator_test.go
  pkg/validate/rsync/validate/deletion_propagation_validator.go
  pkg/validate/rsync/validate/deletion_propagation_validator_test.go
  pkg/validate/rsync/validate/source_spec_validator.go
  pkg/validate/rsync/validate/source_spec_validator_test.go
  pkg/validate/validate_test.go
Labels: size/XXL, lgtm, approved

#1651 test: add assertions to adoption test case
  e2e/testcases/adopt_client_side_applied_test.go
Labels: size/M, lgtm, approved
