Repository GoogleContainerTools/config-sync, pull requests merged in 2025-01, with the labels that each got.

#1521 Update manifest copyright to satisfy linter
  manifests/cluster-selector-crd.yaml
  manifests/hierarchyconfig-crd.yaml
  manifests/namespace-selector-crd.yaml
  manifests/reposync-crd.yaml
  manifests/resourcegroup-crd.yaml
  manifests/rootsync-crd.yaml
Labels: lgtm, size/S, approved

#1522 e2e: fix version check failing when zero nodes
  e2e/nomostest/nt.go
Labels: size/M, lgtm, approved

#1520 Bump helm version
  Makefile
  pkg/hydrate/tool_util.go
Labels: size/XS, lgtm, approved

#1525 [chore] Bump otelcontribcol version
  Makefile
Labels: size/XS, lgtm, approved

#1524 chore: use scheme to get GVK of typed objects
  e2e/nomostest/config_sync.go
  e2e/testcases/composition_test.go
  e2e/testcases/multi_sync_test.go
  pkg/applier/applier.go
  pkg/applier/utils.go
  pkg/applier/utils_test.go
Labels: size/M, lgtm, approved

#1527 chore: update IsManageableSystemNamespace
  pkg/syncer/differ/special_namespaces.go
Labels: size/XS, lgtm, approved

#1528 chore: improve the InvalidCRDName error message
  pkg/importer/analyzer/validation/nonhierarchical/crd_name_validator.go
Labels: size/XS, lgtm, approved

#1523 chore: migrate from v1beta1 CRD to v1 internally
  cmd/nomoserrors/examples/examples.go
  pkg/core/k8sobjects/crds.go
  pkg/core/k8sobjects/objects.go
  pkg/declared/resources.go
  pkg/hydrate/tool_util.go
  pkg/importer/analyzer/validation/nonhierarchical/crd_name_validator.go
  pkg/importer/customresources/customresources.go
  pkg/importer/customresources/customresources_test.go
  pkg/parse/repo_sync_parser.go
  pkg/parse/root_sync_parser.go
  pkg/syncer/decode/decode.go
  pkg/testing/discoverytest/discovery_client.go
  pkg/util/clusterconfig/crd.go
  pkg/util/clusterconfig/crd_test.go
  pkg/util/discovery/scoper.go
  pkg/util/discovery/scoper_builder.go
  pkg/util/discovery/scoper_test.go
  pkg/validate/fileobjects/raw.go
  pkg/validate/raw/validate/cluster_selector_validator_test.go
  pkg/validate/raw/validate/crd_name.go
  pkg/validate/raw/validate/crd_name_test.go
  pkg/validate/raw/validate/crd_removal_validator.go
  pkg/validate/raw/validate/crd_removal_validator_test.go
  pkg/validate/raw/validate/illegal_crd_validator.go
  pkg/validate/raw/validate/illegal_crd_validator_test.go
  pkg/validate/raw/validate/management_annotation_test.go
  pkg/validate/validate.go
  pkg/validate/validate_test.go
Labels: size/XXL, lgtm, approved

#1518 chore: Update to Go 1.23
  go.mod
  test/docker/presync-webhook-server/go.mod
Labels: size/XS, lgtm, approved

#1533 ci: fix vuln scan jq to use location in noteName
  scripts/vulnerabilities.sh
Labels: size/XS, lgtm, approved

#1534 [cherry-pick] ci: fix vuln scan jq to use location in noteName (#1533)
  scripts/vulnerabilities.sh
Labels: size/XS, lgtm, approved

#1535 Add gcloud auth requirement to docs
  docs/development.md
Labels: lgtm, size/S, approved

#1536 chore: bump git-sync to v4.3.0-gke.7
  Makefile
Labels: size/XS, lgtm, approved
