Repository GoogleContainerTools/config-sync, pull requests merged in 2025-09, with the labels that each got.

#1868 chore: bump git-sync to v4.4.2-gke.3
  Makefile
Labels: size/XS, lgtm, approved

#1870 fix: Update import path and dependencies
  e2e/nomostest/sync-status-watch-controller.go
  examples/post-sync/controller.go
  examples/post-sync/controller_test.go
  examples/post-sync/go.mod
  examples/post-sync/go.sum
  examples/post-sync/main.go
Labels: size/L, ok-to-test, lgtm, approved

#1873 fix: improve `nomos status` output when no sync objects are found
  cmd/nomos/status/client.go
  cmd/nomos/status/status_test.go
Labels: size/L, lgtm, approved

#1875 test: log ResourceGroup diff on unexpected updates
  e2e/nomostest/testwatcher/watch.go
  e2e/testcases/resource_group_controller_test.go
Labels: lgtm, size/S, approved

#1891 test: update expected image digest
  e2e/testcases/gcenode_test.go
Labels: lgtm, size/S, approved
