Repository GoogleContainerTools/config-sync, pull requests merged in 2025-02, with the labels that each got.

#1540 chore: bump golint to 1.63.4
  Makefile
  e2e/nomostest/gitproviders/repository.go
  pkg/util/log/stringer.go
Labels: lgtm, size/S, approved

#1541 test: configurable google auth for oci sig server
  test/docker/presync-webhook-server/oci-signature-verification-server.go
Labels: lgtm, size/S, approved

#1543 test: set USE_GOOGLE_AUTHENTICATOR for oci sig server
  e2e/nomostest/oci-image-verification-server.go
Labels: size/XS, lgtm, approved

#1542 refactor: relocate ResourceGroup GVK definition
  cmd/nomos/status/client.go
  pkg/api/kpt.dev/v1alpha1/groupversion_info.go
  pkg/applier/applier_test.go
  pkg/applier/clientset.go
  pkg/applier/destroyer_test.go
  pkg/applier/utils.go
  pkg/bugreport/bugreport.go
  pkg/resourcegroup/resourcegroup.go
  pkg/webhook/resource_group.go
Labels: size/M, lgtm, approved

#1547 cleanup: remove unused kptfile related code
  pkg/importer/reader/parse_file.go
  pkg/importer/reader/parse_file_test.go
  pkg/kinds/kinds.go
Labels: size/L, lgtm, approved

#1549 chore: update to gcr.io/gke-release/debian-base:bookworm-v1.0.4-gke.2
  Makefile
Labels: size/XS, lgtm, approved

#1550 chore: git-sync update v4.3.0-gke.9__linux_amd64
  Makefile
Labels: size/XS, lgtm, approved

#1548 test: add controllerName to rsync unit tests
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: lgtm, size/S, approved

#1545 test: add e2e tests to verify the max RSync NN length
  e2e/testcases/basic_test.go
Labels: size/L, lgtm, approved

#1555 chore: update to gcr.io/gke-release/debian-base:bookworm-v1.0.4-gke.3
  Makefile
Labels: size/XS, lgtm, approved

#1556 Revert "test: add e2e tests to verify the max RSync NN length"
  e2e/testcases/basic_test.go
Labels: size/L, lgtm, approved

#1560 chore: upgrade k8s libs to 1.32.2
  go.mod
  go.sum
  vendor/k8s.io/api/resource/v1alpha3/generated.proto
  vendor/k8s.io/api/resource/v1alpha3/types.go
  vendor/k8s.io/api/resource/v1alpha3/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1beta1/generated.proto
  vendor/k8s.io/api/resource/v1beta1/types.go
  vendor/k8s.io/api/resource/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/code-generator/kube_codegen.sh
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#1554 feat: validate RSync length in reconciler-manager
  e2e/testcases/basic_test.go
  e2e/testcases/multi_sync_test.go
  pkg/reconcilermanager/constants.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#1538 cleanup: Stop updating ManageConflictErrors for a remote RSync
  pkg/parse/root_sync_client.go
  pkg/parse/root_sync_client_test.go
  pkg/parse/run.go
Labels: size/L, lgtm, approved

#1564 chore: allow PartialObjectMetadata in fake client
  pkg/syncer/syncertest/fake/client.go
  pkg/syncer/syncertest/fake/convert.go
  pkg/syncer/syncertest/fake/dynamic_client.go
  pkg/syncer/syncertest/fake/storage.go
  pkg/syncer/syncertest/fake/subresource_storage.go
Labels: size/L, lgtm, approved

#1563 chore: minor cleanup to reconilcer controllers
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#1565 chore: extract otelBaseController
  cmd/reconciler-manager/main.go
  pkg/reconcilermanager/controllers/otel_base_controller.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_controller_test.go
  pkg/reconcilermanager/controllers/otel_sa_controller.go
Labels: size/L, lgtm, approved

#1551 fix: reconfigure controllers to use klog via logr
  cmd/admission-webhook/main.go
  cmd/reconciler-manager/main.go
  cmd/reconciler/main.go
  pkg/reconciler/reconciler.go
  pkg/reconcilermanager/controllers/crd_controller.go
  pkg/reconcilermanager/controllers/garbage_collector.go
  pkg/reconcilermanager/controllers/helm_value_files.go
  pkg/reconcilermanager/controllers/logging_controller.go
  pkg/reconcilermanager/controllers/otel_base_controller.go
  pkg/reconcilermanager/controllers/otel_controller.go
  pkg/reconcilermanager/controllers/otel_sa_controller.go
  pkg/reconcilermanager/controllers/reconciler_base.go
  pkg/reconcilermanager/controllers/reconciler_base_test.go
  pkg/reconcilermanager/controllers/reconciler_finalizer_handler.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_manager_test.go
  pkg/reconcilermanager/controllers/secret.go
  pkg/reconcilermanager/controllers/secret_test.go
  pkg/resourcegroup/controllers/handler/handler_test.go
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
  pkg/resourcegroup/controllers/root/main_test.go
  pkg/resourcegroup/controllers/root/root_controller.go
  pkg/resourcegroup/controllers/runner/run.go
  pkg/resourcegroup/controllers/typeresolver/typeresolver.go
  pkg/resourcegroup/controllers/typeresolver/typeresolver_test.go
  pkg/resourcegroup/controllers/watch/filteredwatcher.go
Labels: lgtm, approved, size/XL

#1570 fix: ResourceGroup unnecessary timestamp updates
  pkg/resourcegroup/controllers/resourcegroup/condition.go
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
Labels: size/M, lgtm, approved

#1573 fix: ResourceGroup controller stuck retrying
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
  pkg/resourcegroup/controllers/root/root_controller.go
Labels: size/M, lgtm, approved

#1578 chore: return error from gitSyncEnvs instead of logging the error
  pkg/reconcilermanager/controllers/gitsync_env.go
  pkg/reconcilermanager/controllers/reposync_controller.go
  pkg/reconcilermanager/controllers/reposync_controller_test.go
  pkg/reconcilermanager/controllers/rootsync_controller.go
  pkg/reconcilermanager/controllers/rootsync_controller_test.go
Labels: size/L, lgtm, approved

#1576 fix: ResourceGroup resource status bugs
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
  pkg/resourcegroup/controllers/root/root_controller.go
Labels: size/L, lgtm, approved
