Repository GoogleContainerTools/config-sync, pull requests merged in 2025-08, with the labels that each got.

#1807 test: add helper function to check if using a Google git provider
  e2e/nomostest/gitproviders/git-provider.go
  e2e/nomostest/ssh.go
  e2e/testcases/multi_sync_test.go
  e2e/testcases/reconciler_manager_test.go
Labels: lgtm, size/S, approved

#1809 chore: bump git-sync to v4.4.2-gke.2
  Makefile
Labels: size/XS, lgtm, approved

#1810 chore: bump debian-base to bookworm-v1.0.5-gke.9
  Makefile
Labels: size/XS, lgtm, approved

#1812 test: fix metrics flake in TestSurfaceFightError
  e2e/testcases/remediator_test.go
Labels: size/M, lgtm, approved

#1815 refactor: fightThreshold global variable
  cmd/reconciler/main.go
  e2e/testcases/remediator_test.go
  pkg/api/configsync/register.go
  pkg/reconciler/reconciler.go
  pkg/syncer/reconcile/apply.go
  pkg/syncer/reconcile/fight/detector.go
  pkg/syncer/reconcile/fight/detector_test.go
Labels: size/M, lgtm, approved

#1824 Skip delete repo if already marked for deletion
  e2e/nomostest/gitproviders/gitlab.go
Labels: lgtm, size/S, approved

#1827 test: update bitbucket workspace
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/XS, lgtm, approved

#1819 fix: Prevent adding ownership condition for NotFound objects
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller.go
  pkg/resourcegroup/controllers/resourcegroup/resourcegroup_controller_test.go
Labels: size/L, ok-to-test, lgtm, approved

#1836 test: delete unused testdata files
  e2e/testdata/2.5k-namespaces/rootsync.yaml
  e2e/testdata/clusterrolebinding-2-create.yaml
  e2e/testdata/clusterrolebinding-2-modify.yaml
  e2e/testdata/clusterrolebinding-create.yaml
  e2e/testdata/clusterrolebinding-modify.yaml
  e2e/testdata/invalid/clusterconfig-missing-kind.yaml
  e2e/testdata/invalid/clusterconfig-missing-spec.yaml
  e2e/testdata/invalid/clusterconfig-missing-version.yaml
  e2e/testdata/invalid/clusterconfig-missing-versions.yaml
  e2e/testdata/invalid/namespaceconfig-missing-kind.yaml
  e2e/testdata/invalid/namespaceconfig-missing-spec.yaml
  e2e/testdata/invalid/namespaceconfig-missing-version.yaml
  e2e/testdata/invalid/namespaceconfig-missing-versions.yaml
  e2e/testdata/invalid/service-invalid-name.yaml
  e2e/testdata/invalid/sync-missing-spec.yaml
  e2e/testdata/multiversion/v1.yaml
  e2e/testdata/multiversion/v1beta1.yaml
  e2e/testdata/namespaces/foo-with-metadata-update.yaml
  e2e/testdata/namespaces/foo-with-metadata.yaml
  e2e/testdata/namespaces/foo.yaml
  e2e/testdata/podsecuritypolicy-create.yaml
  e2e/testdata/podsecuritypolicy-modify.yaml
  e2e/testdata/preservefields/aggregate-clusterrole-modify.yaml
  e2e/testdata/preservefields/aggregate-clusterrole.yaml
  e2e/testdata/preservefields/configmap-add-annotation.yaml
  e2e/testdata/preservefields/configmap-add-label.yaml
  e2e/testdata/preservefields/configmap-no-labels-annotations.yaml
  e2e/testdata/preservefields/configmap-update-annotation.yaml
  e2e/testdata/preservefields/configmap-update-label.yaml
  e2e/testdata/preservefields/namespace-viewer-clusterrole-replace.yaml
  e2e/testdata/preservefields/namespace-viewer-clusterrole.yaml
  e2e/testdata/preservefields/rbac-viewer-clusterrole.yaml
  e2e/testdata/preservefields/service-modify.yaml
  e2e/testdata/preservefields/service.yaml
  e2e/testdata/reconciler-manager/rootsync-sample.yaml
  e2e/testdata/resource_conditions/clusterrole.yaml
  e2e/testdata/resource_conditions/configmap.yaml
  e2e/testdata/resource_conditions/constraint-crd.yaml
  e2e/testdata/resource_conditions/constraint-template-crd.yaml
  e2e/testdata/resource_conditions/constraint-template.yaml
  e2e/testdata/resource_conditions/constraint.yaml
  e2e/testdata/resourcequotas/pod-helloworld-cpu-hungry.yaml
  e2e/testdata/resourcequotas/pod-helloworld-mem-hungry.yaml
  e2e/testdata/resourcequotas/resourcequota-compute.yaml
  e2e/testdata/resourcequotas/resourcequota-configs-pods.yaml
  e2e/testdata/resourcequotas/resourcequota-configs.yaml
Labels: size/XXL, lgtm, approved

#1831 test: Add retry / skip logic and limit check for Bitbucket repository deletion
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/M, lgtm, approved

#1839 test: fix TestStressResourceGroup expectation
  e2e/testcases/stress_test.go
Labels: size/XS, lgtm, approved

#1841 test: parametrize the bitbucket workspace
  e2e/flags.go
  e2e/nomostest/gitproviders/bitbucket.go
Labels: size/M, lgtm, approved

#1822 fix: logic of when to print monorepo notice
  pkg/bugreport/bugreport.go
  pkg/bugreport/bugreport_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/interceptor/intercept.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/objectutil.go
Labels: size/XXL, lgtm, approved

#1851 test: Add t.Skip to failing test while a fix is worked on
  e2e/testcases/hydration_test.go
Labels: size/XS, lgtm, approved

#1853 v1.22.1: additional cherrypick to restore test coverage
  e2e/testcases/hydration_test.go
  e2e/testdata/hydration/compiled-json/helm-components/wordpress/deployment_my-wordpress.json
  e2e/testdata/hydration/compiled/helm-components/wordpress/deployment_my-wordpress.yaml
  e2e/testdata/hydration/helm-components-remote-values-kustomization.yaml
  e2e/testdata/hydration/helm-components/kustomization.yaml
Labels: lgtm, size/S, approved
